### ISSUE TITLE
Embedded Baubles

### ISSUE THREAD

**Issue by Nerdpie** [Thutmose/Pokecube#1]
I tried launching an instance of 1.8.8 with Pokécube installed, and Minecraft complained about having two copies of Baubles.  I checked, and I have a copy under mods/1.8.8, and there is a copy bundled in the Pokécube Core JAR.  This shouldn't be an issue right now, but once other mods start updating, you will VERY quickly run into API conflicts; you should probably list Baubles as a dependency without bundling it.  Just a quick heads-up!

**Comment by Thutmose** [comment]
ahh, baubles is updated to 1.8.8? I will remove it from pokecube if this is the case, as mentioned at the bottom of the readme.

**Comment by Nerdpie** [comment]
Yeah, hadn't seen the readme until later.  I don't know if it's officially supported or not, though; I mostly had taken a number of mods from a 1.8 instance and tried to launch under 1.8.8.  Bauble was one of the ones that didn't complain.

**Comment by Thutmose** [comment]
oh, if the 1.8 version works, then I will try using it.  I will test that asap.

**Comment by Thutmose** [comment]
Seems it might work indeed, I will remove the included version.

**Comment by Nerdpie** [comment]
Cool; I look forward to it.  I have been running into some crashes, but I'm not sure what level the issues are (MC, Forge, another mod, etc.), especially since I got some crashes before I even added Pokécube; I may pull it into a dev environment and poke around a bit tomorrow.

**Comment by Thutmose** [comment]
Baubles is officially for 1.8.8 now, I have uploaded a release which removes it from pokecube.

**Comment by Nerdpie** [comment]
Quick follow up: It works great... after you grab the right resources :facepalm:.  I love the timing of the Baubles update too.

**Comment by Thutmose** [comment]
by the way, this resource pack contains the sounds, and all of the mobs:
http://minecraft.curseforge.com/projects/pokecube-resources/files

**Comment by Nerdpie** [comment]
Cool.  I hadn't seen that yesterday when I checked; I'll switch to that after work.
