### ISSUE TITLE
Standard Monsters phased out over time (Could be config)

### ISSUE THREAD

**Issue by doctorkreger** [Thutmose/Pokecube#100]
#### Issue Description:
I have found it increasingly difficult to find a monster spawn in the world.

#### What happens:
There are many pokemobs, but I cannot find the vanilla minecraft enemies in the world. 

Is there any config options to help balance this?

**Comment by Thutmose** [comment]
Hmm, One might be to make the pokemobs cull more often.

You can do this by decreasing the cullDistance below the aiDisableDisance, and then enable cull.
This will remove any not-angry wild pokemob that is more than a certain distance from the player, and hopefully will free up areas for vanilla mobs to spawn.

**Comment by jochuan** [comment]
what version are you using ?

**Comment by Thutmose** [comment]
I have done some testing, and this seems to be solvable with the following config options:

mobSpawnNumber around 10 (default)
cullDistance set to 32 (or less)
maxSpawnRadius set to 32 (or less, don't set it more than cullDistance)
cull set to true

This results in the pokemobs despawning after the player gets too far away, and allows room for the vanilla mobs to spawn.

**Comment by doctorkreger** [comment]
This works well, thank you.

**Comment by jochuan** [comment]
after some time the mobs stopped spawning and i used those configs but if a legendary spawns and i get too far away from it did he will despawn too ? if so there is a way to change that for legendaries ?
