### ISSUE TITLE
pokedex bugs

### ISSUE THREAD

**Issue by jochuan** [Thutmose/Pokecube#101]
#### Issue Description:
Some bugs that occurs displaying some pokemons in the pokedex

#### What happens:
Mareep and flaaffy aren't shown as shadow in the pokedex maybe due to the dying code and steelix is too big
![2016-07-04_19 14 09](https://cloud.githubusercontent.com/assets/11268912/16597836/56dd15e2-42d1-11e6-96cb-763aca6afec1.png)
![2016-07-04_19 14 11](https://cloud.githubusercontent.com/assets/11268912/16597845/5c7a5f64-42d1-11e6-9794-c9cc34dcb251.png)
![2016-07-04_19 14 23](https://cloud.githubusercontent.com/assets/11268912/16597849/5f129e80-42d1-11e6-8a23-02b2732b34f6.png)

#### What you expected to happen:

they should be displayed properly

#### Steps to reproduce:

1.open your pokedex without have catching them

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:3.4.9
- Pokecube Revival (if applicable):3.4.8
- Pokecube Mobs (if applicable):2.1.5
- Minecraft: 1.8.9
- Forge:1976

**Comment by Thutmose** [comment]
got this fixed for next release.

**Comment by Thutmose** [comment]
The mareep/flaafy issue Will be fixed in next release of ThutCore, The Steelix issue should be fixed in Pokecube Core 3.5.0/4.2.0

**Comment by Thutmose** [comment]
Should be fixed in ThutCore 3.2.0 which is on curse now.
