### ISSUE TITLE
transparency to trainer skins

### ISSUE THREAD

**Issue by jochuan** [Thutmose/Pokecube#102]
#### Issue Description:
the bug catcher texture isn't transparent

#### What happens:
one part of the bug catcher texture should be transparent but in the game it isn't
![bug catcher](https://cloud.githubusercontent.com/assets/11268912/16598194/1479d332-42d3-11e6-81f3-1be53158d86e.png)
![2016-07-02_17 11 00](https://cloud.githubusercontent.com/assets/11268912/16598203/2675af0c-42d3-11e6-945b-fae31a940b24.png)

#### What you expected to happen:
it should be transparent

#### Steps to reproduce:

1.find a bug catcher

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:3.4.9
- Pokecube Revival (if applicable):3.4.8
- Pokecube Mobs (if applicable):2.1.5
- Minecraft: 1.9.4
- Forge:1967

**Comment by Thutmose** [comment]
I will see if I can do anything about this.

**Comment by Thutmose** [comment]
Fixed for next release:
![image](https://cloud.githubusercontent.com/assets/2363472/16603217/5b299d70-42e8-11e6-9314-e5323f69cc9b.png)

**Comment by Thutmose** [comment]
Fixed in Revival 3.4.12/4.1.12
