### ISSUE TITLE
Trainer card a way to save pokemons

### ISSUE THREAD

**Issue by jochuan** [Thutmose/Pokecube#103]
i was frustrated because i had to create a new world to go to the other minecraft version, in the old world i caught a lot of pokemons that i had spent a lot of hours playing to get them. So i have a idea for a item the "player card" it could only be obtained in creative when used it would open a gui with two buttons "save stats" and "load stats" when clicked in the save stats the game would scan every pokemon that is in the pc and the stats such as the number of unique captures and achievements of pokecube and it would save all that information in some part of .minecraft  inside a folder on a file that would be named ("player" card) the "player" would be the current player name and after that the item would disapear and if you created another world you could use the trainer card and click in the button load stats and it would scan the folder in .minecraft where the player cards files are located for a file with the name of the player and it would replace every pokemon of the pc with the ones that are on the "player"card file but it would only work if the player name matches the name of the file. This could be useful for server resets and other things like that

**Comment by Thutmose** [comment]
you can just copy over the pc inventory file in the world save

**Comment by jochuan** [comment]
And about the achievements and unique captures

**Comment by Thutmose** [comment]
the captures are in the pokecube.dat, and achivements are in one of the vanilla files, but you can get those back by sending out and recalling the pokemob.

**Comment by jochuan** [comment]
But if i caught one charmander and evolved it into a charmeleon i would only get the charmeleon achievement in the new world

**Comment by Thutmose** [comment]
ya, so then you need to find the vanilla achievements thing and move that over too, It is in world folder in the json in the folder called "stats"
