### ISSUE TITLE
Crash on pokedex

### ISSUE THREAD

**Issue by jochuan** [Thutmose/Pokecube#104]
#### Issue Description:
my game crashed

#### What happens:
my game crashed when i was navigating on the pokedex
https://gist.github.com/jochuan/40749c3a6e4528e40105824a08b8533b

#### What you expected to happen:

it shouldn't crash

#### Steps to reproduce:

1.open your pokedex 
2.keep looking through the pages

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:3.4.12
- Pokecube Revival (if applicable):3.4.11
- Pokecube Mobs (if applicable):2.1.5
- Minecraft: 1.8.9
- Forge:1976

**Comment by Thutmose** [comment]
This looks to be some issue with your graphics card and GL calls, does it always happen for a specific pokemob for you? I cannot replicate this.

**Comment by jochuan** [comment]
it must be my weak computer failing to renderize the models i think that i should close this since nothing can be done

**Comment by Thutmose** [comment]
if you can find if it is a specfic pokemob that crashes it, I might be able to help, but if it is just random due to the weak computer, I don't think there is anything I can do

**Comment by jochuan** [comment]
it was random so i will close this
