### ISSUE TITLE
Male trainers are using the alex model

### ISSUE THREAD

**Issue by jochuan** [Thutmose/Pokecube#105]
#### Issue Description:
 Male trainers are using the alex model

#### What happens:
They are using the alex model instead of the steve model that looks strange mostly on trainers like RoughNeck,Biker and on male trainers that dont have texture but the Bird Keeper dont have this issue
![2016-07-06_17 48 00](https://cloud.githubusercontent.com/assets/11268912/16634219/11bcd498-43a3-11e6-8435-2ca7c7deddfd.png)
![2016-07-06_17 46 29](https://cloud.githubusercontent.com/assets/11268912/16634222/16d30a42-43a3-11e6-9010-8507cda2d6be.png)
![2016-07-06_17 48 10](https://cloud.githubusercontent.com/assets/11268912/16634227/1da51cde-43a3-11e6-933f-73fdd4e14099.png)

#### What you expected to happen:

They should use the steve model

#### Steps to reproduce:

1.look at the trainers

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:3.4.12
- Pokecube Revival (if applicable):3.4.11
- Pokecube Mobs (if applicable):2.1.5
- Minecraft: 1.9.4
- Forge:1976

**Comment by Thutmose** [comment]
You need to set their gender to male if you spawn them in, the default trainer type is beauty, which is female, so you end up with female trainers.

If you change them to male, they should use the correct model.  They can only spawn in as males, so they only have male textures, but with the trainer editor they can be made to be male or female.
