### ISSUE TITLE
Cannot release pokemon from the PC

### ISSUE THREAD

**Issue by jochuan** [Thutmose/Pokecube#106]
#### What happens:
After clicking in the release button and selecting the pokemon to be released it get away from the selected slot making it impossible to release it

#### What you expected to happen:
it should be possible to release unwanted pokemon

#### Steps to reproduce:

1.go to the pc
2.try to release a pokemon

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:3.4.12
- Pokecube Revival (if applicable):3.4.11
- Pokecube Mobs (if applicable):2.1.5
- Minecraft: 1.9.4
- Forge:1976

**Comment by Thutmose** [comment]
Hmm, I bet i forgot to make it stop picking up when in release mode when I re-did the pc container.

**Comment by Thutmose** [comment]
Fixed in 3.5.0/4.2.0
