### ISSUE TITLE
[1.10.2] Insanely high spawn rates with spongeforge

### ISSUE THREAD

**Issue by XileForce** [Thutmose/Pokecube#107]
Essentially, the spawning becomes insane when spongeforge is installed. Vanilla mobs seemed relatively normal so im guessing it only affects pokecube mobs. As they say a picture is worth 1000 words so here you go. http://imgur.com/pbeK5QJ that was taken a few moments after running /pokecube kill all. 

PokeCube Core: 4.1.12
PokeCube Mobs: 2.1.5
PokeCube Revival: 4.1.11
ThutCore: 3.1.10
Forge: 12.18.0.2007

**Comment by Thutmose** [comment]
Fixed in recent commit to spongeforge.
