### ISSUE TITLE
[Sunwize] Some things you may be able to use

### ISSUE THREAD

**Issue by Robijnvogel** [Thutmose/Pokecube#11]
#### Issue Description:
I noticed that @sunwize has some branches that he never issued a pull-request for.
Maybe you could still use these three files though:
https://github.com/sunwize/Pokecube/commit/67e12e472758062d39d072351b003457b7a3601f
https://github.com/sunwize/Pokecube/commit/43bd29a7a89398f7c3171f91adcf68fb417aa91e
https://github.com/sunwize/Pokecube/commit/1ddbdf5fd8af8a2ba18ea763dee8e2b45914a945

Sunwize, if you're seeing this, please either pull or delete those branches.

**Comment by Thutmose** [comment]
I suggest that he delete them from there, and instead issue the PR to **https://github.com/Thutmose/Pokecube-Models** as that is where I moved the models to.  Those files are not really "needed" but are helpful for adding additional animations/details later.

**Comment by Thutmose** [comment]
I have manually merged these over now.
