### ISSUE TITLE
Minecraft crash on the server

### ISSUE THREAD

**Issue by carcanox32** [Thutmose/Pokecube#111]
Hello my minecraft crash when i go on the server so this is the crash report pls help me 

---- Minecraft Crash Report ----
// I feel sad now :(

Time: 16-07-12 18:49
Description: Ticking entity

java.lang.ClassCastException: java.lang.Byte cannot be cast to java.lang.String
	at pokecube.core.moves.animations.EntityMoveUse.getMove(EntityMoveUse.java:62)
	at pokecube.core.moves.animations.EntityMoveUse.func_70071_h_(EntityMoveUse.java:129)
	at net.minecraft.world.World.func_72866_a(World.java:1962)
	at net.minecraft.world.World.func_72870_g(World.java:1932)
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1789)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at pokecube.core.moves.animations.EntityMoveUse.getMove(EntityMoveUse.java:62)
	at pokecube.core.moves.animations.EntityMoveUse.func_70071_h_(EntityMoveUse.java:129)
	at net.minecraft.world.World.func_72866_a(World.java:1962)
	at net.minecraft.world.World.func_72870_g(World.java:1932)

-- Entity being ticked --
Details:
	Entity Type: pokecube.pokecube:moveuse (pokecube.core.moves.animations.EntityMoveUse)
	Entity ID: 669102
	Entity Name: entity.pokecube.pokecube:moveuse.name
	Entity's Exact location: 30,32, 74,94, -149,49
	Entity's Block location: World: (30,74,-150), Chunk: (at 14,4,10 in 1,-10; contains blocks 16,0,-160 to 31,255,-145), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0,00, 0,00, 0,00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1748)

-- Affected level --
Details:
	Level name: MpServer
	All players: 5 total; [EntityPlayerSP['carcanox32'/668576, l='MpServer', x=8,32, y=74,06, z=-144,25], EntityOtherPlayerMP['Thutmose'/664996, l='MpServer', x=7,75, y=74,00, z=-139,80], EntityOtherPlayerMP['pokeman300'/661851, l='MpServer', x=35,92, y=74,21, z=-123,94], EntityOtherPlayerMP['TigerStorm1'/668930, l='MpServer', x=32,03, y=74,06, z=-150,81], EntityOtherPlayerMP['Idk_a_name'/583089, l='MpServer', x=23,62, y=74,00, z=-146,97]]
	Chunk stats: MultiplayerChunkCache: 225, 225
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (16,75,-155), Chunk: (at 0,4,5 in 1,-10; contains blocks 16,0,-160 to 31,255,-145), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 24984721 game time, 4968499 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 26 total; [EntityPlayerSP['carcanox32'/668576, l='MpServer', x=8,32, y=74,06, z=-144,25], EntityPainting['Painting'/21, l='MpServer', x=7,50, y=75,50, z=-150,97], EntityPainting['Painting'/22, l='MpServer', x=4,03, y=76,00, z=-147,50], EntityPainting['Painting'/23, l='MpServer', x=4,03, y=76,50, z=-144,50], EntityPainting['Painting'/24, l='MpServer', x=7,50, y=75,50, z=-138,03], EntityPainting['Painting'/25, l='MpServer', x=4,03, y=76,00, z=-141,50], EntityOtherPlayerMP['Thutmose'/664996, l='MpServer', x=7,75, y=74,00, z=-139,80], EntityOtherPlayerMP['TigerStorm1'/668930, l='MpServer', x=32,03, y=74,06, z=-150,81], EntityOtherPlayerMP['pokeman300'/661851, l='MpServer', x=35,92, y=74,21, z=-123,94], EntityOtherPlayerMP['pokeman300'/661851, l='MpServer', x=35,92, y=74,21, z=-123,94], EntityPainting['Painting'/21, l='MpServer', x=7,50, y=75,50, z=-150,97], EntityPainting['Painting'/22, l='MpServer', x=4,03, y=76,00, z=-147,50], EntityPainting['Painting'/23, l='MpServer', x=4,03, y=76,50, z=-144,50], EntityPainting['Painting'/24, l='MpServer', x=7,50, y=75,50, z=-138,03], EntityPainting['Painting'/25, l='MpServer', x=4,03, y=76,00, z=-141,50], EntityPokemartSeller['Toradoshi'/26, l='MpServer', x=29,15, y=74,00, z=-176,17], EntityPokemartSeller['Aisumi'/27, l='MpServer', x=29,02, y=74,00, z=-174,46], EntityPokemartSeller['MsBluuEyedKitty'/29, l='MpServer', x=39,38, y=74,00, z=-175,20], EntityPokemartSeller['CubicKnight'/30, l='MpServer', x=39,98, y=74,00, z=-175,94], EntityArmorStand['Drop Party'/32, l='MpServer', x=34,50, y=74,50, z=-129,50], EntityArmorStand['Route'/33, l='MpServer', x=53,50, y=74,50, z=-154,50], GenericPokemob656['Froakie'/34, l='MpServer', x=82,46, y=34,08, z=-178,50], EntityMoveUse['entity.pokecube.pokecube:moveuse.name'/669102, l='MpServer', x=30,32, y=74,94, z=-149,49], EntityOtherPlayerMP['Thutmose'/664996, l='MpServer', x=7,75, y=74,00, z=-139,80], EntityOtherPlayerMP['Idk_a_name'/583089, l='MpServer', x=23,62, y=74,00, z=-146,97], GenericPokemob330['Flygon'/667120, l='MpServer', x=-38,02, y=70,00, z=-87,82]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:414)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 340046560 bytes (324 MB) / 788729856 bytes (752 MB) up to 5355339776 bytes (5107 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.0.2010 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.0.2010.jar) 
	UCHIJA	Forge{12.18.0.2010} [Minecraft Forge] (forge-1.10.2-12.18.0.2010.jar) 
	UCHIJA	Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar) 
	UCHIJA	blockarmor{1.0} [Block Armor] (BlockArmor-1.10-1.0.jar) 
	UCHIJA	chiselsandbits{11.5} [Chisels & Bits] (chiselsandbits-11.5.jar) 
	UCHIJA	IronChest{7.0.6.794} [Iron Chest] (ironchest-1.10.2-7.0.6.794.jar) 
	UCHIJA	thutcore{3.2.0} [ThutCore] (thutcore-1.9.4-3.2.0.jar) 
	UCHIJA	NBTEditpqb{1.8.9-1.0} [In-game NBTEdit - Pokecube Edition] (Pokecube Core-4.2.2.jar) 
	UCHIJA	pokecube{4.2.2} [Pokécube Core] (Pokecube Core-4.2.2.jar) 
	UCHIJA	pokecube_ml{0.1.0} [Pokecube Model Loader] (Pokecube Core-4.2.2.jar) 
	UCHIJA	pokecube_mobs{2.2.1} [Pokécube Mobs] (Pokecube Mobs-2.2.1.jar) 
	UCHIJA	pokecube_origin{@VERSION@} [Pokecube Origin] (Pokecube Mobs-2.2.1.jar) 
	UCHIJA	pokecube_adventures{4.1.15} [Pokécube Revival] (Pokecube Revival-4.1.15.jar) 
	UCHIJA	pokecube_compat{1.0} [Pokecube Compat] (Pokecube Revival-4.1.15.jar) 
	UCHIJA	theoneprobe{1.0.13} [The One Probe] (theoneprobe-1.10-1.0.13.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 368.69' Renderer: 'GeForce GTX 965M/PCIe/SSE2'
	Launched Version: 1.10.2-forge1.10.2-12.18.0.2010
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 965M/PCIe/SSE2 GL version 4.5.0 NVIDIA 368.69, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz

**Comment by Thutmose** [comment]
hmm, I honestly have no clue how that could have happened, that crash shouldn't be possible, try re-downloading and re-installing all of the mods?

**Comment by carcanox32** [comment]
i will try can you do a list of all mods of the server pls ?

**Comment by Thutmose** [comment]
you have them all in

**Comment by carcanox32** [comment]
oki

**Comment by Thutmose** [comment]
This crash shouldn't be able to occur anymore, re-open this issue if it does, or post a new one.
