### ISSUE TITLE
Zapdos colision issues

### ISSUE THREAD

**Issue by jochuan** [Thutmose/Pokecube#112]
#### What happens:

i was fighting with a zapdos then he disappeared and i found him inside the ground
#### What you expected to happen:

i don't think that zapdos can learn the move Dig :)
![2016-07-13_19 05 02](https://cloud.githubusercontent.com/assets/11268912/16821649/cb15b6f0-492d-11e6-930b-054be268a836.png)
![2016-07-13_19 05 45](https://cloud.githubusercontent.com/assets/11268912/16821650/cc1b9a7e-492d-11e6-9774-6c4cc88deb46.png)
#### Steps to reproduce:

1.find a zapdos
2.fight with him

---
#### Affected Versions (Do _not_ use "latest"):
- Pokecube Core:3.6.1
- Pokecube Revival (if applicable):3.4.15
- Pokecube Mobs (if applicable):2.2.1
- Minecraft: 1.9.4
- Forge:1967

**Comment by Thutmose** [comment]
I am working on some more collision fixes, it seems the previous ones mainly worked for things that walk on the ground, things that float/fly were a bit buggy.

**Comment by Thutmose** [comment]
This should be fixed as of the version I just released, but I will keep this issue open as there are probably more collision bugs lying around.

**Comment by Thutmose** [comment]
things have changed since this issue, will close this for now, and let new one be opened if it is still needed.
