### ISSUE TITLE
Pokemobs disappears after throwing a pokeball when they are with low health

### ISSUE THREAD

**Issue by jochuan** [Thutmose/Pokecube#113]
#### What happens:
when you throw a pokeball on a pokemon with one HP and you don't catch it he disappears

#### What you expected to happen:

he should stay on the same place 

#### Steps to reproduce:

1.let a pokemon with one hp
2.trow a pokeball

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:3.6.1
- Pokecube Revival (if applicable):3.4.15
- Pokecube Mobs (if applicable):2.2.1
- Minecraft: 1.9.4
- Forge:1976

**Comment by Thutmose** [comment]
I will look into this, I wonder if when it breaks out of pokecube it takes damage somehow...

**Comment by jochuan** [comment]
After trying to catch a beldum i found that it takes damage when it breaks out of the pokeball it was with half of Hp and died after

**Comment by Thutmose** [comment]
I will start looking into this now, I have spent the last few days re-working a bunch of internal stuff related to spawns and trainers, so haven't had time to start testing this.

**Comment by Thutmose** [comment]
This should be fixed for the next version, or at least I have not been able to replicate it  now.

I Think they were taking fall damage after they left the cube.  I made them clear their fall distance on release which should fix that, I tested with throwing pokecubes at 1hp beldums and chanseys for a while, and none of them died.

**Comment by Thutmose** [comment]
should be fixed in recent versions.
