### ISSUE TITLE
Crash when entering a world

### ISSUE THREAD

**Issue by jochuan** [Thutmose/Pokecube#114]
#### What happens:

i created a new world and i was entering in it then the game crashed
https://gist.github.com/jochuan/a44a769204ce790392aca01e7d92b711

#### What you expected to happen:
the game should not crash

#### Steps to reproduce:

1.create a world

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:3.6.3
- Pokecube Revival (if applicable):3.5.1
- Pokecube Mobs (if applicable):2.2.1
- Minecraft: 1.9.4
- Forge:1976

**Comment by Thutmose** [comment]
I should have this fixed for the release I am making tomorrow.

**Comment by Thutmose** [comment]
It should be fixed in the latest ones.
