### ISSUE TITLE
Pokeplayer bug reports

### ISSUE THREAD

**Issue by KingEdward9830** [Thutmose/Pokecube#115]
#### Issue Description:
Some bugs that I noticed straight away when doing SSP tests of Pokeplayer. Note: this was on the K-Pokecube modpack on the Curse launcher, but as Thutmose knows, this pack is very small and the issues posted here are far more likely to rise from Pokecube itself than mod incompatibilities.

#### What happens:
1.Pokemob health does not display on the player HUD, the amount of health the player has in total does change, but no matter what state of damage the player Pokemob is in, the HUD reports health as full.
2.Death is rather severely bugged. The death screen with the respawn/title screen options does appear, and items are dropped, however the Pokeplayer entity is not removed from the world, and clicking Respawn will simply close the death screen and return you to gameplay as though you had not died.(Edit: after further testing, taking damage as a lvl 100 pidgeot, then changing back to human, and walking around for awhile, caused me to, seemingly out of nowhere, die and be unable to respawn.)
3.When playing as a Ditto and transforming into another Pokemob, neither the moves nor the player's appearance change visually, but the other Pokemob's moves are still usable.

#### What you expected to happen:
1.The HUD to report health as its current state rather than as full, as per normal.
2.Death to function similarly to how it does as a normal player.
3.Ditto's model and visible moveset to change with the transformation, as they do when using Ditto normally.

#### Steps to reproduce:

1.For numbers 1, 2, and 3, become a Pokemob, 3 requires Ditto.
2.For numbers 1 and 2, take some damage and/or die, for number 3, enter a battle and use Transform on your opponent.
3.For number 3, look at your model and movelist, and try attacking with different moveslots.

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core: 4.3.3
- Pokecube Revival (if applicable): 4.2.1
- Pokecube Mobs (if applicable): 2.2.1
- Minecraft: 1.10.2
- Forge: 12.18.0.2005

**Comment by Thutmose** [comment]
I we-write pokeplayer, let me know if this still occurs, make new issues for the new pokeplayer.
