### ISSUE TITLE
Splicing device is too hard to craft on 1.9

### ISSUE THREAD

**Issue by jochuan** [Thutmose/Pokecube#117]
looks like in 1.9 enchanted golden apples cant be crafted anymore and can only be found in 2.6% of desert temple chests, 3.1% of dungeon chests, and 1.4% of chest minecarts in abandoned mine shafts this makes it almost impossible to craft the splicing device now so i think that crafting recipe of the splicing device should be changed to use a normal golden apple or maybe a emerald block

**Comment by Thutmose** [comment]
This is as intended, It would have been more expensive before if I could do so.

If anything I would make it harder, the splicing device is a rather over powered block.

These are my current plans for it:
I will try to split it into a fossil machine and a splicing device

The fossil machine will cost similar to the current one, and the splicing device will be made much more expensive, probably including nether stars somewhere.
