### ISSUE TITLE
Beldum getting fall damage

### ISSUE THREAD

**Issue by jochuan** [Thutmose/Pokecube#118]
#### Issue Description:
one attack of beldum is making it get fall damage

#### What happens:
i was trying to capture a beldum so i used my combusken and i selected the 0 attack and i gave one hit on one beldum  after that he and and the combusken were jumping 3 blocks higher and getting fall damage after somes seconds the beldum died and my combusken ended with only half of the hp

#### What you expected to happen:
i don't think that it should kill itself using takedown

#### Steps to reproduce:

1.use your pokemob and select the 0 attack
2.hit one beldum

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:3.6.2
- Pokecube Revival (if applicable):3.5.0
- Pokecube Mobs (if applicable):2.2.1
- Minecraft: 1.9.4
- Forge:1976

**Comment by Thutmose** [comment]
Takedown does recoil damage, which will kill him.

I will look to make sure he isn't taking fall damage as well though.

**Comment by Thutmose** [comment]
should be fixed in recent versions.
