### ISSUE TITLE
Shedinja pokeplayer bug

### ISSUE THREAD

**Issue by jochuan** [Thutmose/Pokecube#119]
#### Issue Description:
if you transform in a shedinja things will get a little creepy

#### What happens:
if you became human again after being a shedinja the player model will be bugged and if you transform in a shedinja again it will look like it died

![2016-07-17_19 51 45](https://cloud.githubusercontent.com/assets/11268912/16903575/e0904df0-4c58-11e6-8d8d-6b9bf648df59.png)
![2016-07-17_19 51 50](https://cloud.githubusercontent.com/assets/11268912/16903578/e7d72854-4c58-11e6-993b-32f27a4ccd88.png)
![2016-07-17_19 52 09](https://cloud.githubusercontent.com/assets/11268912/16903580/ecd05a92-4c58-11e6-94b6-71d31e5ae6a7.png)
![2016-07-17_19 52 14](https://cloud.githubusercontent.com/assets/11268912/16903582/f0e2a694-4c58-11e6-9eaa-39748ad51275.png)
![2016-07-17_19 52 44](https://cloud.githubusercontent.com/assets/11268912/16903584/f8f89eec-4c58-11e6-9062-7149152c7ee9.png)
![2016-07-17_19 53 20](https://cloud.githubusercontent.com/assets/11268912/16903586/fe100a5a-4c58-11e6-8ca2-c9d339813948.png)

#### What you expected to happen:
the player model should be fine

#### Steps to reproduce:

1.transform in a shedinja 
2.become human again

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:3.7.0
- Pokecube Revival (if applicable):3.6.0
- Pokecube Mobs (if applicable):2.2.1
- Minecraft: 1.9.4
- Forge:1976

**Comment by Thutmose** [comment]
if you decide to report any more of the pokeplayer bugs, please edit this issue to add them.  Pokeplayer is very very buggy atm, and I don't want the issue tracker filled with them.

**Comment by XileForce** [comment]
I don't think this bug is strictly related to Shedinja. It seems to happen occasionally regardless of which Pokemon I choose.

**Comment by jochuan** [comment]
This only happened with shedinja for me also great work on the pokeplayer feature apart from the the little bugs it is very fun

**Comment by Thutmose** [comment]
I we-write pokeplayer, let me know if this still occurs, make new issues for the new pokeplayer.
