### ISSUE TITLE
Pokemobs are jumping like fishs

### ISSUE THREAD

**Issue by jochuan** [Thutmose/Pokecube#120]
#### What happens:
if you look around you will see that great part of the pokemons are jumping 2 and sometimes 4 blocks this is more strange on diglett which should not jump

#### What you expected to happen:
the pokemons should not jump so much

#### Steps to reproduce:

1.find pokemons
2.look at them

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:3.7.0
- Pokecube Revival (if applicable):3.6.0
- Pokecube Mobs (if applicable):2.2.1
- Minecraft: 1.9.4
- Forge:1976

**Comment by Thutmose** [comment]
Has this happened recently? I have made some changes to movement and have not noticed it on my end.

Close it if it hasn't please.

**Comment by jochuan** [comment]
i did not tested the last version and i will only be able do that after 3 days

**Comment by jochuan** [comment]
fixed
