### ISSUE TITLE
Only Caterpie!

### ISSUE THREAD

**Issue by doctorkreger** [Thutmose/Pokecube#121]
#### Issue Description:
There is only Caterpie.

#### What happens:
As of some recent time, all of the pokespawns in my world are caterpie.  

#### What you expected to happen:
Variety
____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:4.4.3
- Pokecube Revival (if applicable):4.3.2
- Pokecube Mobs (if applicable):2.2.1
- Minecraft: 1.9.4
- Forge:12.8.0.2010

**Comment by Thutmose** [comment]
I am getting normal variety of spawns, what other mods are you using? also, 4.4.3/4.3.2 are for 1.10, but you listed 1.9.4?

**Comment by doctorkreger** [comment]
The 1.9.4 was my mistake, I meant 1.10.2. 

I am using a variety of other mods, like a ton. 

I actually did find some other mobs today.  It might be just the way my spawn biome works out. I am on a highland, mostly grass with some trees.  I cannot find any flying pokemon anywhere, and the only terrestrials I find are caterpie.

Here is a list of the mods directory:

07/22/2016  02:05 PM    <DIR>          .
07/22/2016  02:05 PM    <DIR>          ..
07/22/2016  01:10 PM         2,103,471 ActuallyAdditions-1.10.2-r54.jar
07/08/2016  09:55 AM           452,005 AgriculturalExpansion[1.9.4][1.10.2]r-1.2.0 (1).jar
07/08/2016  09:11 AM           115,445 AppleCore-mc1.10.2-1.3.5.jar
07/08/2016  10:27 AM             3,395 ArrowFix-1.1 (1).jar
07/08/2016  09:44 AM         1,476,254 BaseMetals_1.9.4-2.3.2.6.jar
07/08/2016  01:14 PM            89,209 Baubles-1.10.2-1.2.2.0.jar
07/08/2016  09:05 AM         1,874,877 bdlib-1.12.0.2-mc1.10.2.jar
07/16/2016  03:20 PM         6,128,672 BiomesOPlenty-1.9.4-4.1.0.2049-universal.jar
07/21/2016  03:23 PM         9,269,631 BloodMagic-1.9.4-2.0.3-53.jar
07/08/2016  09:31 AM        16,035,738 Botania-unofficial.r1.8-312.jar
07/16/2016  03:37 PM           110,491 Bullseye-1.9.4-1.0.2.jar
07/08/2016  09:10 AM            69,343 Chameleon-1.9.4-2.1.5.jar
07/08/2016  02:21 PM           581,586 chiselsandbits-11.5.jar
07/08/2016  09:39 AM           184,936 CommonCapabilities-1.9.4-1.1.0.jar
07/08/2016  09:25 AM           336,812 CookingForBlockheads-mc1.9.4-3.1.26.jar
07/08/2016  09:38 AM           775,098 CraftTweaker-1.10.2-3.0.10.jar
07/21/2016  03:23 PM         2,588,384 CustomDrones-1.2.0-mc1.10.2.jar
07/08/2016  09:39 AM           641,810 CyclopsCore-1.9.4-0.7.1 (1).jar
07/19/2016  03:05 PM           634,925 DoomlikeDungeons-1.8.13-MC1.10.jar
07/19/2016  10:23 PM           447,455 EnderCore-1.10.2-0.4.1.41-beta.jar
07/19/2016  10:23 PM         5,091,168 EnderIO-1.10.2-3.0.1.71_beta.jar
07/08/2016  09:39 AM            42,655 EnergySynergy-1.9.4-1.0.0 (1).jar
07/19/2016  10:29 PM            49,558 ExtraRails-1.10.2-1.1.1.jar
07/08/2016  02:21 PM           130,309 ezstorage-2.0.4.jar
07/08/2016  09:25 AM             4,785 FastLeafDecay-v10.jar
07/17/2016  01:02 PM         4,228,670 forestry_1.10.2-5.1.12.200.jar
07/08/2016  09:49 AM         4,609,922 Foundry-1.10.2-2.0.0.1.jar
07/08/2016  02:22 PM            90,747 fyrestone-0.6.4.1.jar
07/19/2016  02:46 PM         1,712,021 Gemulation-1.10-4.0.0.jar
07/08/2016  01:27 PM         1,447,504 generators-0.9.20.4-mc1.10.2.jar
07/21/2016  03:19 PM           112,017 grapplemod-1.10.2-v7.jar
07/11/2016  12:00 PM           212,095 hempfarmer-1.10.2-2010-1.67.jar
07/08/2016  09:38 AM            50,737 hopperducts-mc1.9.4-1.4.7.jar
07/08/2016  09:05 AM           148,229 ironchest-1.10.2-7.0.6.794.jar
07/08/2016  09:24 AM           321,713 jei_1.10.2-3.7.4.224.jar
07/08/2016  09:31 AM           203,756 JustEnoughResources-1.10.2-0.4.6.41.jar
07/19/2016  03:05 PM           277,421 LittleInsignificantThings-1.10-3.0.2.jar
07/18/2016  02:02 AM           367,864 llibrary-1.4.2-1.10.2.jar
07/17/2016  04:47 PM           153,909 magicalpotionsandbrews-0.1.7.jar
07/08/2016  02:21 PM         3,202,318 Mantle-1.10-0.10.3.jar
07/08/2016  09:37 AM         3,305,670 MCA-1.10.2-5.2.0-universal.jar.disable
07/12/2016  09:07 AM           252,274 mcjtylib-1.10-1.9.8.jar
07/08/2016  09:38 AM           172,901 MCMultiPart-1.2.0-universal.jar
07/16/2016  05:24 PM         1,914,732 Minecraft Flight Simulator-1.10.2-4.0.0.jar
07/08/2016  09:30 AM            34,995 MmmMmmMmmMmm-1.11.jar
07/08/2016  09:56 AM         1,279,267 ModernMetals-0.11.0.jar
07/08/2016  10:20 AM            47,343 MoreAnvils-Forge-6.0.2.11.jar
07/16/2016  05:23 PM           783,679 multistorage-1.10.0-1.2.1.jar
07/08/2016  09:36 AM            74,695 OreDictionaryConverter-1.9.0.jar
07/08/2016  02:21 PM            23,874 OreSpawn_1.9.4-1.0.3.jar
06/27/2016  02:19 PM         2,480,158 Pam's HarvestCraft 1.9.4c.jar
07/16/2016  05:22 PM           506,891 platforms-1.10.0-1.2.0.jar
07/22/2016  08:57 AM         3,058,705 Pokecube Core-4.4.3.jar
07/12/2016  09:10 AM        14,407,057 Pokecube Mobs-2.2.1.jar
07/19/2016  01:18 PM         1,106,020 Pokecube Revival-4.3.2.jar
07/08/2016  09:43 AM         1,204,242 pressure-1.3.1.3-mc1.10.2.jar
07/08/2016  09:31 AM         2,160,453 Psi-r1.0-36.jar
07/16/2016  03:20 PM         1,607,745 PSIonicUpgrades-r1.9.jar
07/08/2016  09:37 AM           154,121 RadixCore-1.10.2-2.1.2-universal.jar
07/08/2016  09:22 AM         2,357,834 RandomThings-MC1.10-3.7.4.jar
07/08/2016  09:38 AM            90,163 redstonepaste-mc1.9.4-1.7.4.jar
07/11/2016  12:01 PM           953,117 Reliquary-1.10.2-1.3.2.423.jar
07/10/2016  11:04 AM    <DIR>          resources
07/12/2016  08:37 AM         2,641,831 rftools-1.10-5.06.jar
07/12/2016  08:35 AM           933,774 rftoolsdim-1.10-4.30beta46.jar
07/08/2016  09:25 AM           593,850 RoguelikeDungeons-1.10.2-1.5.4.jar
07/17/2016  04:46 PM           593,382 roots-1.10.2-0.109.0.jar
07/08/2016  10:03 AM            30,193 rucksacks-1.10.2-1.0.0.jar
07/03/2016  11:58 AM           106,774 Ruins-1.10.2-sources.jar
07/03/2016  11:58 AM           155,109 Ruins-1.10.2.jar
07/08/2016  10:11 AM           228,833 Runes-of-Wizardry-1.9.4-0.7.0.jar
07/08/2016  10:12 AM           225,229 RunesofWizardry-Classics-1.9.4-0.4.0.jar
07/08/2016  03:02 PM           688,155 SaltyMod-1.10-1.8.c_beta-1_.jar
07/16/2016  03:37 PM            31,224 SGExtraParts-1.9.4-1.0.3-4.jar
07/21/2016  03:33 PM           360,134 ShadowMC-1.10.2-3.4.4.jar
07/16/2016  05:25 PM           322,681 shetiphiancore-1.10.0-3.3.0.jar
07/16/2016  03:43 PM            33,871 SilentLib-1.9.4-1.0.11-19.jar
07/16/2016  03:37 PM         2,921,676 SilentsGems-1.10.2-2.0.23-52.jar
07/16/2016  05:25 PM            89,822 SimpleDimensions-MC1.10-1.3.jar
07/08/2016  10:04 AM           152,295 SimplyCaterpillar-Forge-6.0.1.20 (2).jar
07/08/2016  09:05 AM           516,932 StorageDrawers-1.9.4-3.1.11.jar
07/16/2016  03:20 PM           424,187 StorageNetwork-1.9.4-1.12.4.jar
07/08/2016  09:38 AM           604,826 Substratum-1.10.2-1.6.0.1.jar
07/21/2016  03:22 PM           390,409 taiga-1.10.2-1.0.2.jar
07/08/2016  09:04 AM         2,292,902 TConstruct-1.10-2.3.3a.jar
07/19/2016  01:28 PM         6,609,991 terraqueous-1.10.0-1.2.1.jar
07/18/2016  02:02 AM           308,094 thutcore-1.9.4-3.2.2.jar
07/08/2016  09:57 AM            86,415 thuttech-3.0.5.jar
07/16/2016  03:36 PM            26,744 tnt_utilities-mc1.10-1.2.1.jar
07/08/2016  10:21 AM            17,994 torcharrows-1.10.2-1.jar
07/08/2016  10:15 AM           261,745 ViesCraft-0.2.9b-mc1.10.2.jar
07/10/2016  09:39 AM            66,980 WaterStrainer-1.9.4-1.0.2.jar
07/08/2016  09:40 AM           572,773 weaponcaseloot-1.10.2-4.0.0.jar
07/08/2016  02:21 PM            36,326 [1.9.4]Mo' Villages-1.5.2.jar

**Comment by Thutmose** [comment]
Hmm, see what happens on a different world? then maybe try killing all the wild pokemobs and seeing if not-caterpie spawn? you can kill wild ones with /pokecube kill

If /pokecube kill still results in caterpie, and a different world does not, please send your world's seed so I can test it on my end?

**Comment by doctorkreger** [comment]
Excellent, I will try out that command.  I had been hesitant to use /kill as it is unclear how one would utilize it to target the pokecube mobs. Ill be back to you shortly.

**Comment by doctorkreger** [comment]
Seems better. Still haven't run across flying pokemobs. Are there any special requirements for the to spawn?

**Comment by Thutmose** [comment]
they should be able to spawn in the same places as the ones on the ground

**Comment by Thutmose** [comment]
You can do /pokecube count and it will tell you all pokemobs currently in the world, maybe the flying types are just spawning rarely for you? It seems in my test world only 2 out of 70 were birds for my initial test.

![image](https://cloud.githubusercontent.com/assets/2363472/17071462/adfe8e1c-502f-11e6-8f12-1050d0a3fa02.png)

**Comment by doctorkreger** [comment]
It took a couple of tries, but things seem to have evened out. I suppose the random nature of the spawns just means they weren't getting a chance.
