### ISSUE TITLE
Pokemons not evolving when you make a trade with a trainer

### ISSUE THREAD

**Issue by jochuan** [Thutmose/Pokecube#122]
#### Issue Description:
Pokemons that only evolve by trade didn't evolve when you trade them with a trainer of the mod

#### What happens:

i tested using a onix holding metal coat i traded it with a trainer for a clefairy and when he used the onix it did not evolved in a steelix

#### What you expected to happen:
the pokemons should evolve because they were traded and it would be a easier way of obtaining pokemons that only evolve by trade on single player without having to edit the pokecube files

#### Steps to reproduce:

1.trade a pokemon with a trainer

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:3.7.3
- Pokecube Revival (if applicable):3.6.2
- Pokecube Mobs (if applicable):2.2.1
- Minecraft: 1.9.4
- Forge:1976

**Comment by Thutmose** [comment]
This is currently intentional, as iirc the trainers in the games you can trade with don't usually result in evolution either.
