### ISSUE TITLE
 Female Wobbuffet dont have lipsticks

### ISSUE THREAD

**Issue by jochuan** [Thutmose/Pokecube#123]
The female wobbuffet should have lipsticks so i made them with lipsticks

![spr_6x_202_f](https://cloud.githubusercontent.com/assets/11268912/17070717/f62fd44e-5033-11e6-8140-5c9c1fac6666.png)
![wobbuffetfemale](https://cloud.githubusercontent.com/assets/11268912/17070729/05a73c0a-5034-11e6-8265-133e05597c56.png)
![wobbuffetfemales](https://cloud.githubusercontent.com/assets/11268912/17070728/05a3f180-5034-11e6-8299-93ac01332eb1.png)

**Comment by Thutmose** [comment]
Thanks, I will get that added for next version of mobs.

**Comment by Thutmose** [comment]
You should probably report issues like this one to Pokecube Models instead though.

**Comment by Thutmose** [comment]
I have updated the textures in Pokecube Mobs with this on my end, It will be in the next release of Pokecube Mobs, I will probably be releasing that sometime soonish, as It already has 30ish new pokemon in it.

**Comment by jochuan** [comment]
i think that i found more gender differences i will report them in the pokecube models github

**Comment by Thutmose** [comment]
ok, I will close this issue and use that other one.
