### ISSUE TITLE
Extreme lag

### ISSUE THREAD

**Issue by jochuan** [Thutmose/Pokecube#126]
#### Issue Description:
i am getting a lot of lag in the latest version of pokecube

#### What happens:
My fps dropped to 2 in the latest version when i normally play with 15 fps

#### What you expected to happen

it shouldn't be so lag

#### Steps to reproduce:

1.use only one gb of ram to play minecraft 

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:3.7.4
- Pokecube Revival (if applicable):3.6.3
- Pokecube Mobs (if applicable):2.2.2
- Minecraft: 1.9.4
- Forge:1990

**Comment by Thutmose** [comment]
hmm, I do all my testing with 1G of ram as well, I will look into it some more to see if something changed that would do that.

**Comment by jochuan** [comment]
Maybe it is related to forge as well since i updated pokecube with forge together i will test too when i have time

**Comment by jochuan** [comment]
i updated pokecube to the latest version again and started a new world while the world was generating a got 7 fps but after that my fps dropped again to 0-3 fps and i already tested with the old forge version but i got the same results

**Comment by Thutmose** [comment]
hmm, what happens if you set it to peaceful then do /pokecube kill ? if that fixes it, then the fps is definitely pokemob related.  Also, what is the result from typing /forge tps

**Comment by jochuan** [comment]
i used the pokecube kill all command and my fps increased to 10 but it fluctuate from 10 and 0 when i walk and here is the /forge tps
![2016-07-30_11 24 52](https://cloud.githubusercontent.com/assets/11268912/17271072/9af10920-5648-11e6-8d33-784be5baf890.png)

**Comment by jochuan** [comment]
fixed that on my end i am so dumb sorry for any inconvenience that i may have caused
