### ISSUE TITLE
[Suggestion] Cooldown between catch attempts

### ISSUE THREAD

**Issue by XileForce** [Thutmose/Pokecube#127]
What im suggesting is a configurable cooldown between catch attempts on pokemobs after a failed catch. Currently if you fail a catch you can immediately retry. The problem with this is so long as you have enough pokecubes you can catch almost anything risk free because as soon as it fails you just hit it with another one. This means the pokemob doesn't even get a chance to attack. In the games, if you fail a catch attempt the enemy gets a free turn to attack. I think implementing some sort of cooldown system would make catching stronger pokemon much more challenging as you couldnt simply spam pokeballs until it succeeded. Ive literally watched players stand there and spam pokecubes at a high level pokemob for several minutes without taking any dmg before they finally catch it. It could also be implemented as a cooldown on throwing the pokecube, which may reduce confusion. Or a message could be added when trying to hit a pokemob with a pokecube before the cooldown is up to inform players of why their pokecube bounced off.

**Comment by jochuan** [comment]
this is a good idea

**Comment by Thutmose** [comment]
This will be in next release, there will be a new config option under misc in pokecube.cfg called captureDelayTicks, it will result in the "The Pokémob refuses to enter the cube!" message and the pokecube bouncing off the pokemob if cubes are used on it too quickly

**Comment by Thutmose** [comment]
Uploaded the release that adds this config, 3.76/4.4.6 should have it.
