### ISSUE TITLE
Abra isn't teleporting to flee away

### ISSUE THREAD

**Issue by jochuan** [Thutmose/Pokecube#130]
#### What happens:

Abra use teleport but it stays at the same place
#### What you expected to happen:

he should teleport to another place
#### Steps to reproduce:

1.fight a abra or maybe another pokemon that knows teleport

---
#### Affected Versions (Do _not_ use "latest"):
- Pokecube Core:3.7.6
- Pokecube Revival (if applicable):3.6.5
- Pokecube Mobs (if applicable):2.2.2
- Minecraft: 1.9.4
- Forge:1990

**Comment by Thutmose** [comment]
I will look into this, I think it got broken when I re-worked the internal way moves are used to clean up some old code.

**Comment by Thutmose** [comment]
Fixed in latest releases.
