### ISSUE TITLE
Wild pokemons are attacking more than one turn

### ISSUE THREAD

**Issue by jochuan** [Thutmose/Pokecube#132]
#### What happens:

poke,ons are attacking more than one turn this happens with one from trainers too
#### What you expected to happen:

they shouldnt attack on two turns
#### Steps to reproduce:

1.attack a pokemon
2.
3.
...

---
#### Affected Versions (Do _not_ use "latest"):
- Pokecube Core:3.7.6
- Pokecube Revival (if applicable):3.6.5
- Pokecube Mobs (if applicable):2.2.2
- Minecraft: 1.9.4
- Forge:1990

**Comment by Thutmose** [comment]
I don't notice this, maybe you are using an attack with a rather long cooldown, and the wild ones are using much shorter cooldown attacks, so are hitting before yours is off?

**Comment by jochuan** [comment]
i was using dual chop and dragon rage i have a picture of what happened but i cant show you it now

**Comment by jochuan** [comment]
![2016-08-07_21 32 44](https://cloud.githubusercontent.com/assets/11268912/17635022/b3f24156-60ab-11e6-967e-c9ddd52f7114.png)
![2016-08-07_21 32 50](https://cloud.githubusercontent.com/assets/11268912/17635026/b9837a9a-60ab-11e6-8f02-ab6ee3669d69.png)
![2016-08-07_21 32 55](https://cloud.githubusercontent.com/assets/11268912/17635031/bc5b67dc-60ab-11e6-8d6b-89e44ac57b31.png)
![2016-08-07_21 33 21](https://cloud.githubusercontent.com/assets/11268912/17635039/bfd25998-60ab-11e6-8d16-a0701a1df93f.png)
here are the images looks like my pokemon isn't attacking so this may be related with the other bug

**Comment by jochuan** [comment]
https://github.com/Thutmose/Pokecube/issues/49

**Comment by Thutmose** [comment]
Ahh, I see, I will look and see if I can find a not-attacking bug.

Try something, try setting contactAttackDistance to say 8 or 16, and see if it still occurs, that will make contact moves think they are ranged moves instead, it could be an issue with the mob not being able to get to the target in time?

**Comment by jochuan** [comment]
i made that and it worked but rarely i still get the bug
![2016-08-28_17 03 51](https://cloud.githubusercontent.com/assets/11268912/18037120/067dec28-6d53-11e6-999b-8864e5bc3cbd.png)

**Comment by Thutmose** [comment]
I think that particular case is due to your magikarp being too slow to get to the geodude, so the geodude is able to attack many times before karp gets to it to tackle it

**Comment by jochuan** [comment]
i think that the battle should be made to work more like on turns like the pokemons game where the speed stats of the pokemon would make it attack first and the other pokemon would only attack if the one with the faster speed attacked first but when a pokemon is used against non-pokemobs it would use the currently system

**Comment by Thutmose** [comment]
at some point I might make an addon that does something similar to that, but for pokecube itself, I don't want to implement any form of turn based combat

**Comment by jochuan** [comment]
it dont need to be a battle based on turns like pixelmon but the pokemon would only attack if the one with faster speed attacked

**Comment by Thutmose** [comment]
things have changed since this, and pokecube-server-utilities has a feature to make the turns thing happen.
