### ISSUE TITLE
Master ball evaluate pokedex idea

### ISSUE THREAD

**Issue by jochuan** [Thutmose/Pokecube#135]
i have a idea to get one master ball for free, on the pokemons game you could evaluate your pokedex in the pc,there would be a button on the pc to evaluate the pokedex when you press this button a gui would open showing one empty slot and other area with 3x3 slots so after you caught 40 pokemons or something like that,you would need to place your pokedex in the first slot and the master ball would appear in the area of 3x3 slots the same could be done with the shiny charm when you caught all the pokemons that spawn but you could only obtain the master ball and the shiny charm from there once, there could be other prizes but this is on your side to decide
the Gui should be like that 
![sem titulo](https://cloud.githubusercontent.com/assets/11268912/17834057/d3ba01de-6706-11e6-9b20-cbd9a22de3b0.png)

**Comment by Thutmose** [comment]
I will get the fix for the trainer bug uploaded shortly, then I will see if I can get to work on something like this.

**Comment by jochuan** [comment]
i think that some items like Mega stones and held items like King's Rock could be prizes from there too because i think that buying them is too easy, Mega stones of mewtwo and the primal orbs would be only received by evaluating the pokedex and i think that you should add mega stones  and vitamins to vanilla chests since the only thing that i find from them is exp shares and Tms

**Comment by jochuan** [comment]
also i think that evaluating the pokedex could be a way of obtaining a togepi egg

**Comment by Thutmose** [comment]
I have gone with a simpler version of this where you click the blue light on the pokedex and it gives you things if you meet the requirements.

So far I added these rewards:
exp share - catch 5 unique pokemobs (easy for 1 to train things like magikarp with)
Cut TM - catch 3% of pokemobs that spawn (cut is currently only found in jungle temples, so a bit too rare, used to be scyther had it too)
Flash TM - catch 6% of pokemobs that spawn.
Rock Smash TM - catch 9% of pokemobs that spawn.
Mastercube - catch 40% of pokemobs that spawn.
Shiny charm - catch 100% of pokemobs that spawn (same requirement as mew)

All of these requirements are in the pokecube.cfg in the rewards section, they are also only given once to each player.

**Comment by jochuan** [comment]
i this that one egg from togepi should be added too since on the games you could obtain it from a egg gived by a npc you would need to catch 25% of the pokemons that spawn

**Comment by NelkGames** [comment]
as would capture 5 Pokémon only ones? would be legendary? initials? a specific evolution?

and the reward system works in worlds ever made?

**Comment by Thutmose** [comment]
the capture 5 should apply to any 5, it should work in already made worlds.

**Comment by Thutmose** [comment]
It seems there is a bug making all rewards need the shiny charm requirement, that is fixed for next version.

**Comment by jochuan** [comment]
oh so that is why i have 3 boxes filled and it says that i need to catch more pokemon

**Comment by Thutmose** [comment]
Ya, here is a pre-release for 1.9.4 which should have those fixed, I will be uploading the release for this after I do some more testing.

[mods.zip](https://github.com/Thutmose/Pokecube/files/470862/mods.zip)

**Comment by NelkGames** [comment]
this update with secret bases is amazing !! reminds me of the mod dimensional door. But it was not clear to me how these dimensions, one reason is I do not understand much English kk, but how do you think? you create the block, or think the passage is a Pokemon with a special attack that creates the block?

sorry if was confused the question. google translate xD

**Comment by NelkGames** [comment]
it seems that this update mega developments are not working.

and it may seem strange but I can ask you something ... if you authorize that my youtube channel was "official" or recommended to display updates and the development of mod pokecube for the Brazilian community, my channel is not very big but was one of the few that started with the mod in version 1.2.5 .

**Comment by Thutmose** [comment]
Mega evolution should be fixed in the one I uploaded after, This one should fix it: https://minecraft.curseforge.com/projects/pokecube-core/files/2330039

How should I go about mentioning it as a recommended place to display updates? The problem I have is that if I put the post in english, then it links to channel in portuguese, it might make people confused.

I will try to put a section for videos, and have a section for portuguese and then put your channel there somewhere as information for the 1.9.4 version

**Comment by NelkGames** [comment]
when I spoke in "recommended", would help in video on tricks, basic and advanced information about the mod. I wanted to also help the English part, but I can not speak any English, could try to put subtitles youtube, but I would be worried because I would use google translate to translate my video.

**Comment by NelkGames** [comment]
in fact, forget that part of recommended, it was kind of a bad idea. Just make video showing the updates is already more than perfect, I got carried away a bit in this video story. :v:

**Comment by jochuan** [comment]
Since this system already has been made and there aren't any ideas that will be implemented on him i will close this
