### ISSUE TITLE
Crash with levels mod

### ISSUE THREAD

**Issue by jochuan** [Thutmose/Pokecube#136]
#### Issue Description:

i was walking then the game crashed
#### What happens:

https://gist.github.com/jochuan/7b8acdf857d5917b0e7552f06b63f6d4
#### What you expected to happen:

the game should not crash
#### Steps to reproduce:

1.install levels mod 
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2514890-r4-1-3-levels-weapon-bow-armor-leveling-abilities?page=13
2.walk and fight some monsters
3.
...

---
#### Affected Versions (Do _not_ use "latest"):
- Pokecube Core:3.7.8
- Pokecube Revival (if applicable):3.6.7
- Pokecube Mobs (if applicable):2.2.2
- Minecraft: 1.9.4
- Forge:2051

**Comment by Thutmose** [comment]
~~I will look into this, it is a crash caused by levels mod itself, but I might be able to see why and fix it on my end.~~

I Think this is a bug with levels mod, not related to pokecube, post the issue to them, if they say they can't fix it, then re-open this issue and I will look into it some more.

**Comment by jochuan** [comment]
the author of the levels mod said this:
"Nothing I can do - Pokecube is throwing the error due to the way Levels handles its systems. I would need them to work with me to fix something like this."

**Comment by Thutmose** [comment]
Ok, I reopened this issue, I will see if I can find out what I need to change to fix it.

**Comment by Thutmose** [comment]
closing this issue since I have not heard back from the levels mod people since I posted on their thread last year...
