### ISSUE TITLE
Crash with JustEnoughResources

### ISSUE THREAD

**Issue by mrapplexz** [Thutmose/Pokecube#137]
#### Issue Description:

Game crashes with JustEnoughResources installed. Crash-report: http://pastebin.com/8mP5G5r9. Log: http://pastebin.com/0g4yPyYM.
#### Steps to reproduce:
1. Install Pokecube Core, Pokecube Mobs, Pokecube Revival, Thutcore, JEI, JustEnoughResources.
2. Enter the game.
   ---
   #### Affected Versions (Do _not_ use "latest"):
- Pokecube Core: 4.4.9
- Pokecube Revival (if applicable): 4.3.8
- Pokecube Mobs (if applicable): 2.2.2
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.1.2071

**Comment by Thutmose** [comment]
Uploaded the fix for this in Pokecube Revival 4.3.9, should be on curse shortly.
