### ISSUE TITLE
Another crash with JustEnoughResources

### ISSUE THREAD

**Issue by mrapplexz** [Thutmose/Pokecube#138]
#### Issue Description:

Game crashes with JER installed. Crash-report: http://pastebin.com/8fzNLmeF. Log: http://pastebin.com/LPXma9ss

---
#### Affected Versions (Do _not_ use "latest"):
- Pokecube Core: 4.4.9
- Pokecube Revival (if applicable): 4.3.9
- Pokecube Mobs (if applicable): 2.2.2
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.1.2071

**Comment by Thutmose** [comment]
for now, don't use the alpha build of JER, use the release or beta build, version 1.10.2-0.4.8.48 is the one I am compatible with.

**Comment by Thutmose** [comment]
This issue should be fixed now, JER added back in the needed method for its api.
