### ISSUE TITLE
[1.10.2] Crash on loading world

### ISSUE THREAD

**Issue by Messorix** [Thutmose/Pokecube#139]
#### What happens:

java.lang.ArithmeticException: / by zero
    at pokecube.core.client.gui.GuiChooseFirstPokemob.func_73863_a(GuiChooseFirstPokemob.java:176)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
#### What you expected to happen:

The world to load
#### Steps to reproduce:
1. Start up MC
2. Create new world

---
#### Affected Versions (Do _not_ use "latest"):
- Pokecube Core: 4.5.2
- Pokecube REvival: 4.4.2
- ThutCore: 1.9.4-3.2.3
- Minecraft: 1.10.2
- Forge: 12.18.1.2076

**Comment by Thutmose** [comment]
Do you also have pokecube mobs in?

**Comment by Messorix** [comment]
Double checked and I do not have that in my pack (selfmade)

**Comment by Thutmose** [comment]
pokecube mobs adds in the pokemobs, so it crashed when it couldn't find a starter

**Comment by Messorix** [comment]
So you are saying it is necessary to have it?

**Comment by Thutmose** [comment]
yes, it is seperate because it is most of the file size, so I don't have to keep uploading the same 12MB or so every time I update core or revival

**Comment by Thutmose** [comment]
well, you could use a resource pack that adds the mobs instead

**Comment by Messorix** [comment]
I'm downloading the mods through the curse launcher and it seems some other mods appointed dependencies... Maybe that you could set those as well so this kind of thing can be prevented (there is no place in thhe launcher that says mobs is a mandatory thing)

**Comment by Thutmose** [comment]
the reason it isn't mandatory is incase someone wants to add in their own mobs instead, some people only want the first generation of pokemon, so they need to use their own version of mobs, or a resource pack, instead of using the pokecube mobs on the curse launcher

**Comment by Messorix** [comment]
Ah ok... Makes sense... A warning if such a thing is missing would be nice though (just saying :P)

**Comment by Thutmose** [comment]
I do have this in the description for Pokecube Core:

"[Pokécube Mobs](https://mods.curse.com/mc-mods/minecraft/239105-pokecube-mobs) - Adds in the rest of the pokemobs, Core only includes Zubat."

**Comment by Thutmose** [comment]
I will list Revival as requiring mobs (but only on curse, will work without it), anyone who wants just Gen 1 can manually change it themselves.

**Comment by Messorix** [comment]
I'm dumb... Click on the mod to see the description... duh XD
I installed it from the "main menu"

**Comment by Thutmose** [comment]
no problem, I have done your suggestion and made it so Pokecube Revival thinks it needs Pokecube Mobs, so it should auto-install that when done via curse.

**Comment by Messorix** [comment]
The last thing I'd like to say would be: great job on this awesome mod (and the massively quick responses)

**Comment by Thutmose** [comment]
thanks
