### ISSUE TITLE
Breeding Mechanic

### ISSUE THREAD

**Issue by Disturbeddragon1** [Thutmose/Pokecube#141]
#### Issue Description:

Tame (Player owned) Pokemobs don't seem to lay eggs after the hearts appear above their heads, but Wild Pokemobs are spawning eggs in the wild after the hearts appear above them. 
#### What happens:

Not sure if this is a bug or just something not fully implemented yet, but when trying to breed tame (player owned) Pokemobs with their compatible tame Pokemob (for instance, a female Mareep with a male Mareep) they will show the hearts like standard Minecraft mobs will when in the process of breeding babies and never actually produce any eggs. Both me and my husband have tried the following:
1. Letting them hold different berries in their own inventory in an enclosed area away from any Pokecube trees/bushes, as well as letting them be near those.
2.  Allowing them to roam freely in an enclosed area with and without dirt/grass to walk on in case that had any issue.
3. Keeping them restrained to a 2x2 area that was fenced in. 

This only seems to not really work though with the Tame Pokemobs, as I said above that the Wild Pokemobs are actually spawning eggs in the wild.
#### What you expected to happen:

After the hearts appear to signify that the breeding process was initialized, an egg should appear in the immediate area around the breeding Pokemobs area shortly thereafter unless they have to like each other first, and then I would think there should be a way to check how much they actually like each other and notify you when the egg spawns.

---
#### Affected Versions (Do _not_ use "latest"):
- Pokecube Core: 4.6.1
- Pokecube Revival (if applicable): 4.5.0
- Pokecube Mobs (if applicable): 2.2.3
- Minecraft: 1.10.2
- Forge: 12.18.1.2079

**Comment by Thutmose** [comment]
Try placing a repel block, then setting radius of repel huge (right click it with rowap berry to do this), then kill all wild pokemobs nearby, then try breeding again?

I could be that where you are breeding the tame ones have too many other pokemobs nearby, which cancels the egg laying (but not the breeding itself, hence the hearts, etc)

the way it is setup, it cancel trying to mate if more than 30 other pokemobs within 25 blocks of where the breeding is being done, then cancels laying eggs if more than 5-10 within 8 blocks of the ones trying to breed, I will remove that latter canceling for tame mobs for the next update, which should help with breeding.

**Comment by Disturbeddragon1** [comment]
We tried what you said and it seems to work, thanks for the information. As long as there weren't too many pokemobs around it worked as it was supposed to. 

I don't know if removing that limit on tame pokemobs will be a good idea unless you set up a similar measurement on tame pokemobs in an area to prevent them from over populating if left alone. Either way thanks again for clearing that up since there really wasn't anywhere that stated such about the breeding mechanics that we could find. The mod has really made Minecraft more interesting and gives us a challenge now to try and find Rowap berries so we can make a repel. lol n_n

**Comment by Thutmose** [comment]
Rowaps are dropped by mobs in taigas iirc, and jobacca in extreme hills.

I will move the check for density over to egg hatching, make them only able to hatch if less than 2x the number around that mob spawning limits them to, that will prevent over population, but still allow them to hatch in areas with wild mobs around (unless you wait long enough for the wild ones to breed and double in numbers)

**Comment by Thutmose** [comment]
This should have been fixed as of Pokecube Core 4.6.2
