### ISSUE TITLE
venepede cry is wrong

### ISSUE THREAD

**Issue by moonplayer333** [Thutmose/Pokecube#144]
#### Issue Description:

Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here.
#### Steps to reproduce:

1.
2.
3.
...

---
#### Affected Versions (Do _not_ use "latest"):
- Pokecube Core:
- Pokecube Revival (if applicable):
- Pokecube Mobs (if applicable):
- Minecraft: 1.8.9
- Forge:

**Comment by Thutmose** [comment]
fixed for next release of mobs and sounds.
