### ISSUE TITLE
A question, and a feature request.

### ISSUE THREAD

**Issue by KingEdward9830** [Thutmose/Pokecube#146]
First of all, is it possible to add new form-changes/megas for existing pokes using resource packs? I mainly ask this for Greninja's sake, seeing as how we still don't know if his new form is coming to the games. (And no, Passimian is NOT proof of the batch of leaks that mentioned our froggy friend, but rather of a different batch that got jumbled up with the other batch on some-or-other website. The Internet is very helpful, but it can be so misleading at times, especially with lazy Youtubers who don't bother to do their research before posting a video. _Yes, TyranitarTube, I am looking at you._) Back to the topic at hand, I would love it if some sort of "synchro" mechanic was added to this mod, but left open-ended so that people could add their own synchro-forms using resource packs or other means. Since Ash's Greninja is supposed to look like Ash in its new form, I think the best way to implement it would be as a customizable feature, rather then a static, unchanging one like mega evolution. That way, people could design awesome new synchro forms for their favorite pokes and use them in game.

**Comment by Thutmose** [comment]
yes, you can add in new forms from resources, you can add in whatever you want for resources, you can use the normal mega system for your fancy new mega evolution thing.
