### ISSUE TITLE
Mega Evolution Bug

### ISSUE THREAD

**Issue by Disturbeddragon1** [Thutmose/Pokecube#147]
#### Issue Description:

Mega evolving a pokemob doesn't work and spawns the error that one must be wearing a mega item to initiate Mega Evolution.
#### What happens:

When trying to Mega Evolve a pokemob capable of doing so, the message "You need to be wearing a mega item to initiate Mega Evolution" keeps showing up in the chat area and in the game output area on the launcher. I have tried giving my pokemob the corresponding mega stone to hold and holding the mega item (both the ring and then the belt at separate times) in my hand, then pressing "m" (my mega evolution key). Each time gives the same message stated above. I have also tried putting the items in the new Baubles-like area for Pokecube equipment provided through this mod, and still to no avail has it worked.

So I was wondering if this is a bug within the mod or if it was being reworked?

---
#### Affected Versions (Do _not_ use "latest"):
- Pokecube Core: 4.13.0
- Pokecube Revival (if applicable): 4.9.6
- Pokecube Mobs (if applicable): 2.3.1
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.1.2095

**Comment by Thutmose** [comment]
That seems like I probably didn't get them to properly search the new worn location.  I will try to get it fixed shortly.

**Comment by Thutmose** [comment]
This should be fixed in current version.
