### ISSUE TITLE
Mega Evolving Pokemobs cause them to increase in size

### ISSUE THREAD

**Issue by Disturbeddragon1** [Thutmose/Pokecube#148]
#### Issue Description:

Mega evolving a pokemob and then telling them to return without reverting back to non-mega evolved mob first causes them to increase in size when sending them out again and repeating the process.
#### What you expected to happen:

Pokemob to stay the same size instead of increasing in size each time it is mega-evolved then returned to its pokecube.
#### Steps to reproduce:
1. Send pokemob out and mega evolve
2. Don't revert pokemob to non-mega
3. Send pokemob out and mega evolve again
   ... Repeat steps 1-3 over and over
   ---
   #### Affected Versions (Do _not_ use "latest"):
- Pokecube Core: 4.13.2.1
- Pokecube Revival (if applicable): 4.9.8.1
- Pokecube Mobs (if applicable): 2.3.1
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.1.2095

![2016-10-09_01 51 27](https://cloud.githubusercontent.com/assets/5956996/19218300/0c5087be-8dc4-11e6-8882-cd86d9a6a801.png)

**Comment by Thutmose** [comment]
does this happen with all mega evolved pokemobs? Also do /pcedit at it, let me know if the value it says under "scale " (under pokemob_tag -> visuals_tag), and let me know if that one is also changing number?

**Comment by Disturbeddragon1** [comment]
Sorry for the delay in response, but yeah seems like it is with all mega evolved pokemobs going by the values under "scale" and seeing them visually grow bigger. The values keep increasing every time they are returned to their pokecube and haven't been reverted back to non-mega forms first.

**Comment by Thutmose** [comment]
Hmm, I can't seem to get this to happen for me, I have tested with houndoom and gardevoir so far, I wonder of some of the internal changes I made recently accidentally fixed it.  

When I release next update, check to see if it still occurs for you.

**Comment by Disturbeddragon1** [comment]
Okay will do.

**Comment by Disturbeddragon1** [comment]
Okay so I downloaded and tried it out in a creative test world again, and they still are increasing in size when repeating the steps of mega evolving them and returning them to their pokecube then sending out again and mega evolved once more.

**Comment by Disturbeddragon1** [comment]
Well I got it to work correctly after some more testing, but I actually had to remove the mod completely and reload the save world without any part of the mod including configs to read from then re-add the Pokecube and Thutcore mods back into my mods folder and basically let it recreate it's config files.

**Comment by Thutmose** [comment]
let me know if you can find out how to make this occur again, I will close the issue for now, but you can re-open it if it happens again.
