### ISSUE TITLE
Pokecube Rival 4.9.6 pokemon are not gaining experience

### ISSUE THREAD

**Issue by DeSahd** [Thutmose/Pokecube#149]
#### Issue Description:

Not sure if this is a mod or modpack issue. I updated my server to version 1.1.3 of the pokemon adventure modpack. It updated pokecube rival to 4.9.6 and now none of our pokemobs are gaining experience.
#### What happens:

After any battles the player's pokemobs do not gain any experience. I recall the mob and mouse over the pokecube and the experience value has not changed. Just in case it was a display issue I killed plenty of pokemon to level up a level 4 mob and still nothing happened, was still level 4.
#### What you expected to happen:

Mousing over the cube in inventory should show the mob's experience like it did in the previous version.
#### Steps to reproduce:
1. Get a pokemob
2. Use it to fight and defeat any other pokemob that will give exp
   3.
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- Pokecube Core: 4.12.11
- Pokecube Revival (if applicable): 4.9.6
- Pokecube Mobs (if applicable): 2.3.1
- Minecraft: 1.10.2
- Forge: 12.18.1.2095

**Comment by Thutmose** [comment]
This was fixed in Pokecube Core 4.13.0
