### ISSUE TITLE
nuzleaf cant take leaf stones

### ISSUE THREAD

**Issue by moonplayer333** [Thutmose/Pokecube#152]
#### Issue Description:

Hey thutmose so i was giving my shiny nuzleaf a leaf stone then it turned inviceble and i could't press r so i did /pokerecall all and it came back to my inventory then i send it out.

**Comment by Thutmose** [comment]
this does not happen to me at all, if you can find a way to reliably replicate it, please let me know, I will close this issue for now, I can re-open it if you find a reliable way to replicate.
