### ISSUE TITLE
Misc. First Impression Bugs/Minor Issues

### ISSUE THREAD

**Issue by Furgl** [Thutmose/Pokecube#154]
1) Pokecube Extras' key binds aren't named properly in the lang file (first one has extra space in front, other two aren't named at all):
![image](https://cloud.githubusercontent.com/assets/16003461/19401342/6ecea8a2-9220-11e6-9d1b-4e810b507d56.png)

2) The wearables "Close" button in the inventory is lined up, and is the same color as, the inventory interface, so it looks like "Cose":
![image](https://cloud.githubusercontent.com/assets/16003461/19401714/77c9ca66-9222-11e6-847b-f4f84b762129.png)

3) The Belt doesn't move with player while sneaking:
![image](https://cloud.githubusercontent.com/assets/16003461/19402161/1d253e1c-9225-11e6-83b7-65063f87c155.png)

4) Badge achievements aren't named in the lang file:
![image](https://cloud.githubusercontent.com/assets/16003461/19402881/5fedc346-9229-11e6-9209-3f11e25905e4.png)

5) Status effects show up through most interfaces:
![image](https://cloud.githubusercontent.com/assets/16003461/19403485/4e03b3f8-922d-11e6-885d-0d360990e1c0.png)

6) Mega Slowbro, Mega Altaria, and Mega Garchomp (possibly more mega pokemon) are not named properly in the lang file:
![image](https://cloud.githubusercontent.com/assets/16003461/19406353/e62c0736-9249-11e6-826c-ce40b01606b5.png)
![image](https://cloud.githubusercontent.com/assets/16003461/19406772/c753e97e-9252-11e6-87cd-283719e3f203.png)
![image](https://cloud.githubusercontent.com/assets/16003461/19406780/48ef7318-9253-11e6-97b4-d0dba8bd338e.png)

7) Trainers will claim that you defeated them when you run from them sometimes:
![image](https://cloud.githubusercontent.com/assets/16003461/19406364/0bec38ba-924a-11e6-942a-640f3834349a.png)

---

Tested on K-Adventure Server:
- Pokecube Core: 4.13.6
- Pokecube Revival (if applicable): 4.9.12
- Pokecube Mobs (if applicable): 2.3.1
- Minecraft: 1.10.2
- Forge: 12.18.2.2105

**Comment by Thutmose** [comment]
All of the ones related to pokecube alternative (that is the 6 slot thing + belt) should probably be on the Thut github issue tracker instead, but I will deal with them here.

I will see about fixing the langs, I didn't get them all in yet

**Comment by Thutmose** [comment]
Latest update should have addressed all of these.
