### ISSUE TITLE
Pokemon Dont Respect Height for Combat distance

### ISSUE THREAD

**Issue by Karagra** [Thutmose/Pokecube#155]
#### Issue Description:

Waited a while for a pokemon to lower its height while flying.
#### What happens:

Pokemon Dont Respect Height for Combat distance
#### What you expected to happen:

Faster Combat Time.

**Comment by Thutmose** [comment]
I think this was fixed in latest version, let me know if it wasn't.

**Comment by P3rf3ctXZer0** [comment]
I think its fixed yes.

**Comment by Thutmose** [comment]
closing this issue since it is fixed, reopen or make a new one if it reoccurs.
