### ISSUE TITLE
Pokecenter music plays forever if destroyed with creative

### ISSUE THREAD

**Issue by nrllewellyn** [Thutmose/Pokecube#157]
#### Issue Description:

See title
#### What happens:

The Pokecenter's music starts playing as soon as it's broken and it plays forever.
#### What you expected to happen:

Pokecenter breaks, no music plays
#### Steps to reproduce:
1. Use creative mode
2. Place Pokecenter
3. Break

---
#### Affected Versions (Do _not_ use "latest"):
- Pokecube Core: 4.13.8.1
- Pokecube Revival (if applicable): 4.9.13.1
- Pokecube Mobs (if applicable): 2.3.1
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.2.2099

**Comment by nrllewellyn** [comment]
Same behavior occurs if broken outside of creative mode.

**Comment by Thutmose** [comment]
I will look into ensuring the music turns off when broken.

**Comment by Thutmose** [comment]
this should be fixed for next release.

**Comment by Thutmose** [comment]
fixed in 4.13.9.1
