### ISSUE TITLE
Textures don't display properly when using JourneyMap

### ISSUE THREAD

**Issue by nrllewellyn** [Thutmose/Pokecube#158]
#### Issue Description:

Textures don't display properly when using JourneyMap
#### What happens:

When Journeymap is active, some pokemob's textures become solid white
#### What you expected to happen:

The two mods to work together with no rendering issues
#### Steps to reproduce:
1. Install Journeymap
2. Walk around looking at pokemobs

This doesn't happen every time, but has been more common with Koffing, Hoothoot, and other flying pokemobs. Textures remain broken until Minecraft is completely restarted. I'm fairly certain that this is caused by Journeymap--I had no broken textures with the minimap disabled and enabling it caused an immediate texture problem in at least one test.

---
#### Affected Versions (Do _not_ use "latest"):
- Pokecube Core: 4.13.8.1
- Pokecube Revival (if applicable): 4.9.13.1
- Pokecube Mobs (if applicable): 2.3.1
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.2.2099

**Comment by nrllewellyn** [comment]
More Info:
- Textures are not correct, even if Journeymap is disabled
- Performing a "reload textures" (F3+T) does not fix the issue
- The same bug occurs when entering/exiting the full-screen map

**Comment by Thutmose** [comment]
that is an issue with the latest journeymap iirc, last time I tested it it was also affecting vanilla mobs.

**Comment by nrllewellyn** [comment]
D'oh. Good call. Looks like they're actively working on it:
https://bitbucket.org/TeamJM/journeymap/issues/122/1102-journeymap-1102-530b1-unlimited

**Comment by P3rf3ctXZer0** [comment]
Yep

**Comment by nrllewellyn** [comment]
Confirmed: Development version of Journeymap (available via the link above) fixes the problem. This issue can be closed.

**Comment by Thutmose** [comment]
ok, I will close the issue.
