### ISSUE TITLE
Unable to use pokeplayer

### ISSUE THREAD

**Issue by singularity125** [Thutmose/Pokecube#159]
#### Issue Description:

(I am using the "Pokemon Adventure" modpack with manually updated mods, but it's very mod-lite so I don't think that is the issue)
In the new version of Pokecube I have cheated myself a transformer pad to test it, however I can't actually get it to work, perhaps I'm going about it the wrong way...?
#### What happens:

I have tried right-clicking the panel with the filled pokecube, nothing.
Shift right clicking drops the cube on the panel but still seems to do nothing when I step on it
Left clicking breaks the panel instantly and drops nothing (oops)
#### What you expected to happen:

Setting a pokemob to the panel would allow me to transform
#### Steps to reproduce:
1. Cheat in transformer panel
2. Place in world
3. Try interacting with it
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- Pokecube Core: 4.13.11
- Pokecube Revival (if applicable): 4.9.15
- Pokecube Mobs (if applicable): 2.3.1
- Minecraft: 1.10.2
- Forge: 12.18.2.2107

**Comment by Thutmose** [comment]
so when you right clicked it with the filled pokecube it didn't get placed inside it?

I will do some more testing on this, I hadn't tested it in the compiled version, only in development.

**Comment by Thutmose** [comment]
Well, I have confirmed that it is not working, I will try to find out why and get this fixed.

**Comment by Thutmose** [comment]
This should be fixed in Pokecube Revival 4.9.15.1 which I just uploaded, if it is not for you, reopen this issue.

**Comment by Thutmose** [comment]
The real fix for this might have been some tweaks in ThutCore, so update that to 3.6.5.2 as well.

**Comment by singularity125** [comment]
I have updated to the latest versions as of now (Pokecube Core 4.13.13, Mobs 2.3.3, revival 4.9.17, ThutCore 3.6.5.3). The basic functionality seems to be working, at least on the Charmander I tested, once I figured out alt+click is to use a move. But, it seems like my health bar is always showing as full despite the pokemon's actual health and so it makes fights difficult as you can imagine, heh. If you can look into that it would be awesome. Otherwise this mod's pretty fun!

**Comment by Thutmose** [comment]
are you in creative mode? it sets your health to always full in creative model
