### ISSUE TITLE
Pokecube Revival Sets Player Health to One Heart

### ISSUE THREAD

**Issue by nrllewellyn** [Thutmose/Pokecube#160]
#### Issue Description:

See title
#### What happens:

The player only has one heart of max health. Killing the player does not fix this.
#### What you expected to happen:

The player's health is unchanged.
#### Steps to reproduce:
1. Install Pokecube Revival
2. Look at health bar

---
#### Affected Versions (Do _not_ use "latest"):
- Pokecube Core: 4.13.13
- Pokecube Revival (if applicable): 4.9.17
- Pokecube Mobs (if applicable): 2.3.3
- Minecraft: 1,10.2
- Forge: 12.18.2.2105

**Comment by Thutmose** [comment]
yep, bug with loading in older version of pokeplayer, 2 possible fixes:
1. delete PokePlayer.dat from the world data folder.
2. use /pcedit @p pokeplayer-data and set health to 20.

I will get a version out that fixes this as well.

**Comment by nrllewellyn** [comment]
Hrm... starting a new world had the same problem, so I'm not sure that'd be the cause.

Tried both work-arounds, but no dice. This is just a test world, so I'll wait for the patch. :-) Let me know if you need any more details.

**Comment by Thutmose** [comment]
ok, patch is uploaded to curse, not sure when it will be approved

**Comment by Thutmose** [comment]
https://minecraft.curseforge.com/projects/pokecube-revival/files/2338827 this should fix the issue, let me know if it does not?

**Comment by nrllewellyn** [comment]
Fixed! Thanks for the quick response!

**Comment by Thutmose** [comment]
no problem :D
