### ISSUE TITLE
Create a compatibility mod Mo 'Bends.

### ISSUE THREAD

**Issue by NelkGames** [Thutmose/Pokecube#161]
The bug that exists:
The models are positioned incorrectly in the animation.

![screenshot_3](https://cloud.githubusercontent.com/assets/19228548/19670167/e440d4f4-9a43-11e6-8f1b-a6577ba8c8e8.png)

**Comment by Thutmose** [comment]
can you send some screenshots of the issues?

**Comment by Thutmose** [comment]
This has been fixed in latest version of Thut Wearables
