### ISSUE TITLE
Issues with BiomesOPlenty

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Thutmose/Pokecube#162]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here.

#### What happens:
Crash on startup

#### Steps to reproduce:

1. Add latest Pokecube everything and Biomes o plenty
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:
- Pokecube Revival (if applicable):
- Pokecube Mobs (if applicable):
- Minecraft: 1.10.2
- Forge:

**Comment by Thutmose** [comment]
This was installation error so i am closing this issue
