### ISSUE TITLE
placing items

### ISSUE THREAD

**Issue by spirithart** [Thutmose/Pokecube#164]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here.

hi i found you mod for pokemon i i downloaded it to try it out but unfortunately when i put down a table it disappears could you plz find a way to fix this it looks like a really fun mod :)  
#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:
- Pokecube Revival (if applicable):
- Pokecube Mobs (if applicable):
- Minecraft: 1.8.9
- Forge:

**Comment by spirithart** [comment]
ok never mind i fixed the issue and wow i love the mod. awesome job and sorry for wasting your time on that other text lol i just forgot to update forge. anyways i hope you have a wonderful day and week :D

**Comment by Thutmose** [comment]
closing this since you say you fixed it.
