### ISSUE TITLE
Release button crashes client

### ISSUE THREAD

**Issue by rtrevi** [Thutmose/Pokecube#165]
#### Issue Description:
Game crashes when "release" button is pressed on PC

#### What happens:
https://gist.github.com/Kagynt/ac130ccce8d07eeaeb575f25e4dd3e92

#### What you expected to happen:

release pkmn functionality

#### Steps to reproduce:

1.Enter the PC GUI
2.Click the "release" button

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core: 5.0.0.t
- Pokecube Revival (if applicable): 5.0.0.i
- Pokecube Mobs (if applicable): 2.4.2
- Minecraft: 1.11
- Forge: 1.11-13.19.0.2159

**Comment by Thutmose** [comment]
This is fixed in 5.0.0.u

https://minecraft.curseforge.com/projects/pokecube-core/files/2348998
