### ISSUE TITLE
No se ven los pokemobs

### ISSUE THREAD

**Issue by josealfredog** [Thutmose/Pokecube#166]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here.

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:
- Pokecube Revival (if applicable):
- Pokecube Mobs (if applicable):
- Minecraft: 1.10.2
- Forge:

**Comment by Thutmose** [comment]
what version of MinecraftForge are you using? use the latest one.


¿Qué versión de MinecraftForge está usando? Utilizar el último

**Comment by Thutmose** [comment]
since nothing has come back on this, I am closing it, please report again if it happens.
