### ISSUE TITLE
PokeMart Merchant's inventory is empty

### ISSUE THREAD

**Issue by rtrevi** [Thutmose/Pokecube#167]
#### Issue Description:
Pokemart inventory is empty

#### What happens:
When interacted with, the poke mart merchant has nothing to sell

#### What you expected to happen:
Display the usual items (pokecubes, mega stones, etc)

#### Steps to reproduce:

1.Go into a poke mart
2.right click the merchant

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core: 5.0.0.u
- Pokecube Revival (if applicable): 5.0.0.j
- Pokecube Mobs (if applicable): 2.4.2
- Minecraft: 1.11
- Forge:forge-1.11-13.19.0.2159
![capture](https://cloud.githubusercontent.com/assets/8525443/20645149/1cdd4d0a-b412-11e6-9855-79eaae301831.PNG)

**Comment by Thutmose** [comment]
this should be fixed in revival 5.0.0.k
