### ISSUE TITLE
Meelee moves acceleration bug

### ISSUE THREAD

**Issue by rtrevi** [Thutmose/Pokecube#168]
#### Issue Description:
pkmn with meelee attacks (such as tackle) can end up accelerating into the sky never to be seen again

#### What happens:
when a pkmn with meelee attacks tries to hit something out of its range, the pkmn's velocity will increase to ridiculous levels and might end up burying itself into the ground or into the sky, effect is more noticeable if 2 pkmn fighting are affected by it

#### What you expected to happen:
my bidoof hitting a swinub instead of becoming part of the sun's mass

#### Steps to reproduce:

1.summon a pkmn that only has tackle
2.get into creative mode and hover above the aforementioned pkmn
3.hit him (be sure to be as far as possible from the pkmn)
____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core: 5.0.0.u
- Pokecube Revival (if applicable): 5.0.0.j
- Pokecube Mobs (if applicable): 2.4.2
- Minecraft: 1.11
- Forge: forge-1.11-13.19.0.2159

**Comment by Thutmose** [comment]
this should be fixed in 5.0.0.v
