### ISSUE TITLE
/nbtedit does not work in SMP

### ISSUE THREAD

**Issue by kayila** [Thutmose/Pokecube#17]
#### Issue Description:
Typing `/nbtedit` while looking at an entity or tile entity should bring up a gui allowing for editing of the entity's data. Other forms include using `/nbtedit me` to bring up the editor for the player's data. Note this should only work for ops (unless a config flag is set)

#### What happens:
User types `/nbtedit` while looking at an entity and no dialog appears. The server does write in it's log that the user issued the command however. (`NBTEditpqb.log`)

#### What you expected to happen:
NBTEdit gui should open

#### Steps to reproduce:

1. Log into a SMP server with op permissions
2. Spawn any entity (In this case I've tested a Pokecube trainer, Pokemob, and Pokecube merchant)
3. Move within 2 blocks of the entity
4. Type `/nbtedit` - No gui will appear
5. Verify the `NBTEditpqb.log` file on the server registers the command
____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core: 2.3.1
- Pokecube Revival (if applicable): 2.2.15
- Pokecube Mobs (if applicable): 1.1.11
- Minecraft: 1.8.9
- Forge:  11.15.1.1764 (Both client and server)

**Comment by Thutmose** [comment]
Can you get me the server log from when you try this?

**Comment by Thutmose** [comment]
![image](https://cloud.githubusercontent.com/assets/2363472/13905701/cb2385f4-ee9d-11e5-9bbf-31666e0e73f8.png)

It works fine for me on my local server when connected via a local client.

**Comment by kayila** [comment]
Sure... Do you want the actual server log, or the NBTEdit log?

**Comment by kayila** [comment]
Update.... I can use `/nbtedit me` without a problem... But it doesn't work when I'm looking at an entity/tile entity such as a pokemob

**Comment by Thutmose** [comment]
Hmm, that is very odd, from that log, it looks like something is wrong with some of the packets, but in that case, /nbtedit me shouldn't work either

**Comment by Thutmose** [comment]
It works fine for me in the development environment, as well as my local server, so I don't know how to test what is wrong.

**Comment by kayila** [comment]
Hmmm... Ok. I'll do some more poking and see if I can get my dev environment up. If I can than I'll try to get it to reproduce it.

**Comment by Thutmose** [comment]
I suggest just doing the core dev environment to start with, since nbtedit is in core.

The way I setup one is to download the forge mdk, then place the gradle directory, the gradlew.bat into the Pokecube Core directory, then I run the setuppokecubecore.bat

**Comment by Thutmose** [comment]
Fixed this, I just merged in the changes made in the other NBTEdit branch.
