### ISSUE TITLE
[Suggestion for auto recall]

### ISSUE THREAD

**Issue by rtrevi** [Thutmose/Pokecube#171]
Implement a fail-safe for when trainer gets too far from pkmn.
This to make it harder to lose your pkmn by accidentally teleporting somewere.

In order to avoid recalling when user explicitly wanted to leave the pkmn there, perhaps just recall the pkmn if the pkmn's is not sitting.

**Comment by jochuan** [comment]
there is already that function in the mod you just need to turn it on in the config

**Comment by Thutmose** [comment]
the config is client side only, so it doesn't work well in this situation, as if you teleport elsewhere, the mob no longer shows up on client.  The client config would if you walk away from the mob when it is stuck, but doesn't work if you teleport away (say via a command, or some method other than using a pokemob to teleport)

**Comment by Thutmose** [comment]
Closing this issue, since It cannot be easily dealt with the teleporting, as I have no way to know when that is about to occur, and most usecase for this is dealt with by the client option.
