### ISSUE TITLE
Groudon/Kyogre Catching config question

### ISSUE THREAD

**Issue by HyperMan19680** [Thutmose/Pokecube#175]
I'm using the 1.11 Pokecube files, and I am wondering if the config that lets Groudon and Kyogre captures ignore their requirements is still around? If so, what am I looking for in the config files?

**Comment by Thutmose** [comment]
in 1.11 versions, there should be no capture requirements for anything besides mew.

the spawner blocks for kyogre and groudon are also gone in 1.11 however,

**Comment by HyperMan19680** [comment]
Well they keep breaking out.

**Comment by Thutmose** [comment]
does it say they "refused to enter the cube"?

**Comment by HyperMan19680** [comment]
They "broke out" of a Master Cube. Zekrom too.

**Comment by HyperMan19680** [comment]
Note the words "Master Cube" and "broke out". You shouldn't be able to break out of those in the Pokemon series. Why do they here?

**Comment by Thutmose** [comment]
that was a bug fixed in the latest version. they had capture rate of 0, even mastercube cannot catch something with capture rate of 0
