### ISSUE TITLE
Collision bugs: Articuno

### ISSUE THREAD

**Issue by hairlessOrphan** [Thutmose/Pokecube#177]
#### Issue Description:
Attempting to fight or capture Articuno in a cave, nine times out of ten he will clip into the ground and then sink into the stone down to bedrock level.

Additional bug: Occasionally - if you throw a pokecube *just* as he's sinking into the ground - the pokecube will not hit, but instead of returning to you, it will remain as an entity that can't be picked up or broken, but can be pushed (by walking into it) similar to a minecart.

#### What happens:
Articuno sinks into the ground.

#### What you expected to happen:
Articuno doesn't sink into the ground.

#### Steps to reproduce:

1. Use your Pokecube Core modpack on CurseForge:
https://minecraft.curseforge.com/projects/pokecube-pack
2. Load the attached save:
https://drive.google.com/file/d/0Byu3mwtobVP6RmpDM3l1QnVqVzA/view?usp=sharing
3. Throw pokemob out, attempt to capture Articuno.
...

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core: 5.0.3
- Pokecube Revival (if applicable): 5.0.2
- Pokecube Mobs (if applicable): 2.4.4
- Minecraft: 1.11
- Forge: 13.19.1.2189

**Comment by Thutmose** [comment]
things have changed since this issue, will close this for now, and let new one be opened if it is still needed.
