### ISSUE TITLE
Poke Cube Core 1.10.2 - Forge 209 Ticking Entity and Entity Stats Bug

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Thutmose/Pokecube#178]
#### Issue Description:
When the mods "menumobs" and "Pokecube Core" are present and you scroll through menu mobs; a ticking entity bug occurs.

https://gist.github.com/P3rf3ctXZer0/5e3e7e99e728dc8fc0a98d37364c5c69

#### What happens:
Slowly but surely while pokecube mob is on the title screen the log ticks into oblivion. Mainly takes place with pokecubes that have the seizure head bug.

#### What you expected to happen:
No issues.

#### Steps to reproduce:

1. Make a new modpack adding pokecube core and its primary parts and add Menu Mobs
2. Start Modpack till you find a pokemob on screen with a twitchy, siezury limb.
3. Watch the log.
...

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core: Pokecube Core-4.20.0.1
- Pokecube Revival (if applicable): Pokecube Revival-4.14.0.1
- Pokecube Mobs (if applicable): Pokecube Mobs-2.4.4
- Minecraft: 1.10.2
- Forge: 209

**Comment by P3rf3ctXZer0** [comment]
https://github.com/superbas11/MenuMobs/issues/20

**Comment by bschoenmaeckers** [comment]
I'm currently looking in this as well.

**Comment by bschoenmaeckers** [comment]
I reproduced the bug in the latest 1.10 version but it does not happen in 1.11.

**Comment by bschoenmaeckers** [comment]
fixed it on my side, you can close this.

**Comment by P3rf3ctXZer0** [comment]
@superbas11 ty
