### ISSUE TITLE
1.10.2 - Forge 209 -- Missing textures in JEI Renderer

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Thutmose/Pokecube#179]
#### Issue Description:
Missing textures in JEI
https://gist.github.com/P3rf3ctXZer0/2edc2efe65f36aa41afe022e695ed6f4

#### What happens:
Null

#### What you expected to happen:
Null

#### Steps to reproduce:

Null

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core: Pokecube Core-4.20.0.1
- Pokecube Revival (if applicable): Pokecube Revival-4.14.0.1
- Pokecube Mobs (if applicable): Pokecube Mobs-2.4.4
- Minecraft: 1.10.2
- Forge: 209

**Comment by Thutmose** [comment]
those textures don't actually exist, those mobs use special animated textures.  I will see about making it not give that message though.

**Comment by Thutmose** [comment]
these should all be fixed now that it uses icons.
