### ISSUE TITLE
power of two textures

### ISSUE THREAD

**Issue by jochuan** [Thutmose/Pokecube#18]
Some pokemobs have textures that arent a power of two and this make they appear white on my game because my graphics card only supports textures that are on a power of two,these pokemobs are :
- [x] Dewgong
- [x] Hitmonlee
- [x] Hitmonchan
- [x] Lapras
- [x] Gyarados
- [x] Omanyte
- [x] Omastar
- [x] Mareep
- [x] Flaaffy
- [x] Marill
- [x] Azumarill
- [x] Aipom
- [x] Murkrow
- [x] Misdreavus
- [x] Girafarig
- [x] Gligar
- [x] Snubbull
- [x] Granbull
- [x] Scizor
- [x] Sneasel
- [x] Corsola
- [x] Skarmory
- [x] Houndour
- [x] Houndoom
- [x] Tyrogue
- [x] Hitmontop
- [x] Sceptile
- [x] Blaziken
- [x] Swampert
- [x] Ralts
- [x] Kirlia
- [x] Gardevoir
- [x] Exploud
- [x] Azurill
- [x] Mawile
- [x] Swablu
- [x] Altaria
- [x] Banette
- [x] Absol
- [x] Snorunt
- [x] Glalie
- [x] Latias
- [x] Latios
- [x] Rayquaza
- [x] Jirachi
- [x] Ambipom
- [x] Mismagius
- [x] Honchkrow
- [x] Bronzor
- [x] Bronzong
- [x] Goodra
- [x] Sliggoo
- [x] Greninja
- [x] Braixen
- [x] Chesnaught 
- [x] Quilladin
- [x] Chespin
- [x] Haxorus
- [x] Fraxure
- [x] Axew 
- [x] Zoroark
- [x] Zorua
- [x] Lilligant
- [x] Petilil
- [x] Whimsicott
- [x] Scolipede
- [x] Whirlipede 
- [x] Venipede
- [x] Dewott
- [x] Oshawott
- [x] Emboar
- [x] Pignite
- [x] Tepig
- [x] Serperior
- [x] Servine
- [x] Snivy
- [x] Arceus 
- [x] Manaphy
- [x] Phione
- [x] Giratina
- [x] Froslass
- [x] Gallade
- [x] Gliscor
- [x] Yanmega
- [x] Weavile

**Comment by Thutmose** [comment]
Hmm, some of those will be rather problematic to fix.

Example: Dewgong uses a 72x64 texture, that cannot be resized to power of 2.

I can see If I can get a resource pack together which resizes the ones which have square textures (most of the ones on that list) but it will most likely result in some glitches in the textures, as I am not good at that sort of work.

This may require the models themselves to be editied (Will at least require that for Dewgong), and that will be very difficult for me to do, I will see about trying to do it, but it may go very badly due to my generally being inept at model related stuff.

**Comment by jochuan** [comment]
i finished the list those are all the pokemobs that have this problem

**Comment by jochuan** [comment]
what pokemobs can be resized correctly ?

**Comment by Thutmose** [comment]
The ones with square textures can probably be resized correctly (might have some distortions, but otherwise will be resizable)

They are:
Chespin
Tyrogue
Banette
Mareep
Bronzor
Axew
Blaziken
Braixen
Bronzong
Exploud
Flaaffy
Gallade
Gardevoir
Greninja
Hitmonlee
Kirlia
Omanyte
Omastar
Quilladin
Ralts
Skarmory
Swampert
Zoroark
Houndour
Sneasel
Weavile
Corsola
Aipom
Azurill
Chesnaught
Snubbull
Hitmontop
Froslass
Murkrow
Marill
Hitmonchan
Azumarill
Girafarig
Yanmega
Gligar
Houndoom
Gyarados
Scizor (+ Mega)
Granbull
Ambipom
Snorunt
Goodra
Sliggoo
Latias
Latios
Honchkrow
Misdreavus
Dewott
Emboar
Glalie
Gliscor
Haxorus
Oshawott
Pignite
Serperior
Servine
Snivy
Tepig
Zorua
Mismagius
Altaria

Some others, like Arceus might also be fixable.

I will try to make a texturepack with some re-sized textures, I will post it here when I have it made, let me know if it works.

**Comment by Thutmose** [comment]
[ResizedTextures.zip](https://github.com/Thutmose/Pokecube/files/202543/ResizedTextures.zip)

Here are several of the ones listed re-sized to 512x512, let me know if they work.

It should include everyone above Misdreavus in that list I wrote, that list is in order of size, so ones misdreveous and down need to be made larger than 512, I will do that if this set works.

I probably won't update the ones in mobs to this, as it just increases file size, and will keep this resourcepack somewhere incase others like you have the issue.

**Comment by Thutmose** [comment]
[ResizedTextures.zip](https://github.com/Thutmose/Pokecube/files/202583/ResizedTextures.zip)

This should have all of the textures requested resized to power of 2 squares, let me know if any are missing.

**Comment by jochuan** [comment]
Thanks i will test when i have tjme

**Comment by jochuan** [comment]
Fraxure,Emboar,Pignite,Serperior,Servine and Arceus still have this problem

**Comment by Thutmose** [comment]
But the rest worked?

**Comment by jochuan** [comment]
i am looking at them now and i didn't checked the shiny textures

**Comment by Thutmose** [comment]
Ahh, I seem to had forgotten to include fraxure

The rest on your list were the ones that were needed to be 1024x1024 to prevent loss of texture information, I can scale those down, but it might cause glitches with the textures.

**Comment by Thutmose** [comment]
try putting these in the resource pack:

[process.zip](https://github.com/Thutmose/Pokecube/files/222382/process.zip)

**Comment by jochuan** [comment]
the textures of some of them are a bit blurry but it worked i still looking for others that have this problem

**Comment by Thutmose** [comment]
I won't be able to fix the blurriness, as that is due to reducing the texture size, I am suprised that Altaria didn't have the issue as well.

**Comment by jochuan** [comment]
Snubbull and Altaria have this problem too

**Comment by Thutmose** [comment]
Here are those two.

[process.zip](https://github.com/Thutmose/Pokecube/files/222404/process.zip)

Altaria will probably be very blurry, it had a very large texture for some reason.

**Comment by jochuan** [comment]
Weavile and Yanmega shiny textures aren't a power of two

**Comment by Thutmose** [comment]
Ahh yes, some of the new shiny textures were not included in the original set (I didn't have them yet)

If you can get me a complete list of the shiny textures which are not, I can resize them for you.

**Comment by jochuan** [comment]
i will probably make this tomorrow

**Comment by jochuan** [comment]
Yanmega,Weavile,Sneasel,Tyrogue,Sceptile,Ralts,Swablu,Snorunt and Rayquaza have shiny textures that arent a power of two

**Comment by Thutmose** [comment]
[process.zip](https://github.com/Thutmose/Pokecube/files/222455/process.zip)

Here are those shiny textures.

**Comment by jochuan** [comment]
Phione,Venipede,Whirlipede,Scolipede,Whimsicott,Petilil,Zorua,Sliggoo shiny textures arent a power of two

**Comment by Thutmose** [comment]
[process.zip](https://github.com/Thutmose/Pokecube/files/235235/process.zip)

Here is that set.

**Comment by jochuan** [comment]
Mega Banette texture isnt a power of two

**Comment by Thutmose** [comment]
[process.zip](https://github.com/Thutmose/Pokecube/files/243829/process.zip)

Here is mega banette textures.

**Comment by jochuan** [comment]
Pidgeot mega,Mewtwo mega-y,Cofagrigus arent a power of two

**Comment by Thutmose** [comment]
[process.zip](https://github.com/Thutmose/Pokecube/files/253640/process.zip)

Here are those.

**Comment by jochuan** [comment]
Pinsir and his mega,Grumpig and Rotom Frost textures arent a power of two

**Comment by Thutmose** [comment]
[process.zip](https://github.com/Thutmose/Pokecube/files/276062/process.zip)

Here are these.

**Comment by jochuan** [comment]
i found out that the mega ring texture isnt a power of two

**Comment by jochuan** [comment]
sucuine,swampert mega,mawile mega and rotom heat textures arent a power of two

**Comment by jochuan** [comment]
vivillon,bunnelby,diggersby arent a power of two too

**Comment by Thutmose** [comment]
[process.zip](https://github.com/Thutmose/Pokecube/files/288098/process.zip)

This should be those.

**Comment by jochuan** [comment]
Dedenne,Empoleon and arcanine textures arent a power of two

**Comment by jochuan** [comment]
Zygarde,Houndoom mega,Pancham and Pangoro textures aren't a power of two too i think that i can fix the pangoro texture.

**Comment by jochuan** [comment]
Pinsir shiny and the pokedex GUI of 1.9.4 arent a power of two

**Comment by jochuan** [comment]
http://www.mediafire.com/download/p66ds6jcsckt5f3/ResizedTextures.zip
here is latest power of two pack

**Comment by jochuan** [comment]
i updated the power of two pack it is using the same link i think that you should add it to the front page of the pokecube thread for other people that may have the same issue that me

**Comment by Thutmose** [comment]
I will do so, I will re-upload that zip here though, and link to this one, as mediafire is sometimes known for pushing questionable ads.

[ResizedTextures.zip](https://github.com/Thutmose/Pokecube/files/392063/ResizedTextures.zip)

**Comment by Thutmose** [comment]
Remake this issue over in https://github.com/Thutmose/Pokecube-Models if you still need it.
