### ISSUE TITLE
Selector for gene extractor and splicer

### ISSUE THREAD

**Issue by chandlerjones20** [Thutmose/Pokecube#180]
#### Issue Description:
Doesnt say how to make a selector for the gene extractor or the gene splicer.

#### What happens:
those pages of the guide book say null.

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:
- Pokecube Revival (if applicable):
- Pokecube Mobs (if applicable):
- Minecraft: 1.8.9
- Forge:

**Comment by Thutmose** [comment]
I will see if I can find out why some of the pages ended up null.

You make a written book, called "Selector" and put the name of the genes to select each on a line on the first page of the book.  If you put "all" there, it selects all of the genes.

You can also use the method in OpenComputers for a selector as well, which doesn't consume written books.

**Comment by chandlerjones20** [comment]
it doesnt work once i get all the ingrediants in the gene extractor it doesnt do anything

**Comment by Thutmose** [comment]
so you put a pokemob egg or fossil in the dna slot, a bottle of water in the bottle slot, and the selector into the selector slot? where selector is a book called "Selector" and say has "all" written on the first line?

What other mods do you have? iirc if you have ic2, you need to make the bottle of water with a cauldron, as  ic2 messes with the other bottles.

**Comment by chandlerjones20** [comment]
i have the default mods for pokemon adventures

**Comment by chandlerjones20** [comment]
and yes i did all those things correctly

**Comment by Thutmose** [comment]
send screenshots of your setup? I will be able to test things when I get back to my PC in 2.5 hours or so.

**Comment by chandlerjones20** [comment]
i cant send any right now i will have to do it later but  can you tell me
how to set up the gene extractor without the ingredients but the extractor
itself is there a certainplace to put it or do you have to have other
things with it

**Comment by chandlerjones20** [comment]
i cant send any right now i will have to do it later but  can you tell me how to set up the gene extractor without the ingredients but the extractor itself is there a certainplace to put it or do you have to have other things with it

**Comment by Thutmose** [comment]
oh right, it needs to have an energy siphon placed touching it, then an electric pokemob near that, I wonder if the page mentioning that it requires power is one of the null pages...

**Comment by chandlerjones20** [comment]
i think so XD

**Comment by chandlerjones20** [comment]
i got it working thanks

**Comment by Thutmose** [comment]
Guidebook has had the null pages dealt with in latest versions, I will probably see about adding a basic recipe for an "all" selector as well, which should help alleviate this issue in the future.
