### ISSUE TITLE
[Suggestion] Changing the sound when a pokemob dodge.

### ISSUE THREAD

**Issue by CorentG** [Thutmose/Pokecube#185]
The actual sound is brutal in my opinion (i was actually using a rescource pack for removing that sound lol), so i searched a less brutal sound in vanilla Minecraft files, and i found "minecraft/sounds/entity/witch/throw3.ogg" which is, i think, much more adapted. I'm pretty sure this is an easy change, so what do you think ? (If this is possible, you can try using all 4 "throw" sounds of the witch)

**Comment by Thutmose** [comment]
I can change that, I can possibly even make it configurable, I will look into it, currently it uses the vanilla small fall sound

Currently it uses: "entity.generic.small_fall"  I can probably make this configurable, and maybe even have it allow a random set of sounds to make.

**Comment by Thutmose** [comment]
This has been fixed in ^ commit, there is now a config for it, I will see about swapping to the throw sound instead for the defaults.
