### ISSUE TITLE
Restricting all world gen and mod spawning to a single dimension.

### ISSUE THREAD

**Issue by Thedrummonger** [Thutmose/Pokecube#187]
Is there a way to restrict all world gen and mob spawning from this mod to a single dimension? If possible I would like all Pokecube mobs and world gen to only spawn in McJty's lost cities dimension. I tried to add the dimension id to the dimensionWhitelist config and set the whiteListEnabled to true in the pokecube.cfg file but it didn't seem to make a difference. If it's not currently possible I would like to request it as a feature as it would allow this mod to be used in a larger variety of packs.
Thanks!

**Comment by Thutmose** [comment]
Ahh, that sounds like my whitelist isn't working somehow then, I will add fixing this onto my list of things to fix tomorrow.

that functionality is exactly what the whitelist/blacklist was made for, but it was only tested with a tardis mod a year or two ago, so something has probably broken with it since then.

**Comment by Thutmose** [comment]
Seems this was rather broken when I moved some config stuff around, had got some checks backwards when I re-made it.  This will be fixed for the next version of Pokecube Core which is released.

**Comment by Thutmose** [comment]
I also made it so that there is a config for which dimension the pokecenter is made in, and all of the worldgen will now respect the whitelist, as well as the blacklist.

**Comment by Thutmose** [comment]
This should now be dealt with in the following versions of pokecube core:
1.10.2: 4.24.4
1.11.2: 5.4.3
1.12: 6.1.11

Let me know if there are any other features that would be useful for pack-makers that I should add in.

**Comment by Thedrummonger** [comment]
Awesome, thanks for the quick fix! I got to test it a bit before work this morning, the white list for the Pokemon center work perfectly and the mob whitelist successfully stopped Pokemon from spawning in the overworld, however they also didn't seem to spawn in the whitelisted dimension. Is there a config I'm missing that needs to be changed to allow them to spawn in other dimensions? I wish I came with more information but if you need logs or anything I can definitely get those to you after work.
Thanks!

**Comment by Thutmose** [comment]
I probably messed up somewhere, all it should require is setting whiteListEnabled to true, then putting a number in dimensionWhitelist, I bet I have something further down the spawn pipeline interfering, I will look into it.

**Comment by Thutmose** [comment]
I think I found the issue, will have it fixed shortly.

**Comment by Thutmose** [comment]
Compiled and uploaded the following versions to hopefully fix it (I had forgotten a ! in one of the 5 places the list is checked)

1.10.2: 4.24.4 (last one was actually 4.24.3, had typo in post)
1.11.2: 5.4.4
1.12: 6.1.13
