### ISSUE TITLE
Pokecube Alternative Exp Share Incompatabilty

### ISSUE THREAD

**Issue by Thedrummonger** [Thutmose/Pokecube#188]
Due to the nature of Pokecube Alternative the exp share is unable to function as it's supposed to. Any way you could allow the exp share to work for Pokemon in the pokebelt?
Thanks!

**Comment by Thutmose** [comment]
it should function as it is intended to for pokecube, you can still send out multiple pokemobs with alternative.  Either alt or ctrl will allow you to swap slot when you have a pokemob out, and then you can send out the second one.
