### ISSUE TITLE
Latest version for 1.9 crash involving "Exception while ticking a block" and similar

### ISSUE THREAD

**Issue by Enohpoxas** [Thutmose/Pokecube#19]
#### Issue Description:
Crash after 10 seconds to 1 minute of play.

#### What happens:
I load a world, wait, and then it crashes. Moving or sending out a Pokemon seems to make it occure sooner.

#### What you expected to happen
The game not crashing (at least the first time)

#### Steps to reproduce:

1. Install Thucore 3.0.4, Pokcube Core 3.0.4, Pokecube Mobs 2.0.3, with any version of forge between 1858 and 1863
2. Create new world
3. Walk around and/or send out a Pokemon
...

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core: 3.0.4
- Pokecube Revival (if applicable): N/A
- Pokecube Mobs (if applicable): 2.0.3
- Thutcore: 3.0.4
- Minecraft: 1.9
- Forge: 1858, 1859, 1860, 1861, 1862, and 1863

Here are some crash reports. The last six of them are with only Pokecube Core 3.0.4, Thutcore 3.0.4, and Pokecube Mobs 2.0.3 and each with a different version of forge from 1858 to 1863. The rest contain random other mods installed. 

[crash-2016-04-10_20.06.13-server.txt](https://github.com/Thutmose/Pokecube/files/212157/crash-2016-04-10_20.06.13-server.txt)
[crash-2016-04-10_20.11.28-server.txt](https://github.com/Thutmose/Pokecube/files/212161/crash-2016-04-10_20.11.28-server.txt)
[crash-2016-04-10_20.14.58-server.txt](https://github.com/Thutmose/Pokecube/files/212158/crash-2016-04-10_20.14.58-server.txt)
[crash-2016-04-10_20.19.56-server.txt](https://github.com/Thutmose/Pokecube/files/212160/crash-2016-04-10_20.19.56-server.txt)
[crash-2016-04-10_20.23.58-server.txt](https://github.com/Thutmose/Pokecube/files/212159/crash-2016-04-10_20.23.58-server.txt)
[crash-2016-04-10_20.26.54-server.txt](https://github.com/Thutmose/Pokecube/files/212162/crash-2016-04-10_20.26.54-server.txt)
[crash-2016-04-10_20.29.22-server.txt](https://github.com/Thutmose/Pokecube/files/212164/crash-2016-04-10_20.29.22-server.txt)
[crash-2016-04-10_20.32.40-server.txt](https://github.com/Thutmose/Pokecube/files/212163/crash-2016-04-10_20.32.40-server.txt)
[crash-2016-04-10_20.38.53-server.txt](https://github.com/Thutmose/Pokecube/files/212165/crash-2016-04-10_20.38.53-server.txt)
[crash-2016-04-10_20.44.24-server.txt](https://github.com/Thutmose/Pokecube/files/212166/crash-2016-04-10_20.44.24-server.txt)
[crash-2016-04-10_20.53.54-server.txt](https://github.com/Thutmose/Pokecube/files/212167/crash-2016-04-10_20.53.54-server.txt)
[crash-2016-04-10_20.56.52-server.txt](https://github.com/Thutmose/Pokecube/files/212168/crash-2016-04-10_20.56.52-server.txt)
[crash-2016-04-10_21.12.59-server.txt](https://github.com/Thutmose/Pokecube/files/212174/crash-2016-04-10_21.12.59-server.txt)
[crash-2016-04-10_21.15.58-server.txt](https://github.com/Thutmose/Pokecube/files/212169/crash-2016-04-10_21.15.58-server.txt)
[crash-2016-04-10_21.18.31-server.txt](https://github.com/Thutmose/Pokecube/files/212170/crash-2016-04-10_21.18.31-server.txt)
[crash-2016-04-10_21.21.36-server.txt](https://github.com/Thutmose/Pokecube/files/212171/crash-2016-04-10_21.21.36-server.txt)
[crash-2016-04-10_21.24.43-server.txt](https://github.com/Thutmose/Pokecube/files/212172/crash-2016-04-10_21.24.43-server.txt)
[crash-2016-04-10_21.27.50-server.txt](https://github.com/Thutmose/Pokecube/files/212173/crash-2016-04-10_21.27.50-server.txt)
[crash-2016-04-10_21.32.05-server.txt](https://github.com/Thutmose/Pokecube/files/212175/crash-2016-04-10_21.32.05-server.txt)

**Comment by Thutmose** [comment]
I am waiting on forge to release a "stable" build before trying to fix that crash. Last time something like that was happening (early in the 1.8.8 releases) it was due to a bug in vanilla (fixed by forge).

The crash itself indicates nothing to do with pokecube, so I assume it is some vanilla bug that pokecube happens to be triggering somehow. I have disabled the multi-threaded AI for 1.9, but that didn't fix it, so it wasn't a threading issue.

What I know about that crash:
It occurs when either fire tries ticking or fluid blocks try to flow, something in the thing used for flowing/determining what to burn has an error and crashes.
The code that this occurs in is not changed by pokecube in any way, so I am not sure why or how it could be caused to crash, and not always occur vanilla as well.

What I don't know about that crash:
Why is occurs
What causes it to occur
How to test fixes for it.

**Comment by Enohpoxas** [comment]
So it is the bug you already told me about. Sorry for bringing it up again.
Again thanks for the quick response.

**Comment by Thutmose** [comment]
No problem, ya, due to that bug, I have been doing all of my testing on a flat world, to make sure everything directly pokecube related is functional, vanilla itself isn't quite stable for 1.9 yet either, so I figured I would leave any vanilla related bugs for later.

**Comment by Thutmose** [comment]
I Think these issues are fixed in the 1.9.4 versions, I will re-open this issue if they are not.
