### ISSUE TITLE
Shoulder Pokemobs ignore scale for rendering, also issues with shoulder pichu/pikachu.

### ISSUE THREAD

**Issue by wilsondgonzales** [Thutmose/Pokecube#190]
Reminder for 

1. Pikachu and Pichu rendering with old code

2. pidove test with 1 half size still render the same size on shoulder mounting.

**Comment by Thutmose** [comment]
I am moving this issue over to the Pokecube-Mobs repository instead.

https://github.com/Thutmose/Pokecube-Mobs/issues/1
