### ISSUE TITLE
Pokecube 1.12 Crash to evolve the pokemon in lan world

### ISSUE THREAD

**Issue by NelkGames** [Thutmose/Pokecube#195]
#### Issue Description:
The game is crashing when a pokemon evolves into the lan world.

#### Affected Versions (Do *not* use "latest"):

- Pokecube Core: 6.9.1
- Pokecube Revival (if applicable): 6.6.0
- Pokecube Mobs (if applicable): 2.10.0
- Minecraft: 1.12
- Forge: 1.12- 14.21.1.2419

**Comment by Thutmose** [comment]
can you include the crash report? can you also confirm that it still occurs in the latest beta versions?

**Comment by NelkGames** [comment]
The game does not create the crash file in the folder .. but I will send a print. And yes, I tested this beta and this error continues.

**Comment by NelkGames** [comment]
I just tested the version:Core 6.10.3 and it looks like it's not giving the error. But the Pokémon are not evolving .. I tested shellder and pikachu.
[crash-2017-07-24_15.40.08-server.txt](https://github.com/Thutmose/Pokecube/files/1171647/crash-2017-07-24_15.40.08-server.txt)
[2017-07-24-4.log.gz](https://github.com/Thutmose/Pokecube/files/1171648/2017-07-24-4.log.gz)

**Comment by Thutmose** [comment]
that crash you linked suggests you had Pokecube Core-6.10.0.jar running at the time, and should have been fixed by 6.10.3, can you check that it is the same crash?

I think the one in the log.gz was fixed in the recent version as well? make sure you do have latest versions, then see if it still crashes.

**Comment by NelkGames** [comment]
I will test the Core 6.10.7 version to see if the error persists. The logs I sent you were version 6.10.0, because version: 6.10.3 was not evolving but did not create a crash file in the game or warned of an error.

**Comment by NelkGames** [comment]
Everything is working 
:D, even though the stone evolution is off?
![screenshot_2](https://user-images.githubusercontent.com/19228548/28573833-507b1494-7122-11e7-9d59-6337d3fe92f6.png)

**Comment by Thutmose** [comment]
I will look into the stone evolution, I had done my initial testing on it, but something could have broken later in the changes.

**Comment by Thutmose** [comment]
I have this fixed for next release.

**Comment by Thutmose** [comment]
This should be fixed in latest releases, re-open issue if it re-occurs, or remake issue.
