### ISSUE TITLE
 pokecube adventures

### ISSUE THREAD

**Issue by Snez0kRU** [Thutmose/Pokecube#197]
#### Issue Description:
Have a game crash

#### What happens:
sometimes, have this crash when runnning server on ver 1.10.2

#### Steps to reproduce:
didn't know, i just standing in my world and did nothink. pls see crashreport file
[Another crash.txt](https://github.com/Thutmose/Pokecube/files/1169629/Another.crash.txt)

____
#### Affected Versions (Do *not* use "latest"):
	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2281-universal.jar) 
	Forge{12.18.3.2281} [Minecraft Forge] (forge-1.10.2-12.18.3.2281-universal.jar) 
	ItemBlacklist{1.2.0.11} [ItemBlacklist] (ItemBlacklist-1.9.4-1.2.0.11.jar) 
	loot_crates{1.0.0} [Loot Crates] (lootcrate-0.0.5.jar) 
	thutcore{3.16.0} [Thut Core] (thutcore-3.16.0.jar) 
	pceditmod{1.10.2-2.0.0} [In-game NBTEdit - Pokecube Edition] (Pokecube Core-4.31.0.jar) 
	pokecube{4.31.0} [Pok?cube Core] (Pokecube Core-4.31.0.jar) 
	pokecube_ml{0.1.0} [Pokecube Model Loader] (Pokecube Core-4.31.0.jar) 
	thut_wearables{1.1.1} [Thut's Wearables] (thut_wearables-1.1.1.jar) 
	thut_bling{1.0.1} [Thut's Bling] (thut_bling-1.0.1.jar) 
	thutessentials{1.5.25} [Thut Essentials] (thutessentials-1.5.25.jar) 
	pokecube_adventures{4.20.0} [Pok?cube Revival] (Pokecube Revival-4.20.0.jar) 
	pokecube_mobs{2.10.0} [Pok?cube Mobs] (Pokecube Mobs-2.10.0.jar) 
	pokecube_moves{@VERSION@} [Pokecube Movess] (Pokecube Mobs-2.10.0.jar) 
	pokecube_origin{@VERSION@} [Pokecube Origin] (Pokecube Mobs-2.10.0.jar) 
	pokecube_compat{1.0} [Pokecube Compat] (Pokecube Revival-4.20.0.jar) 
	pokeplayer{@VERSION} [Pokecube Mystery Dungeon] (Pokecube Revival-4.20.0.jar) 
	pokecubeserverutils{1.4.0} [Pokecube Server Utils] (pokecubeserverutils-1.4.0.jar) 
	thutcrafts{0.0.4} [ThutCrafts] (thutcrafts-0.0.4.jar) 
	worldedit{6.1.4} [WorldEdit] (worldedit-forge-mc1.10.2-6.1.4-dist.jar) 
	thutperms{0.1.1} [Thut Permissions] (thutpermissions-0.4.0.jar) 
	worldlimiter{1.0.2} [World Limiter Mod] (worldlimiter-1.10.2-1.0.2.jar)

**Comment by Thutmose** [comment]
Ahh, I think I know what happened, I will try to get it fixed, unfortunately might be a bit for a 1.10.2 version of the fix, as I am currently doing testing on the new beta versions for 1.12 before I will upload the 1.10.2 and 1.11.2 versions

**Comment by Snez0kRU** [comment]
Thank you comrade, I'll look forward to it, too.

**Comment by Thutmose** [comment]
this issue should be fixed now, re-open or remake issue if it occurs again.
