### ISSUE TITLE
Pokecube with Sponge 1.10.2

### ISSUE THREAD

**Issue by Snez0kRU** [Thutmose/Pokecube#198]
#### Issue Description:
Pokemons Dupe

#### What happens:
When i click "q" button or just trying to send my pokecube to PC, it send 1 to it, and this pokecube still in my invenotory. After all i have 2 pokecubes == dupe.

#### What you expected to happen:
Didn't know, but will open Issues on sponge git too.

#### Steps to reproduce:
1. You need to download all mods from my list, and done from "What happens"

____
#### Affected Versions (Do *not* use "latest"):
	Pokecube Core-4.31.0.jar
        Pokecube Mobs-2.10.0.jar
        Pokecube Revival-4.20.0.jar 
        pokecubeserverutils-1.4.0.jar
        thutcore-3.16.0.jar
        spongeforge-1.10.2-2281-5.2.0-BETA-2433.jar

![2017-07-24_18 33 14](https://user-images.githubusercontent.com/30385407/28531720-5098a676-70a0-11e7-9c11-6360ce7aeffe.png)
![2017-07-24_18 33 15](https://user-images.githubusercontent.com/30385407/28531721-509abd1c-70a0-11e7-85ee-cb758b19db76.png)
![2017-07-24_18 33 19](https://user-images.githubusercontent.com/30385407/28531722-509c8570-70a0-11e7-980e-1ae2724ae36e.png)

**Comment by Snez0kRU** [comment]
Someone understands why this happens, or how to fix it, maybe just need to switch something in config, which blocking event sending from player inventory to chest?

**Comment by Thutmose** [comment]
Hmm seems like sponge might be interfering with the toss event somehow, are there any errors showing up in console?

**Comment by Snez0kRU** [comment]
Clear consol has been spoted. If there were errors I would have already thrown a log. Can you fix this ? I really do not want to go to a clean forge without sponge and i open such theme into sponge git, but it's still empty

**Comment by Thutmose** [comment]
I am not sure if I can fix it, it depends on what sponge is doing to cause the crash, I suspect it is messing with the toss event, but I am not sure how or why

**Comment by Snez0kRU** [comment]
When you will have time pls try to look deeper in this. Sponge team, didn't do anythink with it, just mark it with 1.10.2 tag https://github.com/SpongePowered/SpongeForge/issues/1673

**Comment by Thutmose** [comment]
I posted what I think is occurring on that issue, hopefully the sponge team can respond to it.
