### ISSUE TITLE
unable to connect to server

### ISSUE THREAD

**Issue by Thedrummonger** [Thutmose/Pokecube#200]
When I try to connect to a server using a custom made modpack that includes this mod I am unable to connect. I am given the message Fatally missing blocks or items. Upon reviewing the logs it seems the missing items are from this mod. The server and client are using the exact same config and mod version (Literally copy and pasted from one to the other). This problem does not persist if Pokecube Core, Mobs, Revival and alternative are removed from the server and client. Here is the hopefully relevant Log https://pastebin.com/xqsu1Vqj ,I can send the whole thing if you need.
Thanks!

- Pokecube Core: 6.11.4
- Pokecube Revival (if applicable): 6.8.1
- Pokecube Mobs (if applicable): 2.12.0
- Minecraft: 1.12
- Forge: 14.21.1.2426

**Comment by Thutmose** [comment]
check your configs, those things claiming to be missing are recipes? I didn't think those should be an issue to be different on client and server, but maybe they are in 1.12, see if making the two configs identical fixes it.

**Comment by Thedrummonger** [comment]
Ah apologies this issue was my fault. You were right on the money in that in 1.12 recipes can't be different on the client and server. It was was not the fault of your mod but some craftweaker scripts that were not installed server side. That issue does seem new as it was never an issue before. Anyway like I said this was an error on my part so this can be closed. Thanks!

**Comment by Thutmose** [comment]
ahh, ya prior to the 1.12 recipes were not in a "real" registry, so there was no enforcement between client and server settings, so this issue probably resulted from the new 1.12 stuff.
