### ISSUE TITLE
Pokemob Inventories not working on Sponge servers.

### ISSUE THREAD

**Issue by Snez0kRU** [Thutmose/Pokecube#202]
#### Issue Description:
PokeChest didn't opened n Sponge server in new version

#### What happens:
Today 1 plfayer reported me that, his pokechest in pokemon didn't work well. And today i update server to new versions of the mod. He call his pokemon, than press right button of the mouse, and nothink happened, other in single player all work great.

#### What you expected to happen:
If really... probably didn't know. Few days ago all was fine. No errors on client console, and no errors on server console. 

#### Steps to reproduce:
1.Install all mods from modlist
2.Call pokemob
3.Try to open his pokechest
...

____
#### Affected Versions (Do *not* use "latest"):
![21312321321321](https://user-images.githubusercontent.com/30385407/28745223-628ae4d6-747c-11e7-8290-3af87787bbbf.png)

**Comment by Thutmose** [comment]
Hmm, I wonder if sponge is messing with the interact event, I will try to look into this.

**Comment by Snez0kRU** [comment]
@Thutmose Good luck comrade, I'll take up tests of new versions and my comrades will try to find more bugs

**Comment by Thutmose** [comment]
here is the related issue on spongeforge's github:

https://github.com/SpongePowered/SpongeForge/issues/1689

**Comment by Thutmose** [comment]
This has been fixed in at least the 1.12 version of sponge, idk if they got it fixed on any other versions though.

**Comment by Thutmose** [comment]
this should be fixed now, spongeforge fixed it on their end.
