### ISSUE TITLE
Pokecube 1.12 crash save

### ISSUE THREAD

**Issue by NelkGames** [Thutmose/Pokecube#204]
#### Issue Description:
Saves are crashing before being started. You create the save, it loads, connects and crashes.

[erros.zip](https://github.com/Thutmose/Pokecube/files/1185061/erros.zip)

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core: 6.11.5
- Pokecube Revival (if applicable): 6.8.1
- Pokecube Mobs (if applicable): 2.13.0
- Minecraft: 1.12
- Forge: 14.21.1.2424

**Comment by Thutmose** [comment]
Update your pokecube core (;atest should be 6.12.x), re-open this issue if it still occurs after that.
