### ISSUE TITLE
/summon command

### ISSUE THREAD

**Issue by Lars201201** [Thutmose/Pokecube#207]
#### Issue Description:
 the /summon pokecube_ml:<name>  doesn't works how it should.

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core: 6.15.0
- Pokecube Revival (if applicable): 6.9.0
- Pokecube Mobs (if applicable): 2.14.1
- Minecraft: 1.12
- Forge: 14.21.1.2428

**Comment by Thutmose** [comment]
use /pokemake command instead, or specify the full nbt in the /summon.

See here for more details on the command: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2218222-pokecube-revival-adding-600-pokemon-to-minecraft?page=71#c1427
