### ISSUE TITLE
Lost pokemon and Lost items

### ISSUE THREAD

**Issue by RockyMcRock2** [Thutmose/Pokecube#208]
#### Issue Description:
I was at spawn and I accidently clicked a pressure plate automatily turned me into a magnetmite and it killed me, I said alright well ill get my stuff but I couldn't find all my stuff and my gardvior lvl 45 with a garviorite mega stone, lyraroc lvl 34 and mudbrey lvl 5 was gone as well and was not appering in my pc. I turned back and log in and out and they are still missing

The current version is whatever the Test development server is for pokecubes. 
____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:
- Pokecube Revival (if applicable):
- Pokecube Mobs (if applicable):
- Minecraft: 1.8.9
- Forge:

**Comment by MarshyyMallows** [comment]
Um i died and all my pokemon and my stuff were deleted,

**Comment by Thutmose** [comment]
were you playing as a pokemob, or were you a player? also was keep inventory on or off? maybe you just dripped the stuff? did the pokemobs go to PC?

**Comment by MarshyyMallows** [comment]
I was a player, keep inventory was on, and I did /back when I noticed I had nothing and when I went back there was nothing there, I only had one Pokémon left for some reason, and the rest of my stuff and my three Pokémon were gone

**Comment by Thutmose** [comment]
was this in single player or multiplayer?
what additional mods were involved? if multiplayer, please include server-only mods, plugins, etc.
does it happen every time you die and what exact versions of the mods are you usin?

**Comment by MarshyyMallows** [comment]
It was in multiplayer, and it was a server pack that was 1.10.2 and I have not died again so I don't know

**Comment by Thutmose** [comment]
Pokeplayer moved here https://github.com/Thutmose/Pokeplayer please refile this issue there if it still persists
