### ISSUE TITLE
Repel block does not limit Pokemob spawns

### ISSUE THREAD

**Issue by Farsinuce** [Thutmose/Pokecube#209]
#### Issue Description:
Repel blocks does not seem to stop pokemobs from spawning.

#### Steps to reproduce:
1. Place down a repel block
2. Set distance to e.g. 63 by right-clicking on it with a Jaboca berry
3. New Pokemobs still seem to spawn in the area

____
#### Affected Versions:
- Pokecube Core-6.17.4
- Pokecube Revival-6.9.4
- Pokecube Mobs-2.14.2
- pokecube_alternative-2.2.1
- thutcore-5.9.0
- Minecraft: 1.12
- Forge: 14.21.1.2443

**Comment by Thutmose** [comment]
I will look into this.

**Comment by Thutmose** [comment]
^ commit should have fixed it, will have new versions uploaded later tonight.

**Comment by Thutmose** [comment]
Seems that fix only worked for 1.10.2 and 1.11.2

**Comment by Thutmose** [comment]
Now this is closed, fixd in Pokecube Core 6.20.0

**Comment by Farsinuce** [comment]
Awesome.
Good job :) I will test 6.20.0 this evening (GMT+1).

**Comment by Thutmose** [comment]
wait on 6.20.1, I uploaded it a few minutes ago, it fixes an issue where apparently ridden mobs were not controllable in 6.20.0, due to an unrelated thing to this, and the riding speed configs

**Comment by Farsinuce** [comment]
I can confirm that repel blocks work again in Pokecube Core-6.20.1.jar - also around `/spawn`.

Thank you very much 👍
