### ISSUE TITLE
fix it please

### ISSUE THREAD

**Issue by arata00** [Thutmose/Pokecube#214]
the pokemon named meloetta as on de pokedex but is not posible to spawn it 

but otherwise I have never had a problem with the mod you do a great job I hope that the updates come faster even with little content, and I am very anxious for the 3 pokemon thundurus, tornadus and landorus to be added to the mod
thanks for the effort

here is a list I made with the missing pokemons in the mod

352-kecleon
401-kricketot
402-kricketune
434-stunky
435-stuntank
455-carnivine
456-finneon
457-lumineon
465-tangrowth
467-magmortar
506-lillipup
507-herdier
508-stoutland
511-pansage
512-simisage
513-pansear
514-simisear
515-panpour
516-simipour
529-drilbur
530-excadrill
532-timburr
533-gurdurr
534-conkeldurr
538-throh
539-sawk
540-sewaddle
541-swadloon
542-leavanny
550-basculin
559-scraggy
560-scrafty
564-tirtouga
565-carracosta
566-archen
567-archeops
568-trubbish
569-garbodor
572-minccino
573-cinccino
580-ducklett
581-swanna
588-karrablast
589-escavalier
592-frillish
593-jellicent
605-elgyen
606-beheeyem
615-cryogonal
616-shelmet
617-accelgor
619-mienfoo
620-mienshao
621-druddigon
622-golett
623-golurk
626-bouffalant
627-rufflet
628-braviary
629-vullaby
630-mandibuzz
631-heatmor
638-cobalion
639-terrakion
640-virizion
641-tornadus
642-thundurus
645-landorus
648-meloetta
667-litleo
668-pyroar
669-flabebe
670-floette
671-florges
672-skiddo
673-gogoat
676-furfrou
682-spritzee
683-aromatisse
684-swirlix
685-slurpuff
688-binacle
689-barbaracle
692-clauncher
693-clawitzer
694-helioptile
695-heliolisk
701-hawlucha
710-pumpkaboo
711-gourgeist
720-hoopa
721-volcanion
739-crabrawler
740-crabominable
741-oricorio
742-cutiefly
743-ribombee
747-mareanie
748-toxapex
751-dewpider
752-araquanid
755-morelull
756-shiinotic
757-salandit
758-salazzle
759-stufful
760-bewear
761-bounsweet
762-steenee
763-tsareena
765-oranguru
766-passimian
767-wimpod
768-golisopod
775-komala
776-turtonator
777-togedemaru
779-bruxish
780-drampa
781-dhelmise
782-jangmo-o
783-hakamo-o
784-kommo-o
794-buzzwole
795-pheromosa
796-xurkitree
797-celesteela
799-guzzlord
800-necrozma
801-magearna

**Comment by P3rf3ctXZer0** [comment]
@arata00 you could be a bit nicer can you show screenshots proof? Version number and minecraft forge release?

**Comment by arata00** [comment]
i am in minecraft 1.12.1 
forge: 14.22.0.2452
the pokecube is in the newest version
![sem titulo](https://user-images.githubusercontent.com/32281316/30858207-054f0300-a295-11e7-8793-f4420f2c5ebb.png)
but on the pokemake command I can not spawn it

**Comment by Thutmose** [comment]
I have that list of missing mobs located here: https://github.com/Thutmose/Pokecube-Models I will see about comparing the two and seeing if my list is missing some.

iirc the spawn command for Meloetta requires you to specify the form, try "/pokemake meloettaaria"

**Comment by arata00** [comment]
thanks
