### ISSUE TITLE
Pokemobs aren't making noises

### ISSUE THREAD

**Issue by Tortarus** [Thutmose/Pokecube#216]
#### Issue Description:
The pokemobs are not playing sounds. I have all of the sound to 100%, and turned subtitles on. The Subtitle is stating that a sound is supposed to be made/heard but nothing comes though. The pokedex cry button does the same thing, subtitle pops up that there is a sound being played but I can't hear anything. Attack sounds seem to work just fine, albeit just swishing noises. Hostile mobs do have have sounds, spiders make there hissing noises and zombies grown. 

During the initial loading I do see the sound initializer pop up for a second being loaded into the game.
And the pokemon center does play music.

This is in a custom minecraft 1.10.2 modpack with:
baubles
better builder wands
bibliocraft
botabia
chameleon
chisel
chisel & Bits
codechicken Core
codechicken lib
cofh core
connected textures mod
ender io
ender storage
ender core
extra utilities
extreme reactors 
fast leaf decay
Forge Multipart Cbe
Gravestone
inventory sorter
iron backpacks
iron chests
Journey Maps
Just enough Items
just enough resources 
light level overlay
mantle
pam's harvestcraft
pokecube server utilities
pokecube revival
pokecube core
pokecube mobs
redstone arsenal
storage drawers
thermal dynamics
thermal expansion
thermal foundation
thut wearables
thutcore
tinkers constructs
veinminer
waila
wireless redstone cbe
zero core

#### What happens:
No Pokemob sounds on pokemobs or pokedex.

#### What you expected to happen:
Sounds on pokemobs and the cry button in pokedex to make noises.

#### Steps to reproduce:

1. Run game
2. Listen

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core: 4.37.1
- Pokecube Revival (if applicable): 4.23.10
- Pokecube Mobs (if applicable): 2.14.6
- Minecraft: 1.10.2
- Forge: 12.18.3.2477

**Comment by Tortarus** [comment]
Decided to make a vid too:
https://www.youtube.com/watch?v=8-v7O_UmJsk&feature=youtu.be

**Comment by Thutmose** [comment]
I will look into this, I thought I had fixed the missing sounds issue for 1.10.2, maybe I didn't get it done

**Comment by Thutmose** [comment]
this will be fixed in next release, I apologize for the delay.

**Comment by Thutmose** [comment]
this should be fixed.
