### ISSUE TITLE
Entities already removed?

### ISSUE THREAD

**Issue by DeadSix27** [Thutmose/Pokecube#219]
MC Version: 1.12
Mod Versions:
`Pokecube Core-6.21.6.jar`
`Pokecube Mobs-2.14.11.jar`
`Pokecube Revival-6.11.4.jar`
Modlist: https://gist.github.com/DeadSix27/35ce97a26e9617e95c41e0071b6dd55f

My server keeps spamming:
`Tried to add entity pokecube_ml:**** but it was marked as removed already`
Do you have any idea what could cause this?

**Comment by Thutmose** [comment]
usually that is caused by something trying to load and then unload a chunk at wrong times, if you can find a way to make it reliably occur with just pokecube, I can try to get it fixed.  I noticed it happen once or twice during my testing, but could never make it happen reliably

**Comment by DeadSix27** [comment]
@Thutmose
I tried loading the mod with a bare minimum of other mods (inc. chickenchunks) and that issue I could not reproduce.

I suspected chickenchunks since I heard it unloads chunks more forcefully than normally but that didn't make a difference.. this will require a lot of time to narrow down. I will close this issue for now and reply once I've found the mod causing issues.
