### ISSUE TITLE
Rhyhorn mount bug

### ISSUE THREAD

**Issue by jochuan** [Thutmose/Pokecube#22]
#### Issue Description:
i cant mount on Rhyhorn and when i put the saddle on him the GUI of him doesn't work

#### What happens:

the GUI of Rhyhorn doesn't work when i put the saddle on him and i cant mount on him

#### What you expected to happen:

i expected that i could mount on him and the GUI would work normally

#### Steps to reproduce:

1.catch a Rhyhorn
2.put a saddle on him
3.try to right click on him

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:2.3.31
- Pokecube Revival (if applicable):2.2.16k
- Pokecube Mobs (if applicable):1.1.17
- Minecraft: 1.8.9
- Forge:11.15.1.1855

**Comment by Thutmose** [comment]
if a pokemob has a saddle, you need to shift right click it to access gui, this applies to all pokemobs, not just ridable ones (you can test this on a caterpie or something)

rhyhorn looks to be right under the edge of the size needed to ride a pokemob, so yours might be too small.

If his size is around 1.1 or more, he will be ridable

Try breeding a larger rhyhorn?

You can check the size by typing /pcedit while looking at it, it is the number called "scale", if that is less than about 1.1, it probably will not be ridable (for rhyhorn, needed number to ride is based on default size of the pokemob)

**Comment by jochuan** [comment]
thanks for the info
