### ISSUE TITLE
Cant select moves

### ISSUE THREAD

**Issue by iruleubeech** [Thutmose/Pokecube#220]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here.

#### What happens:
cant select pokemons moves. sometimes it will highlight, but then immediately go back t previous move

#### What you expected to happen:

be able to change move on command lol

#### Steps to reproduce:

1.summon pokemon
2.press up
3.nothing happens
...

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:6.21.5
- Pokecube Revival (if applicable):1.12.1
- Pokecube Mobs (if applicable):2.14.11
- Minecraft: 1.12.2
- Forge:1.12.2.

**Comment by Thutmose** [comment]
Fixed in 6.21.6 which was uploaded a few days ago
