### ISSUE TITLE
Mobs names scroll throught letters and numbers and look like a slot machine

### ISSUE THREAD

**Issue by specture18** [Thutmose/Pokecube#221]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here.

#### What happens:
same as title

#### What you expected to happen:
static names that i can read

#### Steps to reproduce:

1. ?
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:
- Pokecube Revival (if applicable):
- Pokecube Mobs (if applicable):
- Minecraft: 1.8.9
- Forge:

**Comment by Thutmose** [comment]
This is a feature, not a bug, try catching one.
