### ISSUE TITLE
How do i use tms

### ISSUE THREAD

**Issue by iruleubeech** [Thutmose/Pokecube#222]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here.

#### What you expected to happen:
it to go back to my pc (by chance how do i use TMs?)

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:
- Pokecube Revival (if applicable):
- Pokecube Mobs (if applicable):
- Minecraft: 1.12.2
- Forge:

**Comment by Thutmose** [comment]
On the death bug, if you can find out how to make it disappear every time, then I can get it fixed, without the steps to reproduce the bug though, I can't fix it.

for how to use TMs, place a TM machine touching a PC (there should be one in the pokecenters iirc) then place a blank TM in the slot, and look for the move you want to add (it checks your PC for moves your pokemobs know, or should have known at a lower lvl) press apply, now you have a TM for the move (trainers and merchants might also sell some TMs).

Then right click your pokemob with the TM, and it will learn it, the move will replace the selected move if you have 4 moves.

**Comment by Thutmose** [comment]
Can you also please include the version of everything in your minecraft, all mods, especially the pokecube related ones.

**Comment by Thutmose** [comment]
This video should explain how to use TMS

https://www.youtube.com/watch?v=rmbOcAzcU_A
