### ISSUE TITLE
please i can you add a feature that shows exactly what forge is needed

### ISSUE THREAD

**Issue by boxboygs** [Thutmose/Pokecube#225]
i need to know which forge exactly is needed for pokecube 1.12.2 cause the game is crashing and also for any future version for that matter

also why isnt there a pokeplayer for 1.12.2 also how do you use it

**Comment by Thutmose** [comment]
Please post the crash report if it is crashing for you.  I am waiting for someone else to offer to maintain pokeplayer, though the 1.12 version of it does work for 1.12.2

**Comment by boxboygs** [comment]
i have a crash report maybe its because im also using journeymap and biomesoplenty

The game crashed whilst initializing game
The game crashed whilst initializing game
Error: java.lang.IllegalAccessError: tried to access field net.minecraft.client.gui.GuiOverlayDebug.field_175242_a from class net.minecraftforge.client.GuiIngameForge$GuiOverlayDebugForge

**Comment by boxboygs** [comment]
[crash-2017-10-27_14.53.38-client.txt](https://github.com/Thutmose/Pokecube/files/1421953/crash-2017-10-27_14.53.38-client.txt)
[crash-2017-10-27_14.53.38-client.txt](https://github.com/Thutmose/Pokecube/files/1421959/crash-2017-10-27_14.53.38-client.txt)

**Comment by boxboygs** [comment]
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 10/27/17 2:53 PM
Description: Initializing game

java.lang.IllegalAccessError: tried to access field net.minecraft.client.gui.GuiOverlayDebug.field_175242_a from class net.minecraftforge.client.GuiIngameForge$GuiOverlayDebugForge
	at net.minecraftforge.client.GuiIngameForge$GuiOverlayDebugForge.<init>(GuiIngameForge.java:917)
	at net.minecraftforge.client.GuiIngameForge$GuiOverlayDebugForge.<init>(GuiIngameForge.java:911)
	at net.minecraftforge.client.GuiIngameForge.<init>(GuiIngameForge.java:101)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.client.GuiIngameForge$GuiOverlayDebugForge.<init>(GuiIngameForge.java:917)
	at net.minecraftforge.client.GuiIngameForge$GuiOverlayDebugForge.<init>(GuiIngameForge.java:911)
	at net.minecraftforge.client.GuiIngameForge.<init>(GuiIngameForge.java:101)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:536)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 264090696 bytes (251 MB) / 939524096 bytes (896 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.0.2492 19 mods loaded, 19 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version      | Source                                        | Signature                                |
	|:------ |:------------------- |:------------ |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft           | 1.12.2       | minecraft.jar                                 | None                                     |
	| UCHIJA | mcp                 | 9.42         | minecraft.jar                                 | None                                     |
	| UCHIJA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.0.2492.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge               | 14.23.0.2492 | forge-1.12.2-14.23.0.2492.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | mercurius_updater   | 1.0          | MercuriusUpdater-1.12.2.jar                   | None                                     |
	| UCHIJA | biomesoplenty       | 7.0.1.2301   | BiomesOPlenty-1.12.2-7.0.1.2301-universal.jar | None                                     |
	| UCHIJA | journeymap          | 1.12.2-5.5.1 | journeymap-1.12.2-5.5.1.jar                   | None                                     |
	| UCHIJA | thutcore            | 5.11.6       | thutcore-5.11.6.jar                           | None                                     |
	| UCHIJA | pceditmod           | 1.10.2-2.0.0 | Pokecube Core-6.23.2.jar                      | None                                     |
	| UCHIJA | pokecube            | 6.23.2       | Pokecube Core-6.23.2.jar                      | None                                     |
	| UCHIJA | pokecube_ml         | 0.1.0        | Pokecube Core-6.23.2.jar                      | None                                     |
	| UCHIJA | thut_wearables      | 3.1.2        | thut_wearables-3.1.2.jar                      | None                                     |
	| UCHIJA | thut_bling          | 2.0.1        | thut_bling-2.0.1.jar                          | None                                     |
	| UCHIJA | pokecube_adventures | 6.13.1       | Pokecube Revival-6.13.1.jar                   | None                                     |
	| UCHIJA | pokecube_mobs       | 4.1.1        | Pokecube Mobs-4.1.1.jar                       | None                                     |
	| UCHIJA | pokecube_moves      | @VERSION@    | Pokecube Mobs-4.1.1.jar                       | None                                     |
	| UCHIJA | pokecube_origin     | 4.1.1        | Pokecube Mobs-4.1.1.jar                       | None                                     |
	| UCHIJA | pokecube_compat     | 1.0          | Pokecube Revival-6.13.1.jar                   | None                                     |
	| UCHIJA | pokeplayer          | 1.12-1.0.0   | pokeplayer-1.12-1.0.0.jar                     | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '2.1.0 - Build 8.15.10.1840' Renderer: 'Intel(R) G45/G43 Express Chipset'
	Launched Version: 1.12.2-forge1.12.2-14.23.0.2492
	LWJGL: 2.9.4
	OpenGL: Intel(R) G45/G43 Express Chipset GL version 2.1.0 - Build 8.15.10.1840, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because EXT_framebuffer_object is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x Pentium(R) Dual-Core CPU E5800 @ 3.20GHz

**Comment by boxboygs** [comment]
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 10/27/17 2:53 PM
Description: Initializing game

java.lang.IllegalAccessError: tried to access field
net.minecraft.client.gui.GuiOverlayDebug.field_175242_a from class
net.minecraftforge.client.GuiIngameForge$GuiOverlayDebugForge
at
net.minecraftforge.client.GuiIngameForge$GuiOverlayDebugForge.(GuiIngameForge.java:917)
at
net.minecraftforge.client.GuiIngameForge$GuiOverlayDebugForge.(GuiIngameForge.java:911)
at net.minecraftforge.client.GuiIngameForge.(GuiIngameForge.java:101)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:536)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
at net.minecraft.client.main.Main.main(SourceFile:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
A detailed walkthrough of the error, its code path and all known details is
as follows:

-- Head --
Thread: Client thread
Stacktrace:
at
net.minecraftforge.client.GuiIngameForge$GuiOverlayDebugForge.(GuiIngameForge.java:917)
at
net.minecraftforge.client.GuiIngameForge$GuiOverlayDebugForge.(GuiIngameForge.java:911)
at net.minecraftforge.client.GuiIngameForge.(GuiIngameForge.java:101)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:536)

-- Initialization --
Details:
Stacktrace:
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
at net.minecraft.client.main.Main.main(SourceFile:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
Minecraft Version: 1.12.2
Operating System: Windows 7 (amd64) version 6.1
Java Version: 1.8.0_25, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle
Corporation
Memory: 264090696 bytes (251 MB) / 939524096 bytes (896 MB) up to
2147483648 bytes (2048 MB)
JVM Flags: 8 total;
-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
-Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC
-XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50
-XX:G1HeapRegionSize=16M
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP 9.42 Powered by Forge 14.23.0.2492 19 mods loaded, 19 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized
'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E'
= Errored

| State  | ID                  | Version      | Source
                       | Signature                                |
|:------ |:------------------- |:------------
|:---------------------------------------------
|:---------------------------------------- |
| UCHIJA | minecraft           | 1.12.2       | minecraft.jar
                       | None                                     |
| UCHIJA | mcp                 | 9.42         | minecraft.jar
                       | None                                     |
| UCHIJA | FML                 | 8.0.99.99    |
forge-1.12.2-14.23.0.2492.jar                 |
e3c3d50c7c986df74c645c0ac54639741c90a557 |
| UCHIJA | forge               | 14.23.0.2492 |
forge-1.12.2-14.23.0.2492.jar                 |
e3c3d50c7c986df74c645c0ac54639741c90a557 |
| UCHIJA | mercurius_updater   | 1.0          |
MercuriusUpdater-1.12.2.jar                   | None
                  |
| UCHIJA | biomesoplenty       | 7.0.1.2301   |
BiomesOPlenty-1.12.2-7.0.1.2301-universal.jar | None
                  |
| UCHIJA | journeymap          | 1.12.2-5.5.1 |
journeymap-1.12.2-5.5.1.jar                   | None
                  |
| UCHIJA | thutcore            | 5.11.6       | thutcore-5.11.6.jar
                       | None                                     |
| UCHIJA | pceditmod           | 1.10.2-2.0.0 | Pokecube
Core-6.23.2.jar                      | None
         |
| UCHIJA | pokecube            | 6.23.2       | Pokecube
Core-6.23.2.jar                      | None
         |
| UCHIJA | pokecube_ml         | 0.1.0        | Pokecube
Core-6.23.2.jar                      | None
         |
| UCHIJA | thut_wearables      | 3.1.2        |
thut_wearables-3.1.2.jar                      | None
                  |
| UCHIJA | thut_bling          | 2.0.1        | thut_bling-2.0.1.jar
                       | None                                     |
| UCHIJA | pokecube_adventures | 6.13.1       | Pokecube
Revival-6.13.1.jar                   | None
         |
| UCHIJA | pokecube_mobs       | 4.1.1        | Pokecube
Mobs-4.1.1.jar                       | None
         |
| UCHIJA | pokecube_moves      | @VERSION@    | Pokecube
Mobs-4.1.1.jar                       | None
         |
| UCHIJA | pokecube_origin     | 4.1.1        | Pokecube
Mobs-4.1.1.jar                       | None
         |
| UCHIJA | pokecube_compat     | 1.0          | Pokecube
Revival-6.13.1.jar                   | None
         |
| UCHIJA | pokeplayer          | 1.12-1.0.0   |
pokeplayer-1.12-1.0.0.jar                     | None
                  |

Loaded coremods (and transformers):
GL info: ' Vendor: 'Intel' Version: '2.1.0 - Build 8.15.10.1840'
Renderer: 'Intel(R) G45/G43 Express Chipset'
Launched Version: 1.12.2-forge1.12.2-14.23.0.2492
LWJGL: 2.9.4
OpenGL: Intel(R) G45/G43 Express Chipset GL version 2.1.0 - Build
8.15.10.1840, Intel
GL Caps: Using GL 1.3 multitexturing.

Using GL 1.3 texture combiners.
Using framebuffer objects because EXT_framebuffer_object is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs:
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 2x Pentium(R) Dual-Core CPU E5800 @ 3.20GHz

**Comment by Thutmose** [comment]
neither of those appear to be from pokecube, I have been testing on forge 2503, but if those are not from pokecube, I am not sure if that information will be helpful for you
