### ISSUE TITLE
how do z-moves work

### ISSUE THREAD

**Issue by boxboygs** [Thutmose/Pokecube#227]
i tried poketm command and found out that zmoves are there now i collected gigavolt havoc and hydro vortex and tried it on my washrotom neither worked even though it had shockwav and hydropump so i spawned one with the zmoves  but they have no animatioon (thats ok) but the atk power is only 1

**Comment by Thutmose** [comment]
zmoves do not currently work, they are in the database, but are not otherwise implemented
