### ISSUE TITLE
Mega Slowbro

### ISSUE THREAD

**Issue by Heoz** [Thutmose/Pokecube#229]
![32149274-fbd44c7c-bd01-11e7-867f-09ea0c6b89c4](https://user-images.githubusercontent.com/6887621/32273802-44f0d804-bf04-11e7-9e25-bd0ed0bd68c1.png) Can anyone fix model i can't it doesn't even look like this

**Comment by Thutmose** [comment]
This issue belongs in https://github.com/Thutmose/Pokecube-Models
