### ISSUE TITLE
errors on the log and poketrainer without textures

### ISSUE THREAD

**Issue by jochuan** [Thutmose/Pokecube#23]
#### Issue Description:
errors on the log and sometimes i find a poketrainer without texture

#### What happens:
i am getting errors on the log telling that a trainer texture failed to load and sometimes i find poketrainer without texture(black and purple)
https://gist.github.com/jochuan/6a8e6f33b6dcb3ad3ae09393a1a80e2b

#### What you expected to happen:

i expected them to have normal skins

#### Steps to reproduce:

1.enter your game
2.look for trainers
3.find one without texture
...

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:2.3.31
- Pokecube Revival (if applicable):2.2.16k
- Pokecube Mobs (if applicable):1.1.17
- Minecraft: 1.8.9
- Forge:1855

**Comment by Thutmose** [comment]
Ya, I need to get a texture done for him, or at least make it use a default texture when non is found.

**Comment by Thutmose** [comment]
Fixed this, I made it so it has defaults if a trainer type is registered and no texture if given.
