### ISSUE TITLE
Crash when throwing repeatcube

### ISSUE THREAD

**Issue by st753m** [Thutmose/Pokecube#231]
#### Issue Description:

After throwing a repeatcube at a wild pokemob, the game crashes to desktop while the repeatcube is in midair just before hitting the target.

This occurs both with species I haven't captured before, and species I have.  Occurred 5 times out of 5 that I tested it.

After restarting minecraft and loading my world again, the pokemob is in the cube, and gives the usual message that it was caught successfully, after which it acts like a normal pokemob.   

[crash-2017-11-19_10.03.43-server.txt](https://github.com/Thutmose/Pokecube/files/1485670/crash-2017-11-19_10.03.43-server.txt)

#### Steps to reproduce:

1. Throw a repeatcube at a weakened pokemob

#### Affected Versions (Do *not* use "latest"):

- Pokecube Core: 6.23.6
- Pokecube Revival (if applicable): 6.13.3
- Pokecube Mobs (if applicable): 4.1.2
- Minecraft: 1.12.2
- Forge: tested on both 14.23.0.2512 and 14.23.0.2546

**Comment by Thutmose** [comment]
I will have this fixed shortly, hopefully I will be getting a release out for it tomorrow
