### ISSUE TITLE
Tm's not applying

### ISSUE THREAD

**Issue by freen37** [Thutmose/Pokecube#232]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here.

#### What happens:
I could be simply clueless of mechanics but....  While trying to train Tm's to pokemobs, nothing happens. Use tm table correctly, get new tm, put pokemob on ground, toggle arrow keys to select move to replace, right click pokemob with new tm (does not matter which pokemob or tm), open pokemob inventory, tm is not applied

#### What you expected to happen:

expect tm to overwrite selected move

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core: 6.23.6
- Pokecube Revival (if applicable): 6.13.3
- Pokecube Mobs (if applicable): 4.1.2
- Minecraft: 1.12.2
- Forge: 14.23.0.2503

**Comment by Thutmose** [comment]
what move are you trying to teach to what pokemob? TMs are applying correctly in my testing, could the move you are trying to teach not be learnable by that mob?

**Comment by Thutmose** [comment]
Not had any response on this, and cannot replicate on any version on my end, so closing this issue.
