### ISSUE TITLE
Pokemobs visually change gender 

### ISSUE THREAD

**Issue by CorentG** [Thutmose/Pokecube#233]
#### Issue Description:
If one pokemob is interacted with (right click on him, sending him out), the others pokemobs of the same species that are already out will get the same gender than the new that got interacted with.

#### What happens:
The gender visually change.

#### What you expected to happen:
If i send a female it's should not turn other pokemobs of the same species into females if they are male.

#### Steps to reproduce:

1.Give yourself 2 pokemobs of the same species : a male and a female.
2.Send the male before, and then the female
3.the male will turn VISUALLY into the female (the contrary works too)
...

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:6.24.0
- Pokecube Revival (if applicable):6.13.4
- Pokecube Mobs (if applicable):4.1.2
- Minecraft: 1.12.2
- Forge:14.23.0.2550

PS : i've got another bug and i'm gonna make another Issue for this.

**Comment by Thutmose** [comment]
Hmm, seems like I may have a bug somewhere in my optimizations for speeding up rendering then, I will look into this, I assume this is client side only? as in the males/females are the correct genders when recalled and sent back out?

**Comment by Thutmose** [comment]
I have this fixed for next release now, I will be rather busy for the rest of the week, so might not be able to get it uploaded.  I will also try to look into the shoulder issue for when I do get time for releasing.

**Comment by CorentG** [comment]
Ok nice.

**Comment by Thutmose** [comment]
should be fixed in 6.24.1
