### ISSUE TITLE
Evolved pokemobs on shoulder use the wrong texture

### ISSUE THREAD

**Issue by CorentG** [Thutmose/Pokecube#234]
#### Issue Description:
Apparently, if you take a Raichu (example) and use a stick to make him go on your shoulder, he will use the texture of Pichu (only when on shoulder).

#### What happens:
A pokemobs with an evolution, and who can go on shoulder, will use the texture of the first pokemob in it's evolutionary line. 
(Raichu will use the texture of Pichu for example)

#### What you expected to happen:
The evolved pokemob i put on my shoulder use the texture of him, instead of the first one in his evolutionary line.

#### Steps to reproduce:

1.Give one pokemob that is an evolved form, who can get on your shoulder
2.When on your shoulder it should use the texture of his first pokemob in it's evolutionary line
3.It go back to normal when he get out from your shoulder
...

____
#### Affected Versions (Do *not* use "latest"):

Pokecube Core:6.24.0
Pokecube Revival (if applicable):6.13.4
Pokecube Mobs (if applicable):4.1.2
Minecraft: 1.12.2
Forge:14.23.0.2550

**Comment by Thutmose** [comment]
hmm, not sure why this would be happening, I will look into it.

**Comment by Thutmose** [comment]
Also got a fix in for this, looking for a couple extra related bugs, then I will try to get the release pushed shortly.

**Comment by Thutmose** [comment]
should be fixed in 6.24.1
