### ISSUE TITLE
support for LuckPerms

### ISSUE THREAD

**Issue by smmmadden** [Thutmose/Pokecube#236]
I've tried a few permission mods and ThutPerms seems to be the only one that I can get working with this mod.  I tried PEX and spent today trying to get LuckPerms working with no success.  All the permission nodes I had previously were added to LP but when I logged in as a player and and OP'd admin, none of the perms were available.  Can you add the support for this?
LuckPerms-Sponge-4.0.35.jar
SpongeForge-1.12.2-2529-7.0.0-BETA-2748.jar
Waterfall-Build62.jar

Other mods looking for this to support: 
![image](https://user-images.githubusercontent.com/10309346/33536367-a7ff7d96-d882-11e7-9d8b-84951c9874c9.png)
Thanks -Steve

**Comment by Thutmose** [comment]
Any permissions for command use should be handled by the permissions plugin, does LP have any information about modifying permissions for modded commands?

**Comment by Thutmose** [comment]
I tested with latest spongeforge and LP, and permissions work fine.

I tested:
`/luckperms user Thutmose permission set pokecube.command.poketm true`
then did /poketm rest, and recieved a rest TM, so the permissions are working as intended.

**Comment by smmmadden** [comment]
thanks for testing.  I should have been more specific.  The problem with the permissions is I've assigned users to "default" group.  Added all the permissions for typical users there.  Each user should not need the same perm node but should be getting perms from those defined in the default group.  So while the permissions can be added to the group or user, in the game the permissions are not working - even for my own id which I've set to "admins" group with parent of "default".  I set the same perms as thut.perms but the behavior is not the same.  I experienced similar behavior using PEX as well which led me to believe that perhaps there is no permission check for LuckPerms or PEX to use it?  Thanks!

**Comment by Thutmose** [comment]
thutperms uses a different permissions system from the other two (class based instead of command based), the perms will be different for LP or PEX than for thutperms

So long as the per-user settings for LP work (as did in my testing) then they should work in any group, try testing with vanilla command permissions first? maybe you are doing something wrongly in the setup?
