### ISSUE TITLE
[improvement] call back to pokeball pokemons that are set to follow you when you exit the nether

### ISSUE THREAD

**Issue by jochuan** [Thutmose/Pokecube#24]
when you exit the nether the pokemon stays there but would be good if when you exit the nether the pokemon enters in the pokeball so you don't need to enter the nether again to get it back
-sorry for my bad english

**Comment by Thutmose** [comment]
hmm, I can try to do something like that, If I can find an event that triggers before the player leaves the nether, then I can do that.  If the event only triggers after, then it will be more difficult.
