### ISSUE TITLE
AnimationEditor.jar do not want to launch.

### ISSUE THREAD

**Issue by CorentG** [Thutmose/Pokecube#241]
#### Issue Description:
The AnimationEditor.jar (the application to edit moves) don't seem to launch.

#### What happens:
I'm doing exactly what i have done in the past (this : https://github.com/Thutmose/Pokecube/wiki/Animating-Moves ) except that it do not want to launch. I guess it is outdated.

#### What you expected to happen:
The application launch and i can simply  edit the animations.

#### Steps to reproduce:

1.Place the AnimationEditor.jar at config/pokecube/database
2.click on it
3.It do not launch
...

____
#### Affected Versions (Do *not* use "latest"):

(I think the AnimationEditor.jar need an update so i don't think it's the fault of core,mobs or revival, but i can be wrong)

- Pokecube Core:6.31.1
- Pokecube Revival (if applicable):6.13.17
- Pokecube Mobs (if applicable):4.2.3
- Minecraft: 1.12.2
- Forge:14.23.1.2581

**Comment by CorentG** [comment]
By the way, i have found an error in your latest core,mobs,revival or whatever updated the animations, at the line 2112 there is a " and a : that are inverted, so a lot of move doesnt appear.

(Edit : nevermind, you fixed it, i havent saw the last pokecubemobs when i found this)

**Comment by Thutmose** [comment]
ya, I had noticed that error as well when the animations all stopped working :D

**Comment by CorentG** [comment]
Can you tell me if the AnimationEditor need an update ? (Just to know if it's normal that it doesnt work)

**Comment by Thutmose** [comment]
I will check it

**Comment by Thutmose** [comment]
it seems to be working as far as I can tell, I used the moves.json and animations.json from here:


https://github.com/Thutmose/Pokecube-Mobs/tree/master/src/main/resources/assets/pokecube_mobs/database

**Comment by CorentG** [comment]
Arf, i found out why it does not launched... java was somehow deleted from my computer... You can close th issue ._. (it work well after installing java)

**Comment by P3rf3ctXZer0** [comment]
Wait seriouslly? That happened to me too! ... any idea why your Java was deleted?

**Comment by CorentG** [comment]
Probably when i tried to fix some "heartbeat lags" or something like that, i unistalled it and there is a chance that i forgot to re install it.

**Comment by CorentG** [comment]
Thutmose, there is also a small bug, when i select for example the particle "misc", the color will only result in the type's color. If i modify a normal move and i put light_blue as a color, it will not use it. This is not a bug with animationeditor.jar, it's probably the fault of whatever mod take care of the animations.

**Comment by Thutmose** [comment]
I will look into this and fix it, I bet I messed up somewhere when I fixed some of the animations not working

**Comment by Thutmose** [comment]
I found that some animation types were ignoring the specific colours, that will be fixed in the next release

**Comment by Thutmose** [comment]
closing this issue since it is no longer a problem.
