### ISSUE TITLE
Error in imagen Pokemon

### ISSUE THREAD

**Issue by manugetsu1990** [Thutmose/Pokecube#242]
After playing several days an error begins that lowers the fps to 1 and the image of the pokemon are seen with crosses of colors

![2017-12-25_18 14 05](https://user-images.githubusercontent.com/34843426/34343006-687ddea8-e9a1-11e7-8399-248e24e747fd.png)

- Pokecube Core: 6.31.3
- Pokecube Revival (if applicable): 6.13.18
- Pokecube Mobs (if applicable): 4.2.4
- Minecraft: 1.12.2
- Forge: 14.23.1.2552

**Comment by Thutmose** [comment]
This "bug" has occured every year on the 25th of december for the past 5 or 6 years, it will go away when the calender changes to say 26th of december

**Comment by Thutmose** [comment]
I will see about ensuring that turning particles off makes it stop for next year though.

**Comment by manugetsu1990** [comment]
THX !!! HAPPY NEW YEAR!

**Comment by Thutmose** [comment]
Happy new year
