### ISSUE TITLE
double registration errors 

### ISSUE THREAD

**Issue by smmmadden** [Thutmose/Pokecube#244]
Adding issue to backlog to address how registrations  are done. Version(s) reported in:
Pokecube Core: 6.31.4
Pokecube Revival: 6.13.18
Pokecube Mobs: 4.2.5
Minecraft: 1.12.2
SpongeAPI: 7.0.0-SNAPSHOT-963ff06
SpongeForge: 1.12.2-2555-7.0.0-BETA-2783
Minecraft Forge: 14.23.1.2582
Thut Core: 5.13.0.c
Thut Bling: 2.0.2
Thut Wearables 3.1.4
OptiFine 1.12.2_HD_U_C7
LuckPerms-Sponge 4.0.62
JourneyMap 1.12.2-5.5.2
Hwyla 1.8.23-B38_1.12
FastLeafDecay: 14
Dynmap-2.6-beta-1-forge-1.12
ShulkerBox: 1.3.0
TotalEconomy: 1.7.1
WorldEdit-Forge-MC1.12-6.1.8-dist
Nucleus-1.2.0-PR5-S7.0-MC1.12.2

Thutmose: These here can also be ignored, I left the double registration message in as a reminder to get around to cleaning up that section at some point, it doesn't actually have any effect ingame. The database moves thing is just an info.

Dec 26, 2017 11:10:21 PM pokecube.core.interfaces.PokecubeMod log
INFO: Registered 648 Database Moves
[23:10:22] [Server thread/INFO] [STDERR]: [pokecube.core.PokecubeCore:registerPokemonByClass:687]: Double Registration for Arceus
[23:10:23] [Server thread/INFO] [STDERR]: [pokecube.core.PokecubeCore:registerPokemonByClass:687]: Double Registration for Genesect

**Comment by Thutmose** [comment]
This one should be fixed in the next version, I am re-writing a large section of the database/pokemob registration, and it should also deal with this one.

**Comment by Thutmose** [comment]
this is fixed one of the latest releases of core.
