### ISSUE TITLE
registering pokeAdv when should be pokeadv

### ISSUE THREAD

**Issue by smmmadden** [Thutmose/Pokecube#247]
Adding issue to backlog to address how commands are registered to account for case sensitive names. Version(s) reported in:
Pokecube Core: 6.31.4
Pokecube Revival: 6.13.18
Pokecube Mobs: 4.2.5
Minecraft: 1.12.2
SpongeAPI: 7.0.0-SNAPSHOT-963ff06
SpongeForge: 1.12.2-2555-7.0.0-BETA-2783
Minecraft Forge: 14.23.1.2582
Thut Core: 5.13.0.c
Thut Bling: 2.0.2
Thut Wearables 3.1.4
OptiFine 1.12.2_HD_U_C7
LuckPerms-Sponge 4.0.62
JourneyMap 1.12.2-5.5.2
Hwyla 1.8.23-B38_1.12
FastLeafDecay: 14
Dynmap-2.6-beta-1-forge-1.12
ShulkerBox: 1.3.0
TotalEconomy: 1.7.1
WorldEdit-Forge-MC1.12-6.1.8-dist
Nucleus-1.2.0-PR5-S7.0-MC1.12.2

Thutmose: These ones are added by sponge, forge and vanilla have no case checking on command names, so I registered for various case combinations:

[23:10:33] [Server thread/WARN] [Sponge]: Plugin 'pokecube_adventures' is attempting to register command 'pokeAdv' with an uppercase character - adjusting to 'pokeadv'
[23:10:33] [Server thread/WARN] [Sponge]: Plugin 'pokecube_adventures' is attempting to register command 'pokeAdv' with an uppercase character - adjusting to 'pokeadv'

**Comment by Thutmose** [comment]
this one I am going to label as wontfix and close, this is just sponge thinking my mod is a pluggin, and should conform to their own standards.  The command is already registered as "pokeadv":

https://github.com/Thutmose/Pokecube/blob/1.10/Pokecube%20Addons/src/main/java/pokecube/adventures/comands/GeneralCommands.java#L44-L45

it is registered as both, as vanilla specifically allows for this, and supports case senstive command names.
