### ISSUE TITLE
corrupt moves on startup?

### ISSUE THREAD

**Issue by smmmadden** [Thutmose/Pokecube#249]
Adding issue to backlog to address the possible corrupt pokecube on startup:
Pokecube Core: 6.31.4
Pokecube Revival: 6.13.18
Pokecube Mobs: 4.2.5
Minecraft: 1.12.2
SpongeAPI: 7.0.0-SNAPSHOT-963ff06
SpongeForge: 1.12.2-2555-7.0.0-BETA-2783
Minecraft Forge: 14.23.1.2582
Thut Core: 5.13.0.c
Thut Bling: 2.0.2
Thut Wearables 3.1.4
OptiFine 1.12.2_HD_U_C7
LuckPerms-Sponge 4.0.62
JourneyMap 1.12.2-5.5.2
Hwyla 1.8.23-B38_1.12
FastLeafDecay: 14
Dynmap-2.6-beta-1-forge-1.12
ShulkerBox: 1.3.0
TotalEconomy: 1.7.1
WorldEdit-Forge-MC1.12-6.1.8-dist
Nucleus-1.2.0-PR5-S7.0-MC1.12.2

During the startup process, where all the pokecube/mobs are being loaded, I noticed there are also several which appear to be corrupt given the error shown and special characters unlike all the others.
![image](https://user-images.githubusercontent.com/10309346/34428397-671cea10-ec1a-11e7-8310-28013d77c7c1.png)
![image](https://user-images.githubusercontent.com/10309346/34428399-6bdaf204-ec1a-11e7-9d15-23db65c55803.png)

**Comment by Thutmose** [comment]
that should be fixed in the very latest versions, it was a corruped move entry in the move database

**Comment by Thutmose** [comment]
this should have been fixed in one of the latest releases of Pokecube Mobs
