### ISSUE TITLE
 I can not feed the pokemon with a saddle

### ISSUE THREAD

**Issue by manugetsu1990** [Thutmose/Pokecube#253]
Like ago to remove the mount to a pokemon or like ago to open the inventory of the pokemon with the mount set?

- Pokecube Core:
- Pokecube Revival (if applicable):
- Pokecube Mobs (if applicable):
- Minecraft: 1.8.9
- Forge:

**Comment by Thutmose** [comment]
try sneaking while right clicking it

**Comment by manugetsu1990** [comment]
Thx very thx GOOD MOOD!!
