### ISSUE TITLE
Moves animations ignore color.

### ISSUE THREAD

**Issue by CorentG** [Thutmose/Pokecube#254]
#### Issue Description:
I remember i told you this on another issue, but i put that here in case you forgot. 

#### What happens:
In the animation editor, if i change for example Thunderbolt, and i use the particle "misc" then set the color to light_blue, it will not use light_blue, instead, it's gonna use the Type's color.

#### What you expected to happen:
The color i put is used, instead of the Type's one.

#### Steps to reproduce:

1.Use the animation editor, then choose for example thunderbolt
2.With the "misc" particle set the color to light-blue 
3.It will use the type's color instead of light blue.
...

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:6.35.3
- Pokecube Revival (if applicable):6.14.9
- Pokecube Mobs (if applicable):4.5.1
- Minecraft: 1.12.2
- Forge:14.23.1.2581

**Comment by Thutmose** [comment]
Hmm, I thought I had fixed this, I will look into it some more

**Comment by Thutmose** [comment]
I found the issue, I had forgotten to call the method that fixes this.  It should be fixed in the next release of Pokecube Core

**Comment by Thutmose** [comment]
uploading Pokecube Core 6.35.4, it should be fixed in it, I tested with thunderbolt, and it had some light blue particles after the fix.
