### ISSUE TITLE
texture bug

### ISSUE THREAD

**Issue by arata00** [Thutmose/Pokecube#258]
these two pokemons are bigger than they should

![ads](https://user-images.githubusercontent.com/32281316/35158450-3c1ba86e-fd1e-11e7-8965-3688fd796d7c.png)

**Comment by P3rf3ctXZer0** [comment]
Um its just genetics not a bug.

**Comment by Thutmose** [comment]
genetics increase size of hitbox as well, so it isn't a genetics issue.

**Comment by Thutmose** [comment]
please repost this issue in https://github.com/Thutmose/Pokecube-Mobs or https://github.com/Thutmose/Pokecube-Models, it belongs in one of those two repositoried.
