### ISSUE TITLE
Pokeplayer: Can't transform into megas

### ISSUE THREAD

**Issue by 1matto** [Thutmose/Pokecube#261]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here.

#### What happens:
Can't transform into a mega pokemon

#### What you expected to happen:
Transform into a mega pokemon

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:1.12.2.6.36.4
- Pokecube Revival (if applicable):1.12.2.6.14.2
- Pokecube Mobs (if applicable):1.12.2.4.6.1
- Minecraft: 1.12.2
- Forge:14.23.2.2611

**Comment by Thutmose** [comment]
Please re-make this issue on the pokeplayer issue tracker: https://github.com/Thutmose/Pokeplayer/issues
