### ISSUE TITLE
compatatability issue with epic seige

### ISSUE THREAD

**Issue by Nathan22211** [Thutmose/Pokecube#262]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. from looking at the crash report it seems to be a AI issue with your mod and the only one I added recently to my modpack I'm working on is epic siege.

https://pastebin.com/FDHfAmcq

#### Steps to reproduce:

1. have epic siege, pokecube core and mobs installed (it might be infernal mobs or vamprisum as well so check that)

2. set it to night

3. load the area around spawn until it crashes
...

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core: 6.35.7
- Pokecube Revival (if applicable): 6.14.9
- Pokecube Mobs (if applicable): 4,5,3
- Minecraft: 1.12.2
- Forge: 14.23.1.2610

**Comment by Nathan22211** [comment]
ok it's not epic siege and pokecube causing it it's epic siege and vampirism. I just tested it

**Comment by Thutmose** [comment]
I have seen a very similar crash occur with only vanilla, it crashed when a cow was trying to path somewhere, I wonder if the extra pathing done by epic siege, plus the extra mobs in pokecube and vampirism is making a vanilla crash occur more often

**Comment by Nathan22211** [comment]
yeah it seems that all 3 of them cause it if you use just epic siege and vampirism it doesn't happen but I haven't tested in other dimensions

**Comment by Nathan22211** [comment]
it might be on epic siege's end. report the bug to him/her and he/she might be able to figure it out

**Comment by Nathan22211** [comment]
wait you mean epic siege can crash on it's own?

**Comment by Thutmose** [comment]
Vanilla can crash on its own from that same issue, is what I found out, very rarely, but it can

**Comment by Thutmose** [comment]
I found a spot in the pathing code that can result in this occuring, it will be fixed in next version to be released. also turning off thutcore's multithreadedAI fixes it.
