### ISSUE TITLE
Non-op players can't open pokécenter doors

### ISSUE THREAD

**Issue by rehv** [Thutmose/Pokecube#263]
#### Issue Description:
If I set myself as OP in my server, no one can open the pokécenter doors in villages. If I grant them OP, they can open those. So, I'm guessing I'm missing a config somewhere where I can set that everyone can open these doors regardless of OP level.

#### What happens:
Can't open pokécenter doors as non-op player if there is at least one op player configured.

#### What you expected to happen:
Being able to adjust a setting where everyone can open the doors regardless of OP, without having to set a Permissions plugin, if possible.

#### Steps to reproduce:
1. Grant OP to a player.
2. Ask other players to open pokécenter doors.

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core: pokecube-core-1.12.2-6.36.6
- Pokecube Revival (if applicable): pokecube-revival-1.12.2-6.14.14
- Pokecube Mobs (if applicable): pokecube-mobs-1.12.2-4.6.1
- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.2.2611-universal

**Comment by Thutmose** [comment]
this sounds like vanilla spawn protection, try disabling that and see if it still occurs

**Comment by rehv** [comment]
Oh -_-

Friends didn't say the problem was just with spawn Pokécenter and honestly I didn't remember spawn protection disabled buttons... Well, thanks!

**Comment by Thutmose** [comment]
no problem, this is a rather common problem, as most people don't notice the spawn protection until it comes to a button or inventory :D
