### ISSUE TITLE
Crash Ticking Entity

### ISSUE THREAD

**Issue by rehv** [Thutmose/Pokecube#264]
#### Issue Description:
Hi again, I had these crashes in different days with the same issue... First one was a player attacking a Dhelmise with Yawn, if the report is correct. Second one I was using Feraligatr with Crunch to defend me while I AFK'ed. The server is hosted @ home, the first crash was through a tunnel (ngrok.io ~ 80-100 ms) the second one through my lan (3-10 ms).

[Crash1](https://pastebin.com/Q1Rh8GhD)
[Crash2](https://pastebin.com/L6JWqS9i)

#### What happens:
N/A

#### What you expected to happen:
N/A

#### Steps to reproduce:
N/A

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core: pokecube-core-1.12.2-6.36.6
- Pokecube Revival (if applicable): pokecube-revival-1.12.2-6.14.14
- Pokecube Mobs (if applicable): pokecube-mobs-1.12.2-4.6.1
- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.2.2611-universal

**Comment by rehv** [comment]
Hi there, had 5 more crashes related to PokéCube and TickingEntity, 3 of them with Wishiwashi Schools and 2 with Wailord, so I guess there's definitely something funky going on with these. Anyway I can disable them entirely for the time being?

[Crash 1](https://pastebin.com/n07E6M21)
[Crash 2](https://pastebin.com/8yi0x8Hk)
[Crash 3](https://pastebin.com/m2cPHAVe)
[Crash 4](https://pastebin.com/GUKVcZBa)
[Crash 5](https://pastebin.com/DPxUpz8X)

PS: Same versions as the OP.

**Comment by Thutmose** [comment]
I found a temporary workaround for this, I apologize for not posting it here earlier, I have been rather busy with some class work, I forgot to look through the issues to post this:

In thutcore.cfg, set multiThreadedAI to false, it fixes this crash

**Comment by Thutmose** [comment]
this crash won't happen anymore after the next version, instead it will give a warning in a log.
