### ISSUE TITLE
gastly hitbox is too big

### ISSUE THREAD

**Issue by jochuan** [Thutmose/Pokecube#27]
#### Issue Description:

gastly hitbox is too big

### What happens:

gastly hitbox is too big and because of that sometimes he can't fight enemies that are on the ground

#### What you expected to happen:

he should be able to fight normally

#### Steps to reproduce:

1.catch a gastly
2.use it to fight other pokemons that are little and are on the ground
3.or fight a onix with it
...

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:2.3.43
- Pokecube Revival (if applicable):2.2.17
- Pokecube Mobs (if applicable):1.1.24
- Minecraft: 1.8.9
- Forge:1902

**Comment by Thutmose** [comment]
Hmm, that shouldn't be that hitbox is too big, rather is an issue with the other pokemobs, I will look into it.

Large hitbox should make it easier to hit things, as hit is based on when hitboxes intersect.

Onix, Gyarados, etc are known to have some issues with being hit though.

**Comment by jochuan** [comment]
i thought that was the hitbox because sometimes he can't fight pokemons that are next to a block on the same height

**Comment by jochuan** [comment]
https://github.com/Thutmose/Pokecube/issues/49#issuecomment-227732671

**Comment by jochuan** [comment]
duplicate
