### ISSUE TITLE
Diamond Block Legends not working

### ISSUE THREAD

**Issue by MetalicoMetal** [Thutmose/Pokecube#272]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here.

#### What happens:
Legendarys that need the diamond block dont spawn

#### What you expected to happen:
The legendary spawning or telling you that you dont have the requirements to spawn it

#### Steps to reproduce:

1.Place the diamond block on any biome that can have legends like Registeel or Kyogre
2.Shift Right click them with your pokedex/pokewatch
3.Nothing Happens.
...

____
#### Affected Versions (Do *not* use "latest"):
Pokecube Core:6.36.6
Pokecube Revival (if applicable):6.14.14
Pokecube Mobs (if applicable):4.6.1
Minecraft: 1.12.2
Forge:14.23.1.2594

**Comment by Thutmose** [comment]
this is the one closed in https://github.com/Thutmose/Pokecube/commit/1eb41ee188dc0adda91d0782a8a445a2d492cad7
