### ISSUE TITLE
Disable players being damaged by pokemons.

### ISSUE THREAD

**Issue by Fandalf89** [Thutmose/Pokecube#275]
#### Issue Description:
Note: I don't know how to turn off the wild pokemon attacking my character in Minecraft.

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:none
- Pokecube Revival (if applicable): 1.5.25.2
- Minecraft: 1.7.10
- Forge: forge-1.7.10-10.13.4.1558

**Comment by Thutmose** [comment]
Check configs, there are some pokemobToPlayer damage ratio options in pokecube.cfg, set those to 0 and they won't hurt you

**Comment by Thutmose** [comment]
Oh wait, this was for 1.7.10, no way there, that version hasn't been supported for 2 or 3 years
