### ISSUE TITLE
 I can not evolve to vulpix alola please help

### ISSUE THREAD

**Issue by manugetsu1990** [Thutmose/Pokecube#277]
#### What happens:

I can not evolve to vulpix alola? 

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core: 6.25.1
- Pokecube Revival (if applicable): 6.13.7
- Pokecube Mobs (if applicable): 4.1.3
- Minecraft: 1.12.2
- Forge :1.12.2-14.23.1.2555

**Comment by Thutmose** [comment]
please fill out the steps to reproduce section

**Comment by Thutmose** [comment]
Tested evolving vulpix alola, it works fine, so I assume you were doing something wrong on your end, please see this video for how to find out how things evolve:

https://youtu.be/UijGJnbAXBQ
