### ISSUE TITLE
pokemons should use berries that are on their inventory[improvement]

### ISSUE THREAD

**Issue by jochuan** [Thutmose/Pokecube#28]
pokemons should use berries that are on the inventory of them when they need for example when they are with low health they would search for any orany berries in their inventory to use

**Comment by Thutmose** [comment]
This seems like it would be rather OP, as you could then put stacks of oran berries and never have your pokemob faint, it wouldn't be good for balance.

**Comment by jochuan** [comment]
Maybe the Pokémon would only use the berry that is on the main slot like on the pokemons games

**Comment by Thutmose** [comment]
they currently do, if they have a berry in their main slot, they will eat it if they need to.

**Comment by jochuan** [comment]
Oh Didnt notice that. Thanks for the info
