### ISSUE TITLE
Trainers pokecube duplicate after server restart.

### ISSUE THREAD

**Issue by Karagra** [Thutmose/Pokecube#281]
Trainers pokecube duplicate after server restart. Seems to have gone from one to three.
Forge 1.2.2  2655
Spongeforge 1.12.2-2655-7.1.0-BETA-3064 
Latest everything pokecube

**Comment by Thutmose** [comment]
does this happen every time? and can you get it to happen on single player?

**Comment by Thutmose** [comment]
I suspect this is a sponge/pokecubes related issue, I will get back to this after sponge makes its changes related to pokecubes.

**Comment by Karagra** [comment]
At this time you are right everything seems to be pointing to Spongeforge.

**Comment by Thutmose** [comment]
Please test this with Spongeforge 3074+. see if it fixes the issue for you, and if so, close this issue.

**Comment by Skyloq** [comment]
Hi ! I have a sponge serveur too and i haven't your problem.

My versions :

Pokecube Core: pokecube-core-1.12.2-6.36.12
Pokecube Revival (if applicable): pokecube-revival-1.12.2-6.14.19
Pokecube Mobs (if applicable): pokecube-mobs-1.12.2-4.9.0
Minecraft: 1.12.2
Sponge : spongeforge-1.12.2-2611-7.1.0-BETA-2970.jar

**Comment by Karagra** [comment]
Yeah the bug has been fixed as recently.

**Comment by Thutmose** [comment]
cosing issue since this is fixed in latest versions
