### ISSUE TITLE
Trainers pokemons not getting moves

### ISSUE THREAD

**Issue by Karagra** [Thutmose/Pokecube#282]
When setting up Trainer Npcs, setting up a new pokemon will not have a default list of moves.
![capture](https://user-images.githubusercontent.com/18022024/39659547-96357550-4ff8-11e8-83ff-d7ecc2d32a52.PNG)

**Comment by Thutmose** [comment]
They should get moves when they actually try to use the pokemobs, but for convinence, I will add a button to auto-fill the moves.
