### ISSUE TITLE
1.12 Optifine issues

### ISSUE THREAD

**Issue by Namkcaws** [Thutmose/Pokecube#283]
The usage of the latest Optifine w/ 1.12 Pokecube seems to crash any world made shortly after loading it.

The world will start up....and proptly crash after a few seconds. Thought it might be conflicts with other mods at first, but nope, Pokecube is the issue. Yes, of course, I added Optifne last like I'm supposed to, so that wasn't it.

[hs_err_pid9144.log](https://github.com/Thutmose/Pokecube/files/1977754/hs_err_pid9144.log)

- Pokecube Core: 1.12.2-6.36.7
- Pokecube Revival (if applicable): 1.12.2-6.14.15
- Pokecube Mobs (if applicable):1.12.2-4.7.0
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.3.2655

**Comment by Thutmose** [comment]
that log doesn't implicate pokecube in any way whatsoever, can you please in include all versions of everything you have in the mods folder, so I can test this on my end?

**Comment by Thutmose** [comment]
![image](https://user-images.githubusercontent.com/2363472/39675341-c0c3cb70-5127-11e8-9af7-ba6d684946c1.png)
Optifine seems to be working fine for me

**Comment by Namkcaws** [comment]
Oh, forgot to include which Optifine it was. My bad.


It was OptiFine_1.12.2_HD_U_D1

**Comment by Namkcaws** [comment]
Also, those were the only 5 mods used when producing that crash & report.

**Comment by smmmadden** [comment]
Are you sure you have all the mods you need?  I'm using OptiFine 1.12.2 D2 version and was using D1 without any issues with Forge 2655.  Your thread dump indicates a problem with the JVM you are using or the parameters provided with it.
Did you add the thut_core mod as well?  Please provide the logs showing the startup of the server itself which will show what you have installed and if there are issues for it.

**Comment by P3rf3ctXZer0** [comment]
I have seen problems like this on Intel chipsets i3 older gen ... What is your graphics card and model and cpu chipset model and ghz? Also if you don't mind me asking how much memory are you dedicating to minecraft and how much memory is installed on your personal computer. Also what is your operating system and is it x64 ready?

**Comment by Namkcaws** [comment]
@smmmadden Whoops, meant 5 mods. Yeah I did.

I DID just update my Java runtime....it's now at version 1.8.0_171. But I don't remember if that was before or after redoing the crash.

**Comment by Namkcaws** [comment]
@P3rf3ctXZer0 Considering I've never had a problem w/ Pokecube versions before, I've no idea why any of that's relevant. Although I can say I've had the memory upped to 3GB for some time, so that part shouldn't be the problem.



Ok I just tested Pokecube w/o Optifine again, and it worked fine. So there IS undoubtedly an issue w/ Optifine and Pokecube, bc every time I add Optifine, it crashes.

**Comment by Namkcaws** [comment]
.....Ok, so it's an Optifine issue....welp. This is embarassing.

**Comment by Thutmose** [comment]
no worries, it can be hard to tell what side issues like this one are on, especially when the crash logs don't implicate anything

**Comment by smmmadden** [comment]
Curious about something @Namkcaws - did you upgrade Java for the JDK or JRE?  Personally, I download the latest JDK and point to the JRE folder for that release.
![image](https://user-images.githubusercontent.com/10309346/39884087-a655bcd0-5456-11e8-9de4-4cc6eeb596ea.png)
