### ISSUE TITLE
AtomicStryker's Ruins Mod Causing Random Crashes

### ISSUE THREAD

**Issue by BlueMeta** [Thutmose/Pokecube#288]
#### Issue Description:
AtomicStryker's Ruins mod compat is outdated _(Maybe)_ and causes crashes when generating ruins.
[Crash Report](https://www.hastebin.com/tapuvixafi.sql)

#### What happens:
Randomly crashes when some ruins generates.

#### What you expected to happen:
Not crashing when generating ruins.

#### Steps to reproduce:

1.Get Ruins mod by AtomicStryker
2.Run the game
3.Go to any map and try to find an structure.
**POOSH!** Your game has been crashed by trying to generating a structure

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core: 6.36.16
- Pokecube Revival (if applicable): 6.14.21
- Pokecube Mobs (if applicable): 4.9.1
- Minecraft: 1.12.2
- Forge: 14.23.3.2655

**Comment by Thutmose** [comment]
oops, seems the code refactor didn't reach all the compat classes, i will have this fixed shortly.

**Comment by Thutmose** [comment]
fix is uploaded as pokecube revival 6.14.22
