### ISSUE TITLE
monsters aren't spawning

### ISSUE THREAD

**Issue by jochuan** [Thutmose/Pokecube#29]
#### Issue Description:
monsters aren't spawning
#### What happens:
monsters dont spawn at the night and in caves now only rarely i can see one of them. In the nether i still can see ghasts and some pigmans but i only found one wither skeleton in a nether fortress

#### What you expected to happen:
the monsters should spawn normally because i didn't get them to not spawn in the config

#### Steps to reproduce:

1.wait for night or enter in a cave
2.look for monsters

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:2.3.43
- Pokecube Revival (if applicable):2.2.17
- Pokecube Mobs (if applicable):1.1.24
- Minecraft: 1.8.9
- Forge:1902

**Comment by jochuan** [comment]
i found out that this is affecting golem spawns because i made a golem farm and only 3 golems spawned in 3 minecraft days but non-hostile mobs like cows and pigs still spawn, i think that this bug only affects neutral and hostile mobs

**Comment by jochuan** [comment]
looks like this bug has been fixed in 1.9.4 the monsters are spawning normally now maybe it was thaumcraft together with pokecube that were reducing the vanilla spawns

**Comment by Thutmose** [comment]
Possibly, I haven't done anything that should have affected spawn rates for vanilla mobs between 1.8.9 and 1.9.4, so it was probably either a vanilla bug in 1.8.9, or a strange mod interaction

**Comment by jochuan** [comment]
I think that this should be closed for now since thaumcraft didnt updated and the monsters are spawning normaly
