### ISSUE TITLE
Number of pokemobs reduced

### ISSUE THREAD

**Issue by Skyloq** [Thutmose/Pokecube#291]
Hi, it's me again ^^

#### What happens:

Since you updated the Core of pokecube, I can edit the .json files without any problem but once in play, I go from a hundred pokemons (about 300) to a maximum of 10-15 around me ...

I tried without adding the file pokemobs_spawns_new.json and the result is the same

[pokecube.zip](https://github.com/Thutmose/Pokecube/files/2020435/pokecube.zip)

#### Steps to reproduce:

No
____
#### Affected Versions (Do *not* use "latest"):

![image](https://user-images.githubusercontent.com/39385087/40280569-cef272ee-5c55-11e8-9d60-20173f17611f.png)

- Minecraft: 1.1.12
- Forge:  forge-1.12.2-14.23.3.2655

**Comment by Thutmose** [comment]
what result do you get from running /pokecount?

**Comment by Skyloq** [comment]
with a 30 sec interval :

![image](https://user-images.githubusercontent.com/39385087/40281226-13027110-5c5f-11e8-9189-cb28b7cea65f.png)

**Comment by Thutmose** [comment]
That is normal, try moving 30 blocks away and re-run the command

**Comment by Skyloq** [comment]
![image](https://user-images.githubusercontent.com/39385087/40281545-9f771246-5c63-11e8-8239-9d7e3359a319.png)

I executed the command every 10 sec while moving and there is clearly less

**Comment by Thutmose** [comment]
It takes a few seconds to spawn, so long as that says 10 or so after you have be in the same spot for 5-10s, then it is working as intended

**Comment by Skyloq** [comment]
![image](https://user-images.githubusercontent.com/39385087/40281925-88db44fe-5c67-11e8-862d-bce6cae7ad21.png)

maybe, but the spawn was much faster with an older version

Command executed at the same rate as the last time

Edit : 

![image](https://user-images.githubusercontent.com/39385087/40281945-be74623a-5c67-11e8-9771-4f24a70f97ac.png)

Second Edit :

Unlike the new version, I run though I see the pokemons appear

**Comment by Thutmose** [comment]
Hmm, it could be a result of some tweaks done for server load reductions

**Comment by Skyloq** [comment]
Do you think you can fix that?

**Comment by Thutmose** [comment]
I will do more testing to see if it needs a "fix" or just more general tweaks.

**Comment by Skyloq** [comment]
Thank you, keep me informed ;)

**Comment by Thutmose** [comment]
I will add a config option for how often the spawn code runs, before it was once a tick, now it is once every 20 ticks, the config will let you get it back to how it was, I will probably be unable to upload the fixes until Wednesday.

**Comment by Thutmose** [comment]
the fix for this should be in the version of pokecube core I uploaded shortly ago
