### ISSUE TITLE
Suggestions : Opaque Block -> Non-Opaque block

### ISSUE THREAD

**Issue by Glopeur** [Thutmose/Pokecube#292]
<h1>Issue :</h1>

I made a custom 3d model for a block in the mod, but when I place the block it do an x-ray issue.

![2018-05-20_21 47 23](https://user-images.githubusercontent.com/35874673/40283005-e4ce4724-5c77-11e8-850a-ca61234cf6e0.png)

This issue is from Minecraft himself, because the block is Opaque, the game don't render hidden sides of blocks who are beside Opaque one.

***
<h1>Suggestion :</h1>

My suggestion is to change Pokecube's block to make them Non-Opaque.
This will allow to set textures who support transparency (like beacon) / custom model without this issue.

In general purpose it's to allow more customization for client's ressourcepack.

***

<h6>Actual Version :</h6>

<h6>- pokecube-core-1.12.2-6.36.23</h6>
<h6>- pokecube-mobs-1.12.2-4.9.2</h6>
<h6>- pokecube-revival-1.12.2-6.14.24</h6>

**Comment by Thutmose** [comment]
I shall do this for next release, it will probably be Wednesday or so before I have the release uploaded though, I will close this issue once it is up

**Comment by Glopeur** [comment]
If you want the custom model to try out I can provide it

**Comment by Thutmose** [comment]
Sure, I can see about testing the model to see if it works, my main pc won't have internet till Wednesday, so I won't be able to do much more than testing bug fixes on my end

**Comment by Glopeur** [comment]
Here is the ressourcepack with the model + textures inside (it replace the Pokecenter block)

[glopeur_3d_pokecube.zip](https://github.com/Thutmose/Pokecube/files/2020702/glopeur_3d_pokecube.zip)

**Comment by Thutmose** [comment]
Fixed for when I have internet to release:
https://i.imgur.com/9reKXXD.png

**Comment by Glopeur** [comment]
God damn you're a genius 👍

**Comment by Thutmose** [comment]
This should be in the current versions
