### ISSUE TITLE
Pokemons traductions ( French )

### ISSUE THREAD

**Issue by Skyloq** [Thutmose/Pokecube#297]
Hey, I'm not used to using this site to share / add code and I translated the 999 pokemons into French.

Here is the file:

[EU_fr.zip](https://github.com/Thutmose/Pokecube/files/2065422/EU_fr.zip)

Once the update done, it will be enough to have his game in French to pass the name of pokemon in French or will it be necessary to make a manipulation?

**Comment by Thutmose** [comment]
what do you mean by pass the name of the pokemon in French? the lang file should change the name of the pokemon to the french name in all of the major mod guis, and in any of the messages in chat

**Comment by Skyloq** [comment]
I did not speak well :p , that's what I thought.

**Comment by Thutmose** [comment]
it ends up like this:
![image](https://user-images.githubusercontent.com/2363472/40887181-85398d28-6712-11e8-97d9-b787ea44e8de.png)
![image](https://user-images.githubusercontent.com/2363472/40887192-ad132c50-6712-11e8-9983-350481df939c.png)

**Comment by Thutmose** [comment]
this lang will be in pokecube mobs 4.9.3, which should be uploaded shortly.

If you want to translate any of the other lang files, feel free to do so, and I will update them as well
