### ISSUE TITLE
Oran berries don't heal when using with hand

### ISSUE THREAD

**Issue by wilzorve** [Thutmose/Pokecube#298]
#### Issue Description:
Berries Oran are broken.
![2018-06-08_23 51 21 oran berry broke](https://user-images.githubusercontent.com/40075237/41183226-dcf58326-6b79-11e8-9ee6-5e8c07797d04.png)

#### What happens:
Oran berries are hold as held items; Berries don't heal your injured pokemob

#### What you expected to happen:
Oran berries must be consume and give + 10 HP to your injured pokemobs.

#### Steps to reproduce:

1.Take your injured pokemob out of his cube
2.Put oran berries in right hand
3.Right click your pokemobs with it (Spam click doesn't matter)

____
#### Affected Versions (Do *not* use "latest"):
Pokecuke pack 3.21.0.zip (twitch launcher)

**Comment by Thutmose** [comment]
this bug has been fixed for a while, it only occurs because that modpack hasn't been updated since it was fixed.
