### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Skyloq** [Thutmose/Pokecube#299]
#### Issue Description

Hey !

The server was working well with the pokecube-core-1.12.2-6.37.0 version
but with the .1 and the .2 I have this message:

![image](https://user-images.githubusercontent.com/39385087/41229683-368630d4-6d7d-11e8-9cb1-d5dfa470eb71.png)

____
#### Affected Versions (Do *not* use "latest"):

![image](https://user-images.githubusercontent.com/39385087/41229738-6cb0f1b2-6d7d-11e8-9c50-2706f9a83bb6.png)

EDIT : 
I will try to update forge and close my request if it works

**Comment by Thutmose** [comment]
Read the line directly above the red highlighted section, it says what the problem is, you need to update forge
