### ISSUE TITLE
internal server crash when shift clicking with healing table (1.9.4)

### ISSUE THREAD

**Issue by Cat-McCatface** [Thutmose/Pokecube#30]
#### Issue Description:
Healing table doesn't work as intended. Better than previous 1.9.x builds crashing during/after player selecting first pokemob though.

#### What happens:
internal server crashes
java.lang.StackOverflowError: Updating screen events
log: http://pastebin.com/ePyfKx0M

#### What you expected to happen:
objects (pokeball) transferred over to "healing table"

#### Steps to reproduce:

1. find healing table and open ui
2. shift click pokemob
3. profit (or in this case, crash)
...

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core: 3.1.1
- Pokecube Revival (if applicable): 3.1.1
- Pokecube Mobs (if applicable): 2.1.1
- Minecraft: 1.9.4
- Forge: 1.9.4-12.17.0.1935

**Comment by Thutmose** [comment]
I will look into that asap.

**Comment by Thutmose** [comment]
Hopefully fixed this in 3.1.2, if it still persists, feel free to re-open this issue.
