### ISSUE TITLE
Severe stutter in various circumstances when using TC6 Thaumometer

### ISSUE THREAD

**Issue by AeiouEnigma** [Thutmose/Pokecube#303]
#### Issue Description:

Using Thaumcraft's Thaumometer when various Pokemobs are within its frame results in severe frame rate reduction. I haven't tested this with many Pokemobs, but the issue is present with Boldore and Roggenrola. The issue is not present when looking at a Geodude.

#### What happens:

Using Pokecube together with Thaumcraft 6 makes it difficult to use Thaumcraft's Thaumometer to scan things in the world. Severe frame rate drops are nearly unavoidable when near a large variety of pokemobs, as more often than not some pokemobs should be expected to be within the Thaumometer's view.

#### What you expected to happen:

I expected that Pokemobs existing within the Thaumometer's frame would not cause any performance issues.

#### Steps to reproduce:

1. Hold Thaumometer in hand
2. Orient field of view such that an affected Pokemob is within the purple Thaumometer window
3. Experience severe frame rate drop

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core: 1.12.2-6.37.2
- Pokecube Revival (if applicable): 1.12.2-6.14.25
- Pokecube Mobs (if applicable): 1.12.2-4.9.4
- Thaumcraft: 1.12.2-6.1.BETA16
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.4.2703

**Comment by captcookie** [comment]
this is a known issue about thaum in large modpacks with or without pokecube

**Comment by luke-bravenboer** [comment]
This was an issue on TC's side, and it has now been fixed in [BETA17](https://minecraft.curseforge.com/projects/thaumcraft/files/2578520)

**Comment by Thutmose** [comment]
closing this issue then
