### ISSUE TITLE
Trainer XML files not working

### ISSUE THREAD

**Issue by AGiLE-EaGLE1994** [Thutmose/Pokecube#304]
#### Issue Description:
For some reason, specifying custom trainer classes with XML files doesn't work.

#### What happens:
When I tell the config not to force databases and add a trainer type xml to a resource pack or in the extra configs option, it doesn't show up.

- Pokecube Core: 1.12.2-6.37.2
- Pokecube Revival (if applicable): 1.12.2-6.14.25
- Pokecube Mobs (if applicable):1.12.2-4.9.4 (Modified to remove Gen 3,4,5,6, and 7 Pokemon)
- Minecraft: 1.8.9
- Forge:1.12.2-forge1.12.2-14.23.4.2708
Also a custom Pokemob resource pack I created.

**Comment by Thutmose** [comment]
they seem to be working find as far as I can tell, I tested removing all but bug catchers and nitwits, and that worked fine, and then I added DERPA and DERPB, and they worked fine as well.

Did you make sure to set forceDatabase to false in pokecube_adventures.cfg?
