### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Skyloq** [Thutmose/Pokecube#305]
Hi, I met a little problem: I have a pokemon that uses the bide attack but does not inflict any damage.

Also, when my pokemon is in aggressive mode (a super convenient mode for the farm and xp), my pokemon uses the attacks he wants. Is there a way to make him use the attacks that he is ordered?

____
#### Affected Versions (Do *not* use "latest"):

If we use an old version of Pokecube Core, it's because in the following versions, there is a compatibility problem with our version of Forge and the server does not start anymore. The problem is that you can not put a newer version of forge on OMGserv (there is the 2655 but it does not work with Sponge).

Pokecube mod :

![image](https://user-images.githubusercontent.com/39385087/42723396-13eff1aa-875d-11e8-9905-4a4b87805a76.png)

- Minecraft: 1.1.12
- Forge: forge-1.12.2-14.23.2.2611-universal

All the mods and plugins : 

![image](https://user-images.githubusercontent.com/39385087/42723407-4a9086a2-875d-11e8-9747-b976a5775d30.png)

**Comment by Thutmose** [comment]
when in guard mode, there is no way to tell the pokemob what attack to use, it will use whatever it feels like using.

it shouldn't ever decide to use a non-damaging attack, as it is supposed to pick whatever it thinks will kill the enemy the quickest, I will look into it to see what is going on, can you include what pokemob it is, and what all attacks it has, as well as the pokemob it is trying to kill?

**Comment by Skyloq** [comment]
Seedot : Attack : Bide and Harden

And I tried on several pokemon like bidoof or Rattata

By the way I do not know why but there are really too many of these two pokemons

Thank you for your work :D

**Comment by Thutmose** [comment]
harden never does any damage, I will need to look into bide to see why it isn't working, though if the targets are not hitting it, bide does no damage, so unless your seedot is attacked, it has no damage dealing moves.

try teaching your seedot a conventional damage dealing move, that should fix your problem.

**Comment by Skyloq** [comment]
I have another problem: I use NPCs (villagers) to shop. The problem is that the pnj provoke the players in pokemon combat each time one approaches them. Do you have a command or a means to prevent the fighting or to remove their pokeballs?

EDIT : Can the legendary spawner several times?

**Comment by Thutmose** [comment]
natural spawning legends can spawn multiple times, villagers shouldn't agress you unless you anger them first

**Comment by Skyloq** [comment]
https://youtu.be/WTbtOuUlvw8 @Thutmose
