### ISSUE TITLE
crash when player fights pokemobs or explores (1.9.4)

### ISSUE THREAD

**Issue by Cat-McCatface** [Thutmose/Pokecube#31]
#### Issue Description:
Normally the player uses pokemobs to fight. Let's see what happens if a player uses minecraft logic and fights mobs themselves. A separate but similar crash (almost identical log) can happen without player input because of entity scripting (?).

#### What happens:
hang leading to crash. "Trainers" seem killable without any care given (unless need to try with nothing in hand).

Description: Ticking entity
java.lang.ClassCastException: net.minecraft.entity.player.EntityPlayerMP cannot be cast to pokecube.core.interfaces.IPokemob

log: http://pastebin.com/ET4zxQXb

Initially thought to be issue with gamemode or as result of world gen. wiped test world and changed to survival to test resulting in crash (again). Tried again intentionally not interacting with wild pokemobs resulting in same crash.

#### What you expected to happen:
Combat with pokemob or some sort of protection error (to only allow pokemob-pokemob fighting).

#### Steps to reproduce:

1. deploy a pokemob... or not
2. go kenshiro on a pokemob in wild (punch it a couple times)
3. crash is random amount of time
...
Other crash resulted from walking around pokemobs in non-combat exploration.

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core: 3.1.2
- Pokecube Revival (if applicable): 3.1.2
- Pokecube Mobs (if applicable): 2.1.1
- Minecraft: 1.9.4
- Forge: 1935

**Comment by Thutmose** [comment]
Fixed in 3.1.3, should be on curseforge shortly.
