### ISSUE TITLE
General Mod Mob Blacklist

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Thutmose/Pokecube#315]
#### Feature being requested

General Blacklist to prevent pokemobs from being allowed to target certain creatures and mod monsters. This should include wildcard support such as mymod:creature*

#### Details on feature/suggestion

players would be unable to use pokemobs to to target - auto target or agro against certain mobs

![2018-08-14 12_24_26-window](https://user-images.githubusercontent.com/10351221/44107474-1c12e3b0-9fbd-11e8-8da8-f58e08c3e7b4.jpg)

**Comment by Thutmose** [comment]
This should be released now
