### ISSUE TITLE
Wearable will disappear when player dies

### ISSUE THREAD

**Issue by Philosyang** [Thutmose/Pokecube#317]
#### Issue Description:

You lose all of your wearables in your pokecube inventory if you had put them in your pokecube inventory and you die.

#### What happens:

You lose all of your wearables, they disappear.

#### What you expected to happen:

You don't lose any of them.

#### Steps to reproduce:

1. Put a bag, a watch or anything that can be fitted into the pokecube inventory slots.
![image](https://user-images.githubusercontent.com/24841393/44632373-36aad800-a93f-11e8-8e14-54a9a7657151.png)

2. Kill yourself with any method.

3. Your wearables will **not** exist neither in the pokecube inventory slots nor the PC.

____
#### Affected Versions:

- Pokecube AIO: 1.12.2-1.6.17
- Minecraft: 1.12.2
- Forge: 14.23.4.2705

**Comment by Thutmose** [comment]
I cannot replicate this, they go to my PC when I die

**Comment by Thutmose** [comment]
is there anything showing up in logs when this happens for you? also can you send a zip of your config folder, maybe it is something in there that is different from my testing environment

**Comment by Philosyang** [comment]
I found the problem.

I made **/gamerule keepInventory true** for my server (this also applies to singleplayer).
When **KeepInventory** is true, you kill yourself, then your wearables that were in pokecube inventory slots will no longer exist neither in the pokecube inventory slots nor the PC.

**Comment by Thutmose** [comment]
ahh, I see, that gamerule being true must prevent the drops from occuring, the wearables are not saved over when the player dies, so if nothing drops, they disappear

**Comment by Thutmose** [comment]
I will look into fixes for this, I suepct I will need to do something differently if that gamerule is on...

**Comment by Philosyang** [comment]
Awesome dev!

**Comment by Thutmose** [comment]
this should be fixed in Pokecube AIO: 1.12.2-1.6.18, please test it whenever it is available, and close this issue if it is fixed.

**Comment by Philosyang** [comment]
Unfortunately, it didn't work for me.
/gamerule KeepInventory true, /kill, wearables still disappear, and nothing in my PC.

**Comment by Thutmose** [comment]
![image](https://user-images.githubusercontent.com/2363472/44822317-77695200-abc8-11e8-8b4b-ba3022dad74d.png)

these stay in my inventory when I run /kill with this modset:
![image](https://user-images.githubusercontent.com/2363472/44822330-9831a780-abc8-11e8-9b53-3d98610c54f7.png)

**Comment by Philosyang** [comment]
My fault, I added the 1.6.18 into my mods folder and deleted 1.6.18 instead of 1.6.16

Problem solved.
