### ISSUE TITLE
crash when player uses ball to obtain wild pokemob

### ISSUE THREAD

**Issue by Cat-McCatface** [Thutmose/Pokecube#32]
#### Issue Description:
Player is unable to capture new pokemobs from wild. Not sure it affects trainer npcs since shouldn't be able to win [steal?] their pokemobs.

#### What happens:
Animation to trap mob happens followed by crash

#### What you expected to happen:
Player should be rewarded (?) a new mob

#### Steps to reproduce:

1.find a low level mob (14 health in test case)
2.throw a ball until successfully captured
3.wait
...
log: http://pastebin.com/pMdcmMJu
____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core: 3.1.4
- Pokecube Revival (if applicable): 3.1.2
- Pokecube Mobs (if applicable): 2.1.1
- Minecraft: 1.9.4
- Forge: 1954

**Comment by Thutmose** [comment]
I will look into that asap, I am in the middle of some major internal changes, so it might take a while.

**Comment by Thutmose** [comment]
Uploaded fix for this crash in Pokecube Core 3.2.0, it should be on curse shortly.
