### ISSUE TITLE
Trainer dies but gives out emeralds

### ISSUE THREAD

**Issue by Philosyang** [Thutmose/Pokecube#321]
#### Issue Description:
Trainer dies but gives out emeralds.

#### What happens:
Trainer dies but gives out emeralds.

#### What you expected to happen:
Trainer dies and no emeralds are given.

#### Steps to reproduce:

1. Come to a trainer.
2. The trainer wants to battle.
3. The trainer sends out a pokemon.
4. Slay the trainer.
5. Get emeralds for winning.

![image](https://user-images.githubusercontent.com/24841393/46504573-e6ebe600-c7f3-11e8-8c78-e6bb202ef3a2.png)

____
#### Affected Versions:

- Pokecube AIO: [1.6.16](https://minecraft.curseforge.com/projects/pokecube-aoi/files/2608566) (5.19.7 in game)
- Minecraft: 1.12.2
- Forge: 14.23.4.2705

**Comment by Thutmose** [comment]
Dead trainers shouldn't be giving emeralds, I will see if I can find out why that message is being sent.

If you kill the trainer, you shouldn't get anything from them.

**Comment by Philosyang** [comment]
It's probably because the pokemon disappears/dies after their trainer dies.

**Comment by Thutmose** [comment]
This should be fixed for the next release
