### ISSUE TITLE
[Bug] The world spawn point's pokecenter cannot be removed 

### ISSUE THREAD

**Issue by CorentG** [Thutmose/Pokecube#325]
#### Issue Description:
The "doSpawnBuilding" setting do not remove the pokecenter at spawn when creating a new world.

#### What happens:
doSpawnBuilding:false doesnt seem to work.

#### What you expected to happen:
When on "false", the pokecenter shouldn't spawn.

#### Steps to reproduce:

1.Set doSpawnBuilding to false
2.Create new world
3.It still spawn
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in, if using AIO, list that instead.

- Pokecube Core:6.41.23
- Pokecube Revival (if applicable):6.16.18
- Pokecube Mobs (if applicable):4.13.1
- Minecraft: 1.12.2
- Forge:14.23.5.2811

**Comment by Thutmose** [comment]
this will be fixed for next release, seems when I updated the spawn building code, I forgot to re-implement this config.
