### ISSUE TITLE
[Bug] Attacks buffs/debuffs doesn't works

### ISSUE THREAD

**Issue by CorentG** [Thutmose/Pokecube#329]
#### Issue Description:
The attacks buffs/debuff that happen after using moves like Calm Mind, Harden or Growl doesn't work. The moves say "Pokemon's Defense rose" but defense hasnt rose.

#### What happens:
Attacks buffs/debuffs are not used when calculating damage.

#### What you expected to happen:
If the defense rosed once, physical moves should deal less damage.

#### Steps to reproduce:

1.Get metapod.
2.Get hit
3.Now get hit again but after using harden
4.Nothing change
...
____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in, if using AIO, list that instead.

- Pokecube Core:6.41.23
- Pokecube Revival (if applicable):6.16.18
- Pokecube Mobs (if applicable):4.13.1
- Minecraft: 1.12.2
- Forge:14.23.5.2811

**Comment by Thutmose** [comment]
I tested with growl, tailwhip, swordsdance while using tackle, and they seemed to work as intended

**Comment by CorentG** [comment]
Ok, so i just tested, and it seems that defense and maybe special defense doesnt work, sword dance works, but harden and defense curl doesnt. I used a l.10 snorlax vs a l.100 magikarp, and even if i used 6 times defense curl the snorlax still take the same amount of damage (he have 58 hp, and after 3 hits of tackle from magikarp, he keep getting to 25 hp, even with defense curl used six times). However i make snorlax use swords dance on the magikarp, and the damage was higher. Also, i tested if the enemy have defense lowered and i use tackle, and yes it works. This means that defense/defense special that has rosed doesnt work.
(edit : defense special doesnt work, exactly like defense)

**Comment by Thutmose** [comment]
Ok, I will look into this
