### ISSUE TITLE
Shiny pokemon and other skins are not working in custom NPC (and crash in lastest version)

### ISSUE THREAD

**Issue by Javi185** [Thutmose/Pokecube#333]
Issue Description:
Shiny skin of pokemon with the custom NPC is not working when you apply it

What happens:
When you change the skin of the pokemon with the custom NPC to make it shiny, the original skin still comes out, it does not change

What you expected to happen:
I think it doesn't detect skin change even if you change it

Steps to reproduce:
Create a NPC with the custom NPC mod
Select someone pokemob model
In the menu of the NPC change it the skin for the shiny version
...
Affected Versions (Do not use "latest"): Replace with a list of all mods you have in.
Pokecube AIO: 1.16.1
Minecraft: 1.12.2
Forge: lastest numbers are 2838

Add that with the -CustomNPCs_1.12.2- (01Oct19) - if you change a pokemon skin directly crash

**Comment by Thutmose** [comment]
Please move this issue to here: https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/issues
