### ISSUE TITLE
[Suggestion] Have Scyther evolve into Kleavor with Flint instead of Netherite Scrap

### ISSUE THREAD

**Issue by PhotonTheNecrozma** [Thutmose/Pokecube#338]
I think it would make a lot of sense as most people got their Black Augurites from defeating a bunch of Gravelers and you do get flint from gravel, plus flint looks a lot like the black augurites too.

**Comment by Thutmose** [comment]
this should be in next update, also next time make the issue in the actually used repo: https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/issues
