### ISSUE TITLE
Optifine - Support

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Thutmose/Pokecube#34]
#### Issue Description:

Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here.
#### What happens:

Needs Support for optifine.
#### Steps to reproduce:

1.
2.
3.
...

---
#### Affected Versions (Do _not_ use "latest"):
- Pokecube Core:
- Pokecube Revival (if applicable):
- Pokecube Mobs (if applicable):
- Minecraft: 1.8.9
- Forge:

**Comment by jochuan** [comment]
what do you mean by support ?

**Comment by schindlershadow** [comment]
works fine for me

**Comment by jochuan** [comment]
you are probaly talking about this https://github.com/Thutmose/Pokecube/issues/33 ?

**Comment by TechDweebGaming** [comment]
I use optifine just fine. If this is causing you to crash, please give me a crash report, otherwise I can't do anything.

**Comment by jochuan** [comment]
this still is a issue ?
