### ISSUE TITLE
[1.9.4] Evolving Pokémon Makes Them Disappear.

### ISSUE THREAD

**Issue by XileForce** [Thutmose/Pokecube#35]
Evolving a Pokémon just makes it permanently disappear. 

Forge 1965
Pokecube core 3.24
Pokecube mobs 2.12
Pokecube revival 3.22

**Comment by schindlershadow** [comment]
Modpack: Infinix test

**Comment by Thutmose** [comment]
Fixed for next release, working on other issues now, will close this when I upload fix to curse.

**Comment by Thutmose** [comment]
Uploaded the fix for this in http://minecraft.curseforge.com/projects/pokecube-core/files/2309016 (may still be a few minutes before it is available)
