### ISSUE TITLE
[1.9.4] nether portal dupe  

### ISSUE THREAD

**Issue by XileForce** [Thutmose/Pokecube#36]
Pushing a Pokémon through a nether portal will return the Pokémon to your hand as well a reporting it through thus making a duplicate.

Steps to reproduce:
1. Throw Pokémon out.
2. Push it into nether portal
3. Pokémon will return to your inventory
4. Now go through portal and recall the duplicate.

Forge 1965
Pokecube core 3.24
Pokecube mobs 2.12
Pokecube revival 3.22

**Comment by schindlershadow** [comment]
Modpack: Infinix test

**Comment by Thutmose** [comment]
Temporary fix for this will be to prevent pokemobs from passing through nether portals.  Will have that fix in the next release, I will work in a more "proper" fix later, as this bug will probably also affect end portals and modded portals.

**Comment by Thutmose** [comment]
Uploaded the temporary fix for this in http://minecraft.curseforge.com/projects/pokecube-core/files/2309016 (may still be a few minutes before it is available)

I will leave this issue open as a reminder incase it does occur with other portal types.

**Comment by 2piradians** [comment]
This issue also applies to End portals. Similar method of pushing them into the portal, then recalling the Pokemon, and proceeding into the End and finding a copy of the Pokemon.

Version 1.9.4/1.10

**Comment by Thutmose** [comment]
Found cause and fixed now :D
