### ISSUE TITLE
Stealing pokemon in trading table

### ISSUE THREAD

**Issue by schindlershadow** [Thutmose/Pokecube#37]
#### Issue Description:
Modpack: Infinix test

#### What happens:

breaking a trading table that someone put a pokemon in will disconnect the player that put the item and but both the table and the pokemon drop. The player that broke the table can now take the pokemon. if that pokemon is sent to the pc it returns to the original owner's pc.

#### What you expected to happen:

table will break, pokemon is returned to players inventory.

#### Steps to reproduce:

1. player one put pokemon for trade in trading table
2. player two breaks table with pickaxe
3. player two picks up pokecube with pokemon in it
...

____
#### Affected Versions (Do *not* use "latest"):

Forge 1965
Pokecube core 3.24
Pokecube mobs 2.12
Pokecube revival 3.22
Minecraft: 1.9.4

**Comment by Thutmose** [comment]
doesn't the trading table take 5 minutes to break?

**Comment by Thutmose** [comment]
Testing a fix for this, will uploaded update shortly if it works.

**Comment by Thutmose** [comment]
Fixed this crash, I made it send the pokemobs to the PC, as that was the simplest solution to implement.
