### ISSUE TITLE
Revive deletes pokemon

### ISSUE THREAD

**Issue by schindlershadow** [Thutmose/Pokecube#38]
#### Issue Description:
Modpack: Infinix test

#### What happens:

Using a revive deletes Pokemon

#### What you expected to happen:

Pokemon gets revived

#### Steps to reproduce:

1. have a fainted Pokemon
2. use revive on it
...

____
#### Affected Versions (Do *not* use "latest"):

Forge 1965
Pokecube core 3.24
Pokecube mobs 2.12
Pokecube revival 3.22
Minecraft: 1.9.4

**Comment by Thutmose** [comment]
Hmm, let me see if 1.9.4 recipes are different than 1.8.9 ones...

**Comment by Thutmose** [comment]
Uploaded the fix for this in http://minecraft.curseforge.com/projects/pokecube-core/files/2309016 (may still be a few minutes before it is available)
