### ISSUE TITLE
No Pokemon sounds

### ISSUE THREAD

**Issue by schindlershadow** [Thutmose/Pokecube#39]
#### Issue Description:
Modpack: Infinix test

#### What happens:

random vanilla mincraft ambient sound is played for all pokemon

#### What you expected to happen:

Pokemon sounds

#### Steps to reproduce:

1. Go near a pokemon
...

____
#### Affected Versions (Do *not* use "latest"):

Forge 1965
Pokecube core 3.24
Pokecube mobs 2.12
Pokecube revival 3.22
Minecraft: 1.9.4

**Comment by Thutmose** [comment]
I hear wild pokemobs in my testing environment, this one might take a bit longer for me to fix.

**Comment by schindlershadow** [comment]
Selecting the sound in the Pokedex does seem to work.

**Comment by Thutmose** [comment]
Hmm, what kind of minecraft ambient sounds? when they hit the ground they will make minecraft hitting ground sounds, they only make their custom sounds when they randomly "say" stuff, so in situations where say a sheep would randomly go "baa" for no apparent reason.

**Comment by schindlershadow** [comment]
Just checked again and they dont seem to make any sounds at all when near them randomly, they only make the ambient sound when they die. The minecraft ambient sound is the one where your in darkness (https://hydra-media.cursecdn.com/minecraft.gamepedia.com/d/da/Cave4.ogg), it seems to only play this one.

**Comment by Thutmose** [comment]
Hmm, odd, I hear them make their sounds as ambient, I wonder if it is another mod or resource pack somehow interfering?

**Comment by schindlershadow** [comment]
when I said " they only make the ambient sound when they die" I mean the minecraft one, not the pokemon's cry. It might be another mod, not using any resource pack.

**Comment by Thutmose** [comment]
oh, you mean they make the minecraft ambient when on death, rather than their own? I will look into that, I hadn't tested that.

**Comment by schindlershadow** [comment]
yes, and rather than playing their cry like a cow would randomly moo they dont make any sounds at all

**Comment by Thutmose** [comment]
I did some testing on this on my end, and they play their sound on death for me.

**Comment by jochuan** [comment]
I dont know if it is related but some pokemons dont have sounds at all

**Comment by Thutmose** [comment]
I found how to replicate this, I will work on the fix now.

**Comment by Thutmose** [comment]
This one is now fixed in 1.9.4/1.10
