### ISSUE TITLE
[1.9.4] console spam from Pokémon 

### ISSUE THREAD

**Issue by XileForce** [Thutmose/Pokecube#40]
The best way to describe this is essentially messages such as this spamming constantly in console:

12:21:48
Keeping entity pokecube_ml.Zubat that already exists with UUID cfc6cb05-6b90-4954-956a-18306d02b410
Keeping entity pokecube_ml.Zubat that already exists with UUID 315c09a9-893b-4c1b-9032-ef099ba381a1
Keeping entity pokecube_ml.Scatterbug that already exists with UUID 8a002789-2628-4293-93dd-f1c4c2c74d3c
Keeping entity pokecube_ml.Scatterbug that already exists with UUID bd05a883-2333-4e1f-890f-2ee0ff1f6d89
Keeping entity pokecube_ml.Scatterbug that already exists with UUID 8694d79f-e014-492d-8bba-05a3af4e3f71
12:21:49
Keeping entity pokecube_ml.Zubat that already exists with UUID fa65fdd9-e32f-42e4-8668-368d699a183e

I don't know if this is necessarily bad but it's sometimes multiple times per second.

Modpack:
InfiniX Test 

Forge 1965
Pokecube core 3.24
Pokecube mobs 2.12
Pokecube revival 3.22

**Comment by Thutmose** [comment]
Hmm, that sounds like a related issue to the earlier evolution bug, I will look into it.

**Comment by XileForce** [comment]
Okay. I haven't been able to test that new update yet since im at work, but if that resolves it I will let you know. Thanks or the Swift reply too! Sorry for reporting all these issues lol.

**Comment by Thutmose** [comment]
No problem, issues give me something to do, otherwise I mostly sit here browsing reddit.

**Comment by Thutmose** [comment]
confirmed that that spam has been removed due to the evolution bug fix, it should go away whenever you update.
