### ISSUE TITLE
[1.9.4] Ticking Entity Error

### ISSUE THREAD

**Issue by XileForce** [Thutmose/Pokecube#41]
[19:19:17] [Server thread/ERROR] [FML/]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreXU2 (extrautils2-1.9.4-alpha-1.0.0a.jar)
  CCCDeobfPlugin (unknown)
  LoadingPlugin (RandomThings-MC1.9.4-3.7.3.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.9.4-2.0.3.65-universal.jar)
  LoadingPlugin (Quark-beta-28.jar)
  FMLPlugin (InventoryTweaks-1.61-dev-53.jar)
  TransformerLoader (OpenComputers-MC1.9.4-1.6.0.2-beta.3.jar)
  EnderCorePlugin (EnderCore-1.9.4-0.4.0.26-alpha.jar)
  CCLCorePlugin (CodeChickenLib-1.9.4-2.0.2.39-universal.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 6/20/16 7:19 PM
Description: Ticking entity

java.lang.NullPointerException: The validated object is null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:203)
	at net.minecraft.util.ResourceLocation.<init>(SourceFile:17)
	at net.minecraft.util.ResourceLocation.<init>(SourceFile:25)
	at pokecube.core.database.PokedexEntry.getSoundEvent(PokedexEntry.java:1396)
	at pokecube.core.entity.pokemobs.helper.EntityPokemobBase.func_184639_G(EntityPokemobBase.java:170)
	at net.minecraft.entity.EntityLiving.func_70642_aH(EntityLiving.java:202)
	at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:218)
	at pokecube.core.entity.pokemobs.helper.EntitySexedPokemob.func_70030_z(EntitySexedPokemob.java:398)
	at pokecube.core.entity.pokemobs.helper.EntityMovesPokemob.func_70030_z(EntityMovesPokemob.java:583)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:354)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1895)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:299)
	at pokecube.core.entity.pokemobs.helper.EntityTameablePokemob.func_70071_h_(EntityTameablePokemob.java:481)
	at pokecube.core.entity.pokemobs.helper.EntityStatsPokemob.func_70071_h_(EntityStatsPokemob.java:586)
	at pokecube.core.entity.pokemobs.helper.EntityMovesPokemob.func_70071_h_(EntityMovesPokemob.java:730)
	at pokecube.core.entity.pokemobs.helper.EntityEvolvablePokemob.func_70071_h_(EntityEvolvablePokemob.java:346)
	at pokecube.core.entity.pokemobs.helper.EntityMountablePokemob.func_70071_h_(EntityMountablePokemob.java:557)
	at pokecube.core.entity.pokemobs.helper.EntityAiPokemob.func_70071_h_(EntityAiPokemob.java:857)
	at pokecube.core.entity.pokemobs.helper.EntityHungryPokemob.func_70071_h_(EntityHungryPokemob.java:370)
	at pokecube.core.entity.pokemobs.helper.EntityPokemobBase.func_70071_h_(EntityPokemobBase.java:599)
	at net.minecraft.world.World.func_72866_a(World.java:1951)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837)
	at net.minecraft.world.World.func_72870_g(World.java:1920)
	at net.minecraft.world.World.func_72939_s(World.java:1743)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:707)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:385)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:203)
	at net.minecraft.util.ResourceLocation.<init>(SourceFile:17)
	at net.minecraft.util.ResourceLocation.<init>(SourceFile:25)
	at pokecube.core.database.PokedexEntry.getSoundEvent(PokedexEntry.java:1396)
	at pokecube.core.entity.pokemobs.helper.EntityPokemobBase.func_184639_G(EntityPokemobBase.java:170)
	at net.minecraft.entity.EntityLiving.func_70642_aH(EntityLiving.java:202)
	at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:218)
	at pokecube.core.entity.pokemobs.helper.EntitySexedPokemob.func_70030_z(EntitySexedPokemob.java:398)
	at pokecube.core.entity.pokemobs.helper.EntityMovesPokemob.func_70030_z(EntityMovesPokemob.java:583)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:354)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1895)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:299)
	at pokecube.core.entity.pokemobs.helper.EntityTameablePokemob.func_70071_h_(EntityTameablePokemob.java:481)
	at pokecube.core.entity.pokemobs.helper.EntityStatsPokemob.func_70071_h_(EntityStatsPokemob.java:586)
	at pokecube.core.entity.pokemobs.helper.EntityMovesPokemob.func_70071_h_(EntityMovesPokemob.java:730)
	at pokecube.core.entity.pokemobs.helper.EntityEvolvablePokemob.func_70071_h_(EntityEvolvablePokemob.java:346)
	at pokecube.core.entity.pokemobs.helper.EntityMountablePokemob.func_70071_h_(EntityMountablePokemob.java:557)
	at pokecube.core.entity.pokemobs.helper.EntityAiPokemob.func_70071_h_(EntityAiPokemob.java:857)
	at pokecube.core.entity.pokemobs.helper.EntityHungryPokemob.func_70071_h_(EntityHungryPokemob.java:370)
	at pokecube.core.entity.pokemobs.helper.EntityPokemobBase.func_70071_h_(EntityPokemobBase.java:599)
	at net.minecraft.world.World.func_72866_a(World.java:1951)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837)
	at net.minecraft.world.World.func_72870_g(World.java:1920)

-- Entity being ticked --
Details:
	Entity Type: pokecube_ml.Vivillon (pokecube.core.entity.pokemobs.GenericPokemob666)
	Entity ID: 2313
	Entity Name: Vivillon
	Entity's Exact location: 3102.63, 74.00, 1021.08
	Entity's Block location: World: (3102,73,1021), Chunk: (at 14,4,13 in 193,63; contains blocks 3088,0,1008 to 3103,255,1023), Region: (6,1; contains chunks 192,32 to 223,63, blocks 3072,0,512 to 3583,255,1023)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1743)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:707)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:385)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.9.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_92, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 973076336 bytes (927 MB) / 2176843776 bytes (2076 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 10 total; -Xmx8192M -Xms2G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication -XX:+AlwaysPreTouch -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+UseFastAccessorMethods -XX:+AggressiveOpts
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.28 Powered by Forge 12.17.0.1968 96 mods loaded, 96 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (ForgeMod.jar) 
	UCHIJAAAA	Forge{12.17.0.1968} [Minecraft Forge] (ForgeMod.jar) 
	UCHIJAAAA	CodeChickenCore{2.0.3.65} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	OpenComputers|Core{1.6.0.2-beta.3} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	actuallyadditions{1.9.4-r45} [Actually Additions] (ActuallyAdditions-1.9.4-r45.jar) 
	UCHIJAAAA	Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar) 
	UCHIJAAAA	baublesstuff{2.0.10} [Baubles Stuff] (baublesstuff-2.0.10.jar) 
	UCHIJAAAA	bdlib{1.11.0.1} [BD Lib] (bdlib-1.11.0.1-mc1.9.4.jar) 
	UCHIJAAAA	BiomesOPlenty{4.1.0.2029} [Biomes O' Plenty] (BiomesOPlenty-1.9.4-4.1.0.2029-universal.jar) 
	UCHIJAAAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.9.4-alpha-1.0.0a.jar) 
	UCHIJAAAA	JEI{3.6.7.216} [Just Enough Items] (jei_1.9.4-3.6.7.216.jar) 
	UCHIJAAAA	BloodMagic{1.9.4-2.0.1-44} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.0.1-44.jar) 
	UCHIJAAAA	BloodArsenal{1.9.4-2.0.0-5} [Blood Arsenal] (BloodArsenal-1.9.4-2.0.0-5.jar) 
	UCHIJAAAA	bookshelf{1.2.3.276} [Bookshelf] (Bookshelf-1.9.4-1.2.3.276.jar) 
	UCHIJAAAA	bookshelfapi{3.1.0} [Bookshelf] (Bookshelf-API-1.9.4-3.1.0.jar) 
	UCHIJAAAA	Botania{r1.8-310} [Botania] (Botania-unofficial.r1.8-310.jar) 
	UCHIJAAAA	Chameleon{1.9-2.1.4} [Chameleon] (Chameleon-1.9-2.1.4.jar) 
	UCHIJAAAA	ChickenChunks{2.0.2.32} [ChickenChunks] (ChickenChunks-1.9.4-2.0.2.32-universal.jar) 
	UCHIJAAAA	mcmultipart{1.2.0} [MCMultiPart] (MCMultiPart-1.2.0-universal.jar) 
	UCHIJAAAA	chiselsandbits{10.7} [Chisels & Bits] (chiselsandbits-10.7.jar) 
	UCHIJAAAA	gg5cookiemod{0.5} [Cookie Obsession Mod] (CookieObsession-1.9.4-0.6.jar) 
	UCHIJAAAA	cyclopscore{0.6.3} [Cyclops Core] (CyclopsCore-1.9.4-0.6.3-350.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJAAAA	DarkUtils{1.1.2.52} [Dark Utilities] (DarkUtilities-1.9.4-1.1.2.55.jar) 
	UCHIJAAAA	ElecCore{1.5.292} [ElecCore] (ElecCore-1.9.4-1.5.292.jar) 
	UCHIJAAAA	deepresonance{1.2.0beta34} [DeepResonance] (deepresonance-1.9.4-1.2.0beta34.jar) 
	UCHIJAAAA	ea{v2.3.9a-mc1.9.4} [Ebon Arts] (EbonArts-v2.3.9a-mc1.9.4.jar) 
	UCHIJAAAA	endercore{1.9.4-0.4.0.26-alpha} [EnderCore] (EnderCore-1.9.4-0.4.0.26-alpha.jar) 
	UCHIJAAAA	EnderIO{1.9.4-3.0.0.43_alpha} [Ender IO] (EnderIO-1.9.4-3.0.0.43_alpha.jar) 
	UCHIJAAAA	enderrift{0.16.3} [Ender-Rift] (EnderRift-1.9.4-0.16.3.jar) 
	UCHIJAAAA	EnderStorage{2.0.2.53} [EnderStorage] (EnderStorage-1.9.4-2.0.2.53-universal.jar) 
	UCHIJAAAA	EnderZoo{1.9.4-1.2.2.40} [Ender Zoo] (EnderZoo-1.9.4-1.2.2.40.jar) 
	UCHIJAAAA	ValkyrieLib{1.9.4-0.9.10} [Valkyrie Lib] (valkyrielib-1.9.4-0.9.10.jar) 
	UCHIJAAAA	EnvironmentalTech{1.9.4-0.9.4c} [Environmental Tech] (environmentaltech-1.9.4-0.9.4c.jar) 
	UCHIJAAAA	evilcraft{0.10.2} [EvilCraft] (EvilCraft-1.9.4-0.10.2-416.jar) 
	UCHIJAAAA	ExtraBitManipulation{1.9-2.1.2} [Extra Bit Manipulation] (ExtraBitManipulation-1.9.4-2.1.0.jar) 
	UCHIJAAAA	IronChest{6.0.145.787} [Iron Chest] (ironchest-1.9.4-6.0.145.787.jar) 
	UCHIJAAAA	randomthings{3.7.3} [Random Things] (RandomThings-MC1.9.4-3.7.3.jar) 
	UCHIJAAAA	xreliquary{1.9.4-1.3.2.372} [Reliquary] (Reliquary-1.9.4-1.3.2.372.jar) 
	UCHIJAAAA	fluidity{6.0.0.6} [Fluidity] (Fluidity-6.0.0.6.jar) 
	UCHIJAAAA	fluxducts{1.0.4} [Flux Ducts] (fluxducts-mc1.9.4-1.0.4.jar) 
	UCHIJAAAA	forestry{5.0.20.167} [Forestry] (forestry_1.9.4-5.0.20.167.jar) 
	UCHIJAAAA	advgenerators{0.9.20.1} [Advanced Generators] (generators-0.9.20.1-mc1.9.4.jar) 
	UCHIJAAAA	gg5lootmod{0.81} [Loot Mod] (gg5lootmod-1.9.4-0.81.jar) 
	UCHIJAAAA	gravestone{1.3.0} [Gravestone] (Gravestone Mod 1.3.0.jar) 
	UCHIJAAAA	HelpFixer{1.3.14} [HelpFixer] (HelpFixer-1.9.4-1.3.14.jar) 
	UCHIJAAAA	InfernalMobs{1.7.0} [Infernal Mobs] (InfernalMobs-1.9.4.jar) 
	UCHIJAAAA	integrateddynamics{0.3.10} [Integrated Dynamics] (IntegratedDynamics-1.9.4-0.3.10-247.jar) 
	UCHIJAAAA	inventorytweaks{1.61-dev-53-0736dc3} [Inventory Tweaks] (InventoryTweaks-1.61-dev-53.jar) 
	UCHIJAAAA	japta{1.8.1} [JAPTA] (JAPTA-1.9.4-1.8.1.jar) 
	UCHIJAAAA	journeymap{1.9.4-5.2.1} [JourneyMap] (journeymap-1.9.4-5.2.1-fairplay.jar) 
	UCHIJAAAA	xlib{r1.0.1} [xLib] (xLib-1.9.4-r1.0.1.jar) 
	UCHIJAAAA	levels{r3.0.3} [Levels] (Levels-1.9.4-r3.0.3.jar) 
	UCHIJAAAA	LunatriusCore{1.1.2.35} [LunatriusCore] (LunatriusCore-1.9.4-1.1.2.35-universal.jar) 
	UCHIJAAAA	mantle{1.9.4-0.10.2.jenkins149} [Mantle] (Mantle-1.9.4-0.10.2.jar) 
	UCHIJAAAA	Mekanism{9.0.2} [Mekanism] (MekanismAll-1.9.4-9.0.2.homebaked.jar) 
	UCHIJAAAA	examplemod{1.0} [examplemod] (MekanismAll-1.9.4-9.0.2.homebaked.jar) 
	UCHIJAAAA	MekanismGenerators{9.0.2} [MekanismGenerators] (MekanismAll-1.9.4-9.0.2.homebaked.jar) 
	UCHIJAAAA	MekanismTools{9.0.2} [MekanismTools] (MekanismAll-1.9.4-9.0.2.homebaked.jar) 
	UCHIJAAAA	ModLister{1.9.4-2.1.5} [ModLister] (ModLister-1.9.4-2.1.5.jar) 
	UCHIJAAAA	Morphtool{GRADLE:VERSION-GRADLE:BUILD} [Morph-o-Tool] (Morph-o-Tool-1.0-3.jar) 
	UCHIJAAAA	tconstruct{1.9.4-2.3.2.jenkins255} [Tinkers' Construct] (TConstruct-1.9.4-2.3.2.jar) 
	UCHIJAAAA	neotech{3.1.0} [NeoTech] (NeoTech-1.9.4-3.1.0.jar) 
	UCHIJAAAA	nethermetals{1.1.0} [Nether Metals] (NetherMetals_1.9-1.1.0.jar) 
	UCHIJAAAA	OpenComputers{1.6.0.2-beta.3} [OpenComputers] (OpenComputers-MC1.9.4-1.6.0.2-beta.3.jar) 
	UCHIJAAAA	openradio{0.7.3} [OpenRadio] (OpenRadio-0.7.3-MC1.9.4.jar) 
	UCHIJAAAA	fodc{1.8.2} [Ore Dictionary Converter] (OreDictionaryConverter-1.8.2.jar) 
	UCHIJAAAA	harvestcraft{1.9.4-pre} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4b.jar) 
	UCHIJAAAA	thutcore{3.1.2} [ThutCore] (thutcore-1.9.4-3.1.2.jar) 
	UCHIJAAAA	NBTEditpqb{1.8-1.0} [In-game NBTEdit - Pokecube Edition] (Pokecube Core-3.2.6.jar) 
	UCHIJAAAA	pokecube{3.2.6} [Pokécube Core] (Pokecube Core-3.2.6.jar) 
	UCHIJAAAA	pokecube_ml{0.1.0} [Pokecube Model Loader] (Pokecube Core-3.2.6.jar) 
	UCHIJAAAA	pokecube_mobs{2.1.2} [Pokécube Mobs] (Pokecube Mobs-2.1.2.jar) 
	UCHIJAAAA	pokecube_adventures{3.2.2} [Pokécube Revival] (Pokecube Revival-3.2.2.jar) 
	UCHIJAAAA	progressiveautomation{1.6.46} [Progressive Automation] (ProgressiveAutomation-1.9.4-1.6.46.jar) 
	UCHIJAAAA	Psi{r1.0-35} [Psi] (Psi-r1.0-35.jar) 
	UCHIJAAAA	quantumflux{2.0.7} [QuantumFlux] (quantumflux-1.9.4-2.0.7.jar) 
	UCHIJAAAA	Quark{beta-28} [Quark] (Quark-beta-28.jar) 
	UCHIJAAAA	reborncore{2.5.4.47} [RebornCore] (RebornCore-1.9.4-2.5.4.47-universal.jar) 
	UCHIJAAAA	reborncore-mcmultipart{2.5.4.47} [reborncore-MCMultiPart] (RebornCore-1.9.4-2.5.4.47-universal.jar) 
	UCHIJAAAA	StorageDrawers{1.9-3.1.7} [Storage Drawers] (StorageDrawers-1.9-3.1.7.jar) 
	UCHIJAAAA	refinedstorage{0.7.16} [Refined Storage] (refinedstorage-0.7.16.jar) 
	UCHIJAAAA	rftools{4.64} [RFTools] (rftools-1.9.4-4.64.jar) 
	UCHIJAAAA	Roguelike{1.5.2} [Roguelike Dungeons] (RoguelikeDungeons-1.9.4-1.5.2.jar) 
	UCHIJAAAA	flammpfeil.slashblade{mc1.9.4-r10} [SlashBlade] (SlashBlade-mc1.9.4-r10.jar) 
	UCHIJAAAA	solarvillage{1.0.0.7} [Solar Village] (SolarVillage-1.9.4-1.0.0.12.jar) 
	UCHIJAAAA	soulshardstow{1.9.4-2.4.4-32} [Soul Shards - The Old Ways] (SoulShards-TOW-1.9.4-2.4.4-32.jar) 
	UCHIJAAAA	Stackie{1.6.0.42} [Stackie] (Stackie-1.9.4-1.6.0.42-universal.jar) 
	UCHIJAAAA	techreborn{1.3.2.120} [TechReborn] (TechReborn-1.9.4-1.3.2.120-universal.jar) 
	UCHIJAAAA	Tesla{1.1.0.24} [TESLA] (Tesla-1.9.4-1.1.0.24.jar) 
	UCHIJAAAA	testtubeanimals{1.1.1} [Test Tube Animals] (testtubeanimals-1.1.1.jar) 
	UCHIJAAAA	tis3d{0.9.0.5} [TIS-3D] (TIS-3D-MC1.9.4-0.9.0.5.jar) 
	UCHIJAAAA	ICSE{1.0.0.0} [I Can See Everything] (Wawla-1.9.4-2.2.1.192.jar) 
	UCHIJAAAA	wawla{2.2.1.188} [What Are We Looking At] (Wawla-1.9.4-2.2.1.192.jar) 
	UCHIJAAAA	ZDoctorBB{1.1} [Blood Baubles] (ZDoctorBB-1.1.jar) 
	Loaded coremods (and transformers): 
CoreXU2 (extrautils2-1.9.4-alpha-1.0.0a.jar)
  com.rwtema.extrautils2.asm.ClassTransformerHandler
CCCDeobfPlugin (unknown)
  
LoadingPlugin (RandomThings-MC1.9.4-3.7.3.jar)
  lumien.randomthings.asm.ClassTransformer
CodeChickenCorePlugin (CodeChickenCore-1.9.4-2.0.3.65-universal.jar)
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
LoadingPlugin (Quark-beta-28.jar)
  vazkii.quark.base.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.61-dev-53.jar)
  invtweaks.forge.asm.ContainerTransformer
TransformerLoader (OpenComputers-MC1.9.4-1.6.0.2-beta.3.jar)
  li.cil.oc.common.asm.ClassTransformer
EnderCorePlugin (EnderCore-1.9.4-0.4.0.26-alpha.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
CCLCorePlugin (CodeChickenLib-1.9.4-2.0.2.39-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* actuallyadditionsapi (17) from ActuallyAdditions-1.9.4-r45.jar
		* Baubles|API (1.1.1.0) from Baubles-1.9.4-1.2.1.0.jar
		* BloodMagic|API (@VERSION@) from BloodMagic-1.9.4-2.0.1-44.jar
		* BotaniaAPI (79) from Botania-unofficial.r1.8-310.jar
		* CapabilityCore|base (1.01) from EnderRift-1.9.4-0.16.3.jar
		* CapabilityCore|energy (1.01) from EnderRift-1.9.4-0.16.3.jar
		* CapabilityCore|tweakable (1.01) from EnderRift-1.9.4-0.16.3.jar
		* ChiselsAndBitsAPI (1.8.1) from chiselsandbits-10.7.jar
		* CoFHAPI (1.8.9R1.2.0B1) from ProgressiveAutomation-1.9.4-1.6.46.jar
		* CoFHAPI|block (1.8.9R1.2.0B1) from fluxducts-mc1.9.4-1.0.4.jar
		* CoFHAPI|core (1.8.9R1.2.0B1) from valkyrielib-1.9.4-0.9.10.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from JAPTA-1.9.4-1.8.1.jar
		* CoFHAPI|inventory (1.8.9R1.2.0B1) from valkyrielib-1.9.4-0.9.10.jar
		* CoFHAPI|item (1.8-BuildCraft-Testing) from MekanismAll-1.9.4-9.0.2.homebaked.jar
		* CoFHAPI|tileentity (1.8.9R1.2.0B1) from ProgressiveAutomation-1.9.4-1.6.46.jar
		* commoncapabilities|api (0.0.1) from IntegratedDynamics-1.9.4-0.3.10-247.jar
		* DR-API (1.0.4-Beta) from deepresonance-1.9.4-1.2.0beta34.jar
		* ElecCore|Abilities (#API_VER#) from ElecCore-1.9.4-1.5.292.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.9.4-3.0.0.43_alpha.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.9.4-3.0.0.43_alpha.jar
		* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.9.4-3.0.0.43_alpha.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.9.4-3.0.0.43_alpha.jar
		* environmentaltech.api (1.9.4-0.9.4c) from environmentaltech-1.9.4-0.9.4c.jar
		* ForestryAPI|apiculture (4.8.0) from forestry_1.9.4-5.0.20.167.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.9.4-5.0.20.167.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.9.4-5.0.20.167.jar
		* ForestryAPI|core (5.0.0) from forestry_1.9.4-5.0.20.167.jar
		* ForestryAPI|farming (2.1.0) from forestry_1.9.4-5.0.20.167.jar
		* ForestryAPI|food (1.1.0) from forestry_1.9.4-5.0.20.167.jar
		* ForestryAPI|fuels (2.0.1) from forestry_1.9.4-5.0.20.167.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.9.4-5.0.20.167.jar
		* ForestryAPI|greenhouse (5.0.0) from forestry_1.9.4-5.0.20.167.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.9.4-5.0.20.167.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.9.4-5.0.20.167.jar
		* ForestryAPI|mail (3.0.0) from forestry_1.9.4-5.0.20.167.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.9.4-5.0.20.167.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.9.4-5.0.20.167.jar
		* ForestryAPI|storage (3.0.0) from forestry_1.9.4-5.0.20.167.jar
		* ForestryAPI|world (2.1.0) from forestry_1.9.4-5.0.20.167.jar
		* integrateddynamics|api (0.1.0) from IntegratedDynamics-1.9.4-0.3.10-247.jar
		* journeymap|client-api (1.2) from journeymap-1.9.4-5.2.1-fairplay.jar
		* journeymap|client-api-display (1.2) from journeymap-1.9.4-5.2.1-fairplay.jar
		* journeymap|client-api-event (1.2) from journeymap-1.9.4-5.2.1-fairplay.jar
		* journeymap|client-api-model (1.2) from journeymap-1.9.4-5.2.1-fairplay.jar
		* journeymap|client-api-util (1.2) from journeymap-1.9.4-5.2.1-fairplay.jar
		* JustEnoughItemsAPI (3.1.0) from jei_1.9.4-3.6.7.216.jar
		* McJtyLib (1.9.4-1.9.1) from mcjtylib-1.9.4-1.9.1.jar
		* MekanismAPI|core (9.0.0) from MekanismAll-1.9.4-9.0.2.homebaked.jar
		* MekanismAPI|energy (9.0.0) from MekanismAll-1.9.4-9.0.2.homebaked.jar
		* MekanismAPI|gas (9.0.0) from MekanismAll-1.9.4-9.0.2.homebaked.jar
		* MekanismAPI|infuse (9.0.0) from MekanismAll-1.9.4-9.0.2.homebaked.jar
		* MekanismAPI|laser (9.0.0) from MekanismAll-1.9.4-9.0.2.homebaked.jar
		* MekanismAPI|reactor (9.0.0) from MekanismAll-1.9.4-9.0.2.homebaked.jar
		* MekanismAPI|recipe (9.0.0) from MekanismAll-1.9.4-9.0.2.homebaked.jar
		* MekanismAPI|transmitter (9.0.0) from MekanismAll-1.9.4-9.0.2.homebaked.jar
		* MekanismAPI|util (9.0.0) from MekanismAll-1.9.4-9.0.2.homebaked.jar
		* OpenComputersAPI|Component (6.0.0-alpha) from OpenComputers-MC1.9.4-1.6.0.2-beta.3.jar
		* OpenComputersAPI|Core (6.0.0-alpha) from OpenComputers-MC1.9.4-1.6.0.2-beta.3.jar
		* OpenComputersAPI|Driver (6.0.0-alpha) from OpenComputers-MC1.9.4-1.6.0.2-beta.3.jar
		* OpenComputersAPI|Driver|Item (6.0.0-alpha) from OpenComputers-MC1.9.4-1.6.0.2-beta.3.jar
		* OpenComputersAPI|Event (6.0.0-alpha) from OpenComputers-MC1.9.4-1.6.0.2-beta.3.jar
		* OpenComputersAPI|FileSystem (6.0.0-alpha) from OpenComputers-MC1.9.4-1.6.0.2-beta.3.jar
		* OpenComputersAPI|Internal (6.0.0-alpha) from OpenComputers-MC1.9.4-1.6.0.2-beta.3.jar
		* OpenComputersAPI|Machine (6.0.0-alpha) from OpenComputers-MC1.9.4-1.6.0.2-beta.3.jar
		* OpenComputersAPI|Manual (6.0.0-alpha) from OpenComputers-MC1.9.4-1.6.0.2-beta.3.jar
		* OpenComputersAPI|Network (6.0.0-alpha) from OpenComputers-MC1.9.4-1.6.0.2-beta.3.jar
		* OpenComputersAPI|Prefab (6.0.0-alpha) from OpenComputers-MC1.9.4-1.6.0.2-beta.3.jar
		* PsiAPI (2) from Psi-r1.0-35.jar
		* reborncoreAPI (2.5.4.47) from RebornCore-1.9.4-2.5.4.47-universal.jar
		* SoulShardsTOW|API (0.1.5) from SoulShards-TOW-1.9.4-2.4.4-32.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.7.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from refinedstorage-0.7.16.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from refinedstorage-0.7.16.jar
		* StorageDrawersAPI|inventory (1.7.10-1.2.0) from refinedstorage-0.7.16.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from refinedstorage-0.7.16.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.7.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from refinedstorage-0.7.16.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.7.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.9-3.1.7.jar
		* techrebornAPI (1.3.2.120) from TechReborn-1.9.4-1.3.2.120-universal.jar
		* Tesla|API (1.1.0.24) from Tesla-1.9.4-1.1.0.24.jar
		* thut|API (1.0.0) from Pokecube Core-3.2.6.jar
		* tis3dAPI (0.9.0.5) from TIS-3D-MC1.9.4-0.9.0.5.jar
		* ValkyrieLib.api (1.9.4-0.9.10) from valkyrielib-1.9.4-0.9.10.jar
		* WailaAPI (1.3) from Waila-1.7.0-B3_1.9.4.jar
	EnderIO: No known problems detected.

I have enabled forges feature to auto remove ticking tile entities and entities rather than crashing, so this doesn't actually do anything but its spamming the console and I figured you may wanna check it out. 

Forge 1968
Pokecube core 3.26
Pokecube mobs 2.12
Pokecube revival 3.22

**Comment by Thutmose** [comment]
Testing the fix for that as soon as it compiles.

**Comment by Thutmose** [comment]
so I have that fixed, but I will need to disable all of the OC stuff I was working on for a release, as it seems there is a major bug in OC right now with adding components.

I should have a release that fixes that in an hour or so.

**Comment by XileForce** [comment]
Ok man. you are awesome

**Comment by Thutmose** [comment]
I will spend the next 30 minutes or so trying to find a workaround to this OC issue, if I don't get it working, I will just disable all of the OC stuff again, and release the fix for this crash.

**Comment by XileForce** [comment]
no worries. take your time

**Comment by Thutmose** [comment]
Fixed in 3.2.7

Note that 3.2.8 also re-adds baubles support, so I suggest waiting for it to be approved on curse, rather than using 3.2.7
