### ISSUE TITLE
Pokemon that evolve through items unevolvable?

### ISSUE THREAD

**Issue by schindlershadow** [Thutmose/Pokecube#42]
#### Issue Description:

Modpack: Infinix test
#### What happens:

Pokemon (such as sneasel) that require an item to evolve (razor claw) cannot. Also not sure if Time-of-day evolving is implemented. 
#### What you expected to happen:

Some workaround by level or razor claw being implemented that allow these pokemon to evolve. 

---
#### Affected Versions (Do _not_ use "latest"):

Forge 1965
Pokecube core 3.2.6
Pokecube mobs 2.1.2
Pokecube revival 3.2.2

**Comment by Thutmose** [comment]
Several of those special evolution items are currently mapped to vanilla items, you can find them here:

https://github.com/Thutmose/Pokecube/blob/master/Pokecube%20Core/src/main/java/pokecube/core/PokecubeItems.java#L478-L492

**Comment by jochuan** [comment]
If you want i can make real textures for them

**Comment by Thutmose** [comment]
eh, I don't know if I want to add a bunch of items which only have 1 use, maybe I can make an ingame thing that shows which items are mapped to which evolution item instead.

**Comment by jochuan** [comment]
yeah that would be cool but i think that some items that have more than one function should be made like the dragon scale that evolves seadra and boosts dragon type moves by 10% when hold

**Comment by Thutmose** [comment]
I guess I could make 1 more item, which can then be used for a variety of held items for pokemobs, I am not sure how I would want to go about having them obtainable though.

**Comment by jochuan** [comment]
maybe making it appears on chests from dungeons or traded by trainers and about the move boost items did you want them ?

**Comment by Thutmose** [comment]
which move boost items?

Traded by trainers would be a good idea.

Also, if I do go and make these items, I will probably also be able to include the arceus plates as well.

**Comment by jochuan** [comment]
i am talking about type-enchancing items like silk scarf and dragon fang and items that enchance types and evolve at the same time like metal coat did you need them ?

**Comment by Thutmose** [comment]
Just as I was about to reply to this, my internet cut out.  

Ya, I just re-wrote some of the held items to allow me to extend them without using IDs, Send them all in 1 zip file please.

**Comment by Thutmose** [comment]
Just as I was about to reply to this, my internet cut out.  

Ya, I just re-wrote some of the held items to allow me to extend them without using IDs, Send them all in 1 zip file please.

**Comment by jochuan** [comment]
I cant make all of them right now i will make them in next week but i think that i have time to make two tomorow

**Comment by Thutmose** [comment]
Ok, that is fine, I can add them in when you get them done.

**Comment by jochuan** [comment]
i made 3 items textures i uploaded them in the minecraft forum i gonna make the rest in the next week

**Comment by jochuan** [comment]
[http://media-minecraftforum.cursecdn.com/attachments/208/868/636022771005675929.png](url)
[http://media-minecraftforum.cursecdn.com/attachments/208/867/636022769477873041.png](url)
[http://media-minecraftforum.cursecdn.com/attachments/208/866/636022769434006161.png](url)
 here are 3 items textures

**Comment by Thutmose** [comment]
Hmm, that didn't seem to work, can you drag the image file itself into the comment? as in save it to a computer, then drag it into the comment?

**Comment by jochuan** [comment]
https://drive.google.com/file/d/0Bwkd5IdoB4l9Z1UxRk42aHJ3M2s/view?usp=drivesdk
 I made some more items

**Comment by Thutmose** [comment]
Thanks, I will see about getting those in.

**Comment by jochuan** [comment]
https://drive.google.com/file/d/0Bwkd5IdoB4l9YXVkNHE5Qno1TkE/view?usp=drivesdk
Here is the rest these items have more than one function unless the magmarizer and the electarizer which are updated versions of those that i sended to you

**Comment by jochuan** [comment]
The next ones will be normal held items

**Comment by jochuan** [comment]
https://drive.google.com/file/d/0Bwkd5IdoB4l9VmdYOUhSRUEyTHM/view?usp=drivesdk
Here are the attack boost items i think that these and the items that have more than one function shouldnt be traded by trainers would be op if a trainer had one dragon fang for every      dragon pokemon that it has so they probaly should be rarely dropped by pokemobs and be found on dungeon chests and for the charcoal and the hard rock they could be found rarely when mining stone and charcoal

**Comment by Thutmose** [comment]
Ok, Thanks.

I will probably get around to adding these once I get most of the bugs out of the 1.9.4/1.10 versions, which will probably be sometime in the next week or so.

**Comment by jochuan** [comment]
https://drive.google.com/file/d/0Bwkd5IdoB4l9NG5SOW5aaHRqMG8/view?usp=drivesdk
Here is the last set

**Comment by Thutmose** [comment]
In the recent versions, everything related to this can be overwritten with configs, so closing this issue.
