### ISSUE TITLE
[1.9.4] Duplicating PokeCubes When Dropped

### ISSUE THREAD

**Issue by XileForce** [Thutmose/Pokecube#43]
Problem:
If you shift right click with a pokecube in hand to drop it on the ground, it drops 1 from your inventory but creates 2.

steps to reproduce:
hold a pokecube of any type. shift right click. it will fall onto the ground. now if you nudge it by walking into it you will see the one dropped pokecube separate into 2 pokecubes. You now got 2 pokecubes from 1.

Forge 1968
Pokecube core 3.26
Pokecube mobs 2.12
Pokecube revival 3.22

**Comment by Thutmose** [comment]
Should have this fixed shortly, I will upload it along with some possible fixes for some OC issues.

**Comment by Thutmose** [comment]
Have that issue fixed, will be in 3.2.9 whenever it is uploaded (testing an OC issue fix now)
Also fixed the issue where it gives the bad aim message even if it properly throws the cube (related to the dupe bug)

**Comment by XileForce** [comment]
Okay cool! quick question. For AI threads what is your recommendation for a setting? as high as possible? for instance we have an 8 core server in which case would it be beneficial to set that to 8. sorry for the off topic but having trouble finding documentation on the config files.

**Comment by Thutmose** [comment]
that should probably just be kept at 1, I have optimized a bunch of stuff since I did that, and it should do fine now with just 1 thread, unless you plan to have lots and lots each in separate areas.

Generally it should be 1 thread per 500-600 active pokemobs, any pokemob that is "out of range" isn't active, "out of range" means more than the despawn distance from the player, the default settings result in about 20-30 active pokemobs per player, but that assumes each player is more than despawn distance apart

**Comment by XileForce** [comment]
Thank you very much for the clarification. I've slightly reduced the spawn rate from default so I will definitely be fine with 1 then.

**Comment by Thutmose** [comment]
I might just end up scrapping the OC support for now, it seems that there are some major issues with trying to make components for it in 1.9.4, it has some issues with the asm stuff it does.

If my next few attempts at a workaround don't work, I will do that.

**Comment by Thutmose** [comment]
do you know of any mods that add OC support for 1.9.4? If I could see what they do, it might help.

**Comment by XileForce** [comment]
Hmm well ik there's an add-on for open computers called open radios. http://minecraft.curseforge.com/projects/openradio perhaps that will help.

**Comment by Thutmose** [comment]
Hmm wont help, was a good idea to check it anyway, but unfortunatly it uses the hard-dependancy method, I am trying to use the soft method, so it would require a mod that can work without OC installed.

**Comment by XileForce** [comment]
Ah. I can't think of any off the top of my head. But I'll keep looking.

**Comment by Thutmose** [comment]
Well, for now I will disable the OC support then, I will add it back whenever OC starts working.  Testing the fixes for this and the joltik bug, will upload those shortly.

**Comment by XileForce** [comment]
Ok sounds good. Also I just looked and it appears EnderIO conduits work with OC. Here's the quote on the page.

Compact conduits (RF, items, fluids, redstone, AE2, OC, Mek gas), highly configurable machines, farms, powered tools and armor, not to mention stuff and things!

**Comment by Thutmose** [comment]
Thanks, I will look into that.  I have uploaded the versions with these fixes, I will close this issue, but it should still allow comments on it.

**Comment by Thutmose** [comment]
Hmm, I think that might just refer to the fact that OC supports anything that can transmit RF for a power source
