### ISSUE TITLE
Joltik fall damage

### ISSUE THREAD

**Issue by schindlershadow** [Thutmose/Pokecube#44]
#### Issue Description:
Modpack: Infinix test

#### What happens:

Joltik jumps so high that it constantly kills itself via fall damage.

#### What you expected to happen:

Joltik being immune to fall damage from at least the height of its jump.

#### Steps to reproduce:

1. Use a Joltik to battle anything
...

____
#### Affected Versions (Do *not* use "latest"):

Forge 1965
Pokecube core 3.2.6
Pokecube mobs 2.1.2
Pokecube revival 3.2.2

**Comment by Thutmose** [comment]
I will lower fall damage, this affects more than just joltik, seems pokemobs can jump quite a bit higher than vanilla mobs.

**Comment by Thutmose** [comment]
This should be reduced in 3.2.9 which I just uploaded, I greatly reduced falling damage for pokemobs, it should prevent most cases of them jumping and taking damage.
