### ISSUE TITLE
Magmar cannot evolve

### ISSUE THREAD

**Issue by schindlershadow** [Thutmose/Pokecube#45]
#### Issue Description:

Modpack: Infinix test
#### What happens:

Magmar traded with a flint and steel does not evolve. Also when sent out of pokeball holding a flint and steel it intently goes back, you then receive a "Magmar has grown to level $level" where $level is the level it is currently at (no change in level). If you send it out again it no longer has the flint and steel and it also did not evolve. (my magmar is level 5)
#### What you expected to happen:

After being traded with a flint and steel magmar evolves after being sent out.
#### Steps to reproduce:
1. Player A gives Magmar a flint and steel
2. Player A trades Magmar to Player B
3. Player B trades back Magmar to Player A
4. Player A sends out Magmar.
   ...

---
#### Affected Versions (Do _not_ use "latest"):

Forge 1965
Pokecube core 3.2.6
Pokecube mobs 2.1.2
Pokecube revival 3.2.2

**Comment by Thutmose** [comment]
I don't think his evolution is in the game yet, check to see if it is in the pokedex.

**Comment by Thutmose** [comment]
A list of pokemobs not currently modelled yet can be found here:

https://github.com/Thutmose/Pokecube-Models

Magmortar is there.

**Comment by Thutmose** [comment]
closing this issue as cleanup.
