### ISSUE TITLE
[1.9.4] Vivillon are invisible

### ISSUE THREAD

**Issue by XileForce** [Thutmose/Pokecube#47]
Vivillon appear to be invisible. Here's some sample pictures. No optifine.

http://imgur.com/a/XCcL0

Forge 1968
Pokecube core 3.26
Pokecube mobs 2.12
Pokecube revival 3.22

**Comment by schindlershadow** [comment]
I can see the outline of its model in the pokedex, but it is invisible in the world.

**Comment by Thutmose** [comment]
Do you know which ones are invisible? as in which biomes it is inivisible in? or is it all of them?

**Comment by XileForce** [comment]
I tried then out in several biomes and they were always invisible. Can't say if it was necessarily all biomes though.

**Comment by schindlershadow** [comment]
I have noticed a couple that were not invisible, they were all the pink color (Meadow?). I will take note of the biomes for the invisible ones and report back. I am unsure how the mapping work for the colors to the biomes but you can find all the colors here for referace http://bulbapedia.bulbagarden.net/wiki/Vivillon_(Pok%C3%A9mon)#Biology

**Comment by Thutmose** [comment]
I will look into it, I might have forgotten to sync some changes from the 1.8.9 texture handling code.?

You can find the list of Vivillons in pokecube here:
https://github.com/Thutmose/Pokecube-Models/blob/master/Gen_6/assets/pokecube_ml/models/pokemobs/Vivillon.xml#L7-L17

and the rules for spawning for them are here:
https://github.com/Thutmose/Pokecube-Models/blob/master/Gen_6/assets/pokecube_ml/models/pokemobs/Spewpa.xml#L9-L15

**Comment by Thutmose** [comment]
Ok, I have this fixed for the next release, note that some of the textures for vivillon seem to be missing the antenna stalks, but that should be fixed by one of the texturers at some point.

**Comment by Thutmose** [comment]
Uploaded Pokecube Core 3.2.10, it should close this issue.
