### ISSUE TITLE
NPC mobs are not rendering textures correctly

### ISSUE THREAD

**Issue by schindlershadow** [Thutmose/Pokecube#48]
#### Issue Description:
Modpack: Infinix test

#### What happens:

Look:
http://imgur.com/a/v0oH4
(also notice the missing space in "$trainer wants to battle!" in the 2nd image)

#### What you expected to happen:

textures to be correctly rendered

#### Steps to reproduce:

1. look at an NPC (trainer or market)
...

____
#### Affected Versions (Do *not* use "latest"):

Forge 1965
Pokecube core 3.2.9
Pokecube mobs 2.1.2
Pokecube revival 3.2.4

**Comment by Thutmose** [comment]
Ahh yes, I need to update some of the textures to the new standard, I think I forgot to update them with the rest, they used to use 1.7 player model, and I recently updated to using the 1.8 player model, and it seems some textures were missed.

I also noticed the missing space, I will see about fixing that.

**Comment by Thutmose** [comment]
Oh, also, where can I find this "Infinix test" modpack for testing things? incase there are any issues that might result from mod interactions?

**Comment by XileForce** [comment]
It's a modpack on the technic launcher. If you haven't used before basically downlaod the launcher here: http://technicpack.net/download then once you have it installed go to the modpacks tab, search infinix and then select infinix test. By default technic launcher only allocates 1g of ram. You can change that in the settings in upper right. I recommend above 3 if you can spare it. There's quite a few mods ATM.

**Comment by Thutmose** [comment]
I am working on the texture fixes for this issue, at some point I will see about downloading the technic thing, is there any way to get technic modpacks in the curse launcher?

**Comment by XileForce** [comment]
I've not used the curse launcher before so I couldn't say. once the pack is out of the testing stage I plan to have it on both though. Currently update it like 2x a day fixing things so dont wanna have to do that on multiple platforms xD. Also we have a discord, and could add you to the admin section if you ever need testing done more real time. no mic needed.

**Comment by Thutmose** [comment]
Testing the compiled fix for this now. should be uploaded shortly if it works.

**Comment by Thutmose** [comment]
Uploaded Pokecube Revival 3.2.5, it should close this issue.
