### ISSUE TITLE
Pokemon not attacking

### ISSUE THREAD

**Issue by schindlershadow** [Thutmose/Pokecube#49]
#### Issue Description:

Modpack: Infinix test
#### What happens:

After one attack pokemon sometimes stop attacking, the other pokemon then proceed to repeatedly attack your pokemon until it dies.
#### What you expected to happen:

Pokemon keeps attacking
#### Steps to reproduce:
1. tell a pokemon to attack
2. sometimes after the first attack, pokemon will not attack again.
   ...

---
#### Affected Versions (Do _not_ use "latest"):

Forge 1965
Pokecube core 3.2.9
Pokecube mobs 2.1.2
Pokecube revival 3.2.4

**Comment by Thutmose** [comment]
Hmm, I will look into this, something might be interfering with the combat AI.

**Comment by Thutmose** [comment]
Can you find a reliable way to replicate this? as in find some combination of pokemobs which results in this happening a lot?

**Comment by schindlershadow** [comment]
hmm, i'm not sure if there is one but I'll give it a try. stuck in work atm so it will be a few hours before I can test. A workaround is to just recall and resummon the pokemon.

**Comment by Thutmose** [comment]
whenever you get time then, see if you can find a pattern to when it occurs, it would help quite a lot with trying to find the root cause of the issue.

**Comment by jochuan** [comment]
Sometimes this happens in the 1.8.9 version too

**Comment by jochuan** [comment]
https://github.com/Thutmose/Pokecube/issues/27 
I think that it is related

**Comment by schindlershadow** [comment]
It happens very often, sometimes it also happens to the wild pokemon at the same time so you will have two Pokemon just staring at each other. I still cannot find a way to replicate it other than just attacking a bunch of pokemon.

**Comment by Thutmose** [comment]
Has this happened since i made the AI changes to make them use a different cooldown system?

**Comment by jochuan** [comment]
it still happens the others pokemons attack 7 times and my pokemon only attack one this happens mostly with magikarp and other slow pokemons

**Comment by mail2003** [comment]
my pokemon wont attack either. i send out my litten it wont attack

**Comment by Thutmose** [comment]
most of the related stuff has been re-written since this issue, remake if it occurs again.
