### ISSUE TITLE
[1.9.4] Cannot fly down with airborn pokemon

### ISSUE THREAD

**Issue by XileForce** [Thutmose/Pokecube#50]
What you expect to happen:
Clicking shift while riding a pokemon in flight makes it fly down.

What happens:
you dismount and fall 500 blocks to your death because you forgot to test flying down earlier.

Forge 1968
Pokecube core 3.2.9
Pokecube mobs 2.1.2
Pokecube revival 3.2.4

**Comment by XileForce** [comment]
woops i was just informed its ctrl! sorry!

**Comment by Thutmose** [comment]
No problem, It seems the shift thing is difficult to re-map, so I had to make it use ctrl instead, it does result in lots of deaths the first time though lol
