### ISSUE TITLE
[1.9.4] Pokemon re-deploy at full hp if they die while inventory is full.

### ISSUE THREAD

**Issue by XileForce** [Thutmose/Pokecube#51]
What you expect to happen:
The pokemon should return to your PC like the message indicates

What actually happens:
The pokemon immediately redeploys with full health.

Steps to reproduce:
throw a pokemon out. then fill inventory completely. have it get killed and it will respawn in the same location with full health again instantly.

Forge 1968
Pokecube core 3.2.9
Pokecube mobs 2.1.2
Pokecube revival 3.2.4

**Comment by Thutmose** [comment]
Hmm, does it also duplicate it? (ie does one also appear in PC)

This might also affect 1.8.9, I never tested this case in it.  Will work on fix asap.

**Comment by Thutmose** [comment]
Yep, it does duplicate lol,  It also works on just pressing recall.  I will see why.

**Comment by XileForce** [comment]
yea they duplicate just had him check

**Comment by XileForce** [comment]
lol I swear these guys find every corner case possible.

**Comment by Thutmose** [comment]
I have a fix done, I will look into a couple extra recall cases, then upload it.

**Comment by Thutmose** [comment]
I Uploaded Pokecube Core 3.2.11, It should fix this issue.
