### ISSUE TITLE
cheri and rawst berry trees do not grow

### ISSUE THREAD

**Issue by schindlershadow** [Thutmose/Pokecube#52]
#### Issue Description:
Modpack: Infinix test

#### What happens:

cheri and rawst berry trees do not grow, they reach mature but you get no berries and it does not grow into a tree.

#### What you expected to happen:

A tree to grow.

#### Steps to reproduce:

1. Plant cheri or rawst berry
2. Watch it not grow
...

____
#### Affected Versions (Do *not* use "latest"):

Forge 1965
Pokecube core 3.2.13
Pokecube mobs 2.1.2
Pokecube revival 3.2.5

**Comment by jochuan** [comment]
these berries do not become a tree they are small if you break the fruits on top of it it will drop berries

**Comment by Thutmose** [comment]
Confirmed that there is something wrong with some of the berries in the 1.9.4 version, working on fix now.

**Comment by schindlershadow** [comment]
is now working in:
Forge 1965
Pokecube core 3.3.0
Pokecube mobs 2.1.2
Pokecube revival 3.3.0
