### ISSUE TITLE
The Templates For Creating Your Own Pokemobs Need To Be Made

### ISSUE THREAD

**Issue by GreninjaGuy** [Thutmose/Pokecube#54]
The templates for creating your own pokemobs need to be made.

**Comment by TechDweebGaming** [comment]
How so? For Models? Textures? The physical pokemon in-game? What is it you would like a template for?

**Comment by Thutmose** [comment]
I will be making templates for resource packs

**Comment by Thutmose** [comment]
Over the next few days I will be going over the models to make sure the player is offset correctly when riding, when I do this I will try to also get a basic template made

**Comment by Thutmose** [comment]
Here is a sample resource pack for adding a completely new pokemob:

[Adding Mobs.zip](https://github.com/Thutmose/Pokecube/files/355357/Adding.Mobs.zip)

It adds Cube and Bigcube mobs, and defines stats, movesets, etc for them.

Similar resource packs can be used to add in any pokemon not defined in the database (ie gen 7).

If you want to add in pokemon that are in the database, you do something similar, except you do not need to include the <Pokemon> tags in the XML

**Comment by GreninjaGuy** [comment]
thx

**Comment by Thutmose** [comment]
This is now on the wiki here: https://github.com/Thutmose/Pokecube/wiki/How-to-add-Custom-Pok%C3%A9mobs-to-Pok%C3%A9cube
