### ISSUE TITLE
Using the "pokemob attack" key on a block gives you a strange message

### ISSUE THREAD

**Issue by schindlershadow** [Thutmose/Pokecube#56]
#### Issue Description:
Modpack: Infinix test

#### What happens:

Using the "pokemob attack" key on a block gives you a strange message in the battle log:
http://i.imgur.com/S4KGn1X.png

looks like the block's toString return or something, should be grabbing just the name.

#### What you expected to happen:

no message in the battle log or name of block like "$name cannot attack $block!"

#### Steps to reproduce:

1. Use the "pokemob attack" key on a block
...

____
#### Affected Versions (Do *not* use "latest"):

Forge 1965
Pokecube core 3.3.0
Pokecube mobs 2.1.2
Pokecube revival 3.3.0

**Comment by Thutmose** [comment]
That is an issue with how I was getting the pokemob's name in that case. fixed for next version.

**Comment by Thutmose** [comment]
fixed in 3.3.1
