### ISSUE TITLE
Talonflame and all pre-evolves models are not centered correctly

### ISSUE THREAD

**Issue by schindlershadow** [Thutmose/Pokecube#57]
#### Issue Description:
Modpack: Infinix test

#### What happens:

Talonflame and all pre-evolves models are not centered correctly:
http://i.imgur.com/xM2lwxZ.png

It's hitbox is in the correct place.

#### What you expected to happen:

Centered model like the rest of the pokemon.

#### Steps to reproduce:

1. look at a Talonflame or any of its pre-evolves
...

____
#### Affected Versions (Do *not* use "latest"):

Forge 1965
Pokecube core 3.3.0
Pokecube mobs 2.1.2
Pokecube revival 3.3.0

**Comment by Thutmose** [comment]
Fixed in Pokecube Mobs 2.1.3
