### ISSUE TITLE
Dispensers fail to acknowledge vertical facing dispensers

### ISSUE THREAD

**Issue by 13rett** [Thutmose/Pokecube#6]
If you make a dispenser pointing strait up (or down) then the ball is thrown south instead of up (or down).

**Comment by Thutmose** [comment]
right, need to add those directions in, for some reason, it is currently only coded for horizontal plane.  Will get that done shortly.

**Comment by Thutmose** [comment]
Ok, fix for this issue was committed here, I will close this issue once the next version is uploaded to curseforge.

https://github.com/Thutmose/Pokecube/commit/f4b1c7cea5521288e4abf34fa9c6bf33fbb2997e
