### ISSUE TITLE
[1.9.4] Using pokedex on pokemon adds an r to the end of their name

### ISSUE THREAD

**Issue by XileForce** [Thutmose/Pokecube#64]
What you expect to happen:
nothing

What happens:
An r gets added to the end of the pokemon. Poor Raichur :( luckily you can edit the name and it fixes it until the next time.

Forge 1969
Pokecube core 3.3.1
Pokecube mobs 2.1.2
Pokecube revival 3.3.1

**Comment by Thutmose** [comment]
Ahh, that explains why I had a mew?r while testing thing earlier!  I will see about fixing that tomorrow.
