### ISSUE TITLE
Server crash, not possible to reboot.

### ISSUE THREAD

**Issue by doctorkreger** [Thutmose/Pokecube#66]
#### Issue Description:
Server had been running for a while with no issues, suddenly crashed. 

May be coincidental, but I was harvesting berries near some some newly grown oran trees and the crash log mentions berries!

I removed the mods, reloaded the world to finalize the removal of the old blocks, then reloaded the server again, this time with pokemods.  The server booted, but crashed again, with the same error log when a player attempted a login.
 ------------------------------------------------------------------------------------------------------------------------------
WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.9.4-0.4.0.26-alpha.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 6/25/16 11:58 AM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
        at pokecube.core.PokecubeItems.getStack(PokecubeItems.java:386)
        at pokecube.core.PokecubeItems.getStack(PokecubeItems.java:381)
        at pokecube.core.items.berries.BerryManager.getBerryItem(BerryManager.java:165)
        at pokecube.core.blocks.berries.BlockBerryFruit.getBerryStack(BlockBerryFruit.java:141)
        at pokecube.core.blocks.berries.BlockBerryFruit.getDrops(BlockBerryFruit.java:117)
        at pokecube.core.blocks.berries.BlockBerryFruit.func_180653_a(BlockBerryFruit.java:84)
        at net.minecraft.block.Block.func_176226_b(Block.java:531)
        at net.minecraft.block.BlockBush.func_176475_e(BlockBush.java:65)
        at net.minecraft.block.BlockBush.func_180650_b(BlockBush.java:58)
        at net.minecraft.block.Block.func_180645_a(Block.java:474)
        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:470)
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:219)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:696)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:385)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
        at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
        at pokecube.core.PokecubeItems.getStack(PokecubeItems.java:386)
        at pokecube.core.PokecubeItems.getStack(PokecubeItems.java:381)
        at pokecube.core.items.berries.BerryManager.getBerryItem(BerryManager.java:165)
        at pokecube.core.blocks.berries.BlockBerryFruit.getBerryStack(BlockBerryFruit.java:141)
        at pokecube.core.blocks.berries.BlockBerryFruit.getDrops(BlockBerryFruit.java:117)
        at pokecube.core.blocks.berries.BlockBerryFruit.func_180653_a(BlockBerryFruit.java:84)
        at net.minecraft.block.Block.func_176226_b(Block.java:531)
        at net.minecraft.block.BlockBush.func_176475_e(BlockBush.java:65)
        at net.minecraft.block.BlockBush.func_180650_b(BlockBush.java:58)
        at net.minecraft.block.Block.func_180645_a(Block.java:474)
        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:470)
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:219)

-- Affected level --
Details:
        Level name: world
        All players: 1 total; [EntityPlayerMP['LadySinger'/172, l='world', x=198.50, y=82.00, z=231.50]]
        Chunk stats: ServerChunkCache: 442 Drop: 0
        Level seed: 1977900120
        Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
        Level generator options:
        Level spawn location: World: (196,82,228), Chunk: (at 4,5,4 in 12,14; contains blocks 192,0,224 to 207,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
        Level time: 2706732 game time, 2761352 day time
        Level dimension: 0
        Level storage version: 0x04ABD - Anvil
        Level weather: Rain time: 37826 (now: false), thunder time: 117298 (now: false)
        Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:696)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:385)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
        at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
        Minecraft Version: 1.9.4
        Operating System: Windows 7 (amd64) version 6.1
        Java Version: 1.8.0_91, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 2475558744 bytes (2360 MB) / 2998927360 bytes (2860 MB) up to 2998927360 bytes (2860 MB)
        JVM Flags: 2 total; -Xmx3072M -Xms3072M
        IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
        FML: MCP 9.28 Powered by Forge 12.17.0.1976 55 mods loaded, 55 mods active
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
        UCHIJAAAA       mcp{9.19} [Minecraft Coder Pack] (minecraft.jar)
        UCHIJAAAA       FML{8.0.99.99} [Forge Mod Loader] (forge-1.9.4.3.jar)
        UCHIJAAAA       Forge{12.17.0.1976} [Minecraft Forge] (forge-1.9.4.3.jar)
        UCHIJAAAA       actuallyadditions{1.9.4-r45} [Actually Additions] (ActuallyAdditions-1.9.4-r45.jar)
        UCHIJAAAA       alt{1.05} [Additional Loot Tables] (AdditionalLootTables_1.9.4-1.05.jar)
        UCHIJAAAA       adobeblocks{6.0.0.13} [Adobe Blocks 2] (AdobeBlocks-6.0.0.13.jar)
        UCHIJAAAA       adobeblocksvc{3.2-fork} [Adobe Blocks Version Checker] (AdobeBlocks-6.0.0.13.jar)
        UCHIJAAAA       basemetals{2.3.2} [Base Metals] (BaseMetals_1.9.4-2.3.2.6.jar)
        UCHIJAAAA       Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0 (1).jar)
        UCHIJAAAA       BiomesOPlenty{4.1.0.2029} [Biomes O' Plenty] (BiomesOPlenty-1.9.4-4.1.0.2029-universal.jar)
        UCHIJAAAA       JEI{3.6.7.216} [Just Enough Items] (jei_1.9.4-3.6.7.216.jar)
        UCHIJAAAA       BloodMagic{1.9.4-2.0.1-40} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.0.1-40.jar)
        UCHIJAAAA       Botania{r1.8-310} [Botania] (Botania-unofficial.r1.8-310.jar)
        UCHIJAAAA       Chameleon{1.9-2.1.4} [Chameleon] (Chameleon-1.9-2.1.4.jar)
        UCHIJAAAA       claycraft{2.0} [Claycraft] (Claycraftmod v2.0 - MC1.9.4 Forge.jar)
        UCHIJAAAA       nt{1.0} [Climbing Claw] (ClimbingClawV1.0[1.9.4].jar)
        UCHIJAAAA       cookingforblockheads{3.1.26} [Cooking for Blockheads] (CookingForBlockheads-mc1.9.4-3.1.26.jar)
        UCHIJAAAA       MineTweaker3{3.0.9} [MineTweaker 3] (CraftTweaker-1.9-3.0.9.jar)
        UCHIJAAAA       endercore{1.9.4-0.4.0.26-alpha} [EnderCore] (EnderCore-1.9.4-0.4.0.26-alpha.jar)
        UCHIJAAAA       EnderIO{1.9.4-3.0.0.45_alpha} [Ender IO] (EnderIO-1.9.4-3.0.0.45_alpha.jar)
        UCHIJAAAA       IronChest{6.0.146.788} [Iron Chest] (ironchest-1.9.4-6.0.146.788.jar)
        UCHIJAAAA       moreanvils{6.0.1.10} [More Anvils] (MoreAnvils-6.0.1.10.jar)
        UCHIJAAAA       xreliquary{1.9.4-1.3.2.390} [Reliquary] (Reliquary-1.9.4-1.3.2.390.jar)
        UCHIJAAAA       fluidity{6.0.0.6} [Fluidity] (Fluidity-6.0.0.6.jar)
        UCHIJAAAA       forestry{5.0.23.170} [Forestry] (forestry_1.9.4-5.0.23.170.jar)
        UCHIJAAAA       substratum{1.4.0.1} [Substratum] (Substratum-1.9.4-1.4.0.1 (1).jar)
        UCHIJAAAA       foundry{2.0.0.0-beta5} [Foundry] (Foundry-1.9.4-2.0.0.0-beta5.jar)
        UCHIJAAAA       hempfarmer{1.9.4-1968-1.51} [HempFarmer] (hempfarmer-1.9.4-1968-1.51.jar)
        UCHIJAAAA       hopperducts{1.4.7} [Hopper Ducts] (hopperducts-mc1.9.4-1.4.7 (1).jar)
        UCHIJAAAA       inventorysorter{0.9.1+41} [Simple Inventory sorting] (inventorysorter-1.9.4-0.9.1+41.jar)
        UCHIJAAAA       mantle{1.9.4-0.10.2.jenkins149} [Mantle] (Mantle-1.9.4-0.10.2.jar)
        UCHIJAAAA       modernmetals{0.11.0} [Modern Metals] (ModernMetals-0.11.0.jar)
        UCHIJAAAA       moreanvilsvc{3.2} [More Anvils Version Checker] (MoreAnvils-6.0.1.10.jar)
        UCHIJAAAA       yurtmod{5.01} [Nomadic Tents] (NomadicTents[1.9.4]-5.01.jar)
        UCHIJAAAA       orespawn{1.0.3} [Ore Spawn] (OreSpawn_1.9.4-1.0.3.jar)
        UCHIJAAAA       harvestcraft{1.9.4-pre} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4a.jar)
        UCHIJAAAA       thutcore{3.1.2} [ThutCore] (thutcore-1.9.4-3.1.2.jar)
        UCHIJAAAA       NBTEditpqb{1.8.9-1.0} [In-game NBTEdit - Pokecube Edition] (Pokecube Core-3.3.1.jar)
        UCHIJAAAA       pokecube{3.3.1} [PokΘcube Core] (Pokecube Core-3.3.1.jar)
        UCHIJAAAA       pokecube_ml{0.1.0} [Pokecube Model Loader] (Pokecube Core-3.3.1.jar)
        UCHIJAAAA       pokecube_mobs{2.1.2} [PokΘcube Mobs] (Pokecube Mobs-2.1.2.jar)
        UCHIJAAAA       pokecube_adventures{3.3.1} [PokΘcube Revival] (Pokecube Revival-3.3.1.jar)
        UCHIJAAAA       pokecube_compat{1.0} [Pokecube Compat] (Pokecube Revival-3.3.1.jar)
        UCHIJAAAA       Roguelike{1.5.3} [Roguelike Dungeons] (RoguelikeDungeons-1.9.4-1.5.3.jar)
        UCHIJAAAA       roots{0.1} [Roots] (roots-0.005.jar)
        UCHIJAAAA       AS_Ruins{16.1} [Ruins Spawning System] (Ruins-1.9.4.jar)
        UCHIJAAAA       SaltMod{1.8.c} [Salty Mod] (SaltyMod-1.9.4-1.8.c_beta-3.jar)
        UCHIJAAAA       slabcraftmod{5.0} [Slabcraft] (Slabcraftmod v5.0 - MC1.9.4 Forge.jar)
        UCHIJAAAA       staircraftmod{5.0} [Staircraft] (Staircraftmod v5.0 - MC1.9.4 Forge.jar)
        UCHIJAAAA       storagenetwork{1.12.0} [Storage Network] (StorageNetwork-1.9.4-1.12.0.jar)
        UCHIJAAAA       tconstruct{1.9.4-2.3.3.jenkins263} [Tinkers' Construct] (TConstruct-1.9.4-2.3.3.jar)
        UCHIJAAAA       thuttech{3.0.2} [Thut's Tech] (thuttech-3.0.2.jar)
        UCHIJAAAA       torcharrowsmod{1.9.4-2} [TorchArrowsMod] (torcharrows-1.9.4-2.jar)
        UCHIJAAAA       AS_UpdateCheck{1.1.7} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.9.4.jar)
        UCHIJAAAA       wallcraftmod{5.0} [Wallcraft] (Wallcraftmod v5.0 - MC1.9.4 Forge.jar)
        Loaded coremods (and transformers):
EnderCorePlugin (EnderCore-1.9.4-0.4.0.26-alpha.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
        Pulsar/tconstruct loaded Pulses:
                - TinkerCommons (Enabled/Forced)
                - TinkerWorld (Enabled/Not Forced)
                - TinkerTools (Enabled/Not Forced)
                - TinkerSmeltery (Enabled/Not Forced)
                - TinkerGadgets (Enabled/Not Forced)
                - TinkerOredict (Enabled/Forced)
                - TinkerIntegration (Enabled/Forced)
                - TinkerFluids (Enabled/Forced)
                - TinkerMaterials (Enabled/Forced)

        EnderIO: No known problems detected.
        Profiler Position: N/A (disabled)
        Player Count: 1 / 20; [EntityPlayerMP['LadySinger'/172, l='world', x=198.50, y=82.00, z=231.50]]
        Is Modded: Definitely; Server brand changed to 'fml,forge'
        Type: Dedicated Server (map_server.txt)

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:3.3.1
- Pokecube Revival (if applicable):3.3.1
- Pokecube Mobs (if applicable):2.1.2
- Minecraft: 1.9.4
- Forge:12.17.0.1976

**Comment by Thutmose** [comment]
I will have that fixed shortly, seems a temporary fix is to disable plant growth.

**Comment by doctorkreger** [comment]
Thank you for the quick response! 

Another workaround is to disable mod, fill the plant airspace with a different block, then reload.  A little labor intensive, but it works!

**Comment by Thutmose** [comment]
ok, I am working on some GUI stuff, hopefully I can get the fix for this out in a couple hours.

**Comment by Thutmose** [comment]
Hopefully finializing the fixes for this now

**Comment by doctorkreger** [comment]
Excellent. I posted a few other smaller details to take a look at as well. Thanks for your efforts!

**Comment by Thutmose** [comment]
This should be fixed in 3.3.3/4.0.3 (1.9.4/1.10)

They have just been uploaded to curse, should be available shortly.  Reopen this issue if those fixes didn't work for you.
