### ISSUE TITLE
Pokedex Biome Pokemon Not Displaying in Multiplayer

### ISSUE THREAD

**Issue by 2piradians** [Thutmose/Pokecube#67]
#### Issue Description:

Biome Pokemon list in Pokedex does not display on server unless you load up a new world in single player.

#### What happens:

Logged into multiplayer server without going to single player.

![2016-06-25_13 17 28](https://cloud.githubusercontent.com/assets/20136903/16358382/320ceef6-3ad7-11e6-83e8-0fbfc98541e6.png)

#### What you expected to happen:

Loaded a world in single player and checked pokedex.

![2016-06-25_13 07 22](https://cloud.githubusercontent.com/assets/20136903/16358383/371640aa-3ad7-11e6-909c-511c4e869de1.png)

#### Steps to reproduce:

1. Start game.
2. Login to Multiplayer server.
3. Check Pokedex biome list.
...

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core: 4.0.2
- Pokecube Revival (if applicable): 4.0.2
- Pokecube Mobs (if applicable): 2.1.3
- Minecraft: 1.10/1.9.4
- Forge: 12.18.0.1986

**Comment by Thutmose** [comment]
got this fixed for next release.

**Comment by Thutmose** [comment]
Fixed in 3.3.3/4.0.3
