### ISSUE TITLE
Krabby too large

### ISSUE THREAD

**Issue by doctorkreger** [Thutmose/Pokecube#68]
#### Issue Description:
Krabby rendering too large.

#### What happens:
It appears Krabby always spawns much larger than he should be.  In order to hit one, you have to walk inside of its model and attack where the normal-sized Krabby would be.

#### What you expected to happen:
Smaller Krabby/ matching hitbox if intended size.

#### Steps to reproduce:
Play game until Krabby spawns.
..

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:3.3.2
- Pokecube Revival (if applicable):3.3.2
- Pokecube Mobs (if applicable):2.1.2
- Minecraft: 1.9.4 Server
- Forge:1.9.4-x.1976

**Comment by Thutmose** [comment]
What version of ThutCore?

**Comment by Thutmose** [comment]
![image](https://cloud.githubusercontent.com/assets/2363472/16359454/e2515e66-3b02-11e6-8ffe-4e7eafa0a11a.png)

This is what it looks like for me, using thutcore-1.9.4-3.1.3

**Comment by XileForce** [comment]
can confirm this is fixed in the latest versions. The krabby used to be about 12x bigger than that in game.

**Comment by schindlershadow** [comment]
also kingler used to be so large that only his legs rendered

**Comment by Thutmose** [comment]
ya, that was a ThutCore glitch

**Comment by doctorkreger** [comment]
I will try that this evening, it sounds like everything is as it should be.
