### ISSUE TITLE
PC Gui - Always shows "Private"

### ISSUE THREAD

**Issue by doctorkreger** [Thutmose/Pokecube#70]
#### Issue Description:
PC always shows "Private," not much too it.

#### What happens:
Regardless of being on the public or private pages of the PC, it always reports "Private"

#### What you expected to happen:
The accurate listing.

#### Steps to reproduce:

Use machine, switch tabs, observe lack of change.
...

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:3.3.2
- Pokecube Revival (if applicable):3.3.2
- Pokecube Mobs (if applicable):2.1.2
- Minecraft: 1.9.4 Server
- Forge:1.9.4-x.1976

**Comment by Thutmose** [comment]
I Will look into this shortly.

**Comment by Thutmose** [comment]
I have this fixed internally, it will be fixed for next release.
