### ISSUE TITLE
(Suggestion's)

### ISSUE THREAD

**Issue by Karagra** [Thutmose/Pokecube#71]
(Suggestion)
PokeCenter Doctor with same interface as healer for cosmetic
(Dyeable Items)
Bags,Rings
Mega Evo Neckless - World need model
Mega Evo Hats - Would need model

**Comment by 2piradians** [comment]
In the Pokedex, add a reverse of the biome search.
So instead of looking at what pokemon spawn in a certain biome, we can search for what biomes a certain pokemon spawns in.

**Comment by jochuan** [comment]
Maybe adding sounds for attacks like tackle and others, mega evo hats would be strange but mega evo gloves like the one that korrina uses would be cool i think that i can make the nurse skin but first i will give priority to the trainers skins

**Comment by jochuan** [comment]
i am working in the nurse skin right now thutmose is possible to your system to render skins that are bigger than the default ones ?

**Comment by Thutmose** [comment]
So long as the texture proportions are the same,the size of the texture shouldn't matter

**Comment by jochuan** [comment]
i made the nurse skin
![nursejoy](https://cloud.githubusercontent.com/assets/11268912/17645990/c5c9dd1c-618c-11e6-85ec-1cb738f40c33.png)

**Comment by Thutmose** [comment]
Ok, I will make it so when the professor is turned into a healer, it switches to that skin

**Comment by jochuan** [comment]
would be cool if you could make nurse trainers that would heal your pokemon if you beat them

**Comment by Thutmose** [comment]
hmm, I can see about that, I might be able to make them act as healers when on cooldown between battles?

**Comment by jochuan** [comment]
and making them spawn far away from the pokecenters

**Comment by Thutmose** [comment]
closing this, as everything in it is in, the necklaces are in ThutBling.
