### ISSUE TITLE
Metronome needs investigating

### ISSUE THREAD

**Issue by Karagra** [Thutmose/Pokecube#72]
#### What happens:

Game Crashes when using Metranome

http://pastebin.com/yMHdaCpB
#### What you expected to happen:

Not to crash
#### Steps to reproduce:
1. Send out a Metranome

---
#### Affected Versions (Do _not_ use "latest"):
- Minecraft 1.10

**Comment by schindlershadow** [comment]
What pokemon is Metronome? do you mean the move Metronome? http://bulbapedia.bulbagarden.net/wiki/Metronome

**Comment by Thutmose** [comment]
Last time I tested it worked, so closing this issue, re-make it if it happens again.
