### ISSUE TITLE
[Suggestion]Graves mod compatibility

### ISSUE THREAD

**Issue by XileForce** [Thutmose/Pokecube#73]
Currently if you use a graves mod, the pokecubes get put in the graves rather than returning to the pc. this is usually okay for singleplayer worlds, but on servers it can become problematic if you die and someone else retrieves your grave even though they cant use the pokecubes. I was wondering if there was a way to make the pokecubes return to your pc on death despite a mod like graves trying to preserve them on the grave.

**Comment by Thutmose** [comment]
I can try to see something about it, do you know if graves is open source?

**Comment by XileForce** [comment]
yea heres a link to their github. https://github.com/FireBall1725/Graves

**Comment by XileForce** [comment]
Also just realized when i died, it not only stayed in the grave, but also duplicated in my pc.

**Comment by Thutmose** [comment]
Looking at the github you linked, I might be able to get something done to fix this on my end.  I will look into it tomorrow.

**Comment by Thutmose** [comment]
looking into this, it might not be that easy, i could try to make it so you can disable the auto-pc thing? players could get someone else's pokemobs, but if they tossed them, or otherwise, they would go to original owner's pc

**Comment by XileForce** [comment]
Hmm that would resolve the duping issue, the only thing I'm worried about is someone just sticking your lvl 100 legendary in a chest somewhere. Is there a way to make the pokecube return to the pc maybe ads soon as it is dropped? Like for instance when the grave is broken and it is no longer in an inventory it returns to the pc? That way nobody could pick them up. It would still have to be disabled upon death due to duping though. Idk just an idea.

**Comment by Thutmose** [comment]
I can see if the player pickup event is called when graves drops, in that case, I can possibly send to PC if wrong owner.

**Comment by XileForce** [comment]
That would also work as far as I can tell. In fact that would be optimal. Then the owner could still retrieve from the grave but others couldn't. My only worry would be someone burning it or something on the ground (ppl are mean like that sometimes :/ ) but I'm not sure there's really any way to get around that.

**Comment by Thutmose** [comment]
So as mentioned in discord, the next release will fix the dupe bug, but will not be able to fix the items going into the breaker's inventory, as the graves mod you linked directly places them there.

Any graves mod that just drops the items however, will result in the pokecubes going to their owner's PC, rather than going into the inventory of the breaker (unless the breaker owns the pokecubes)

I will probably keep this issue open after I commit those changes, but I will remove the Major Bug tag, and replace it with Minor Bug or something.

**Comment by XileForce** [comment]
Ok I'll give it a shot once it's up

**Comment by Thutmose** [comment]
Uploaded the fix for this as 4.1.2/3.4.2
