### ISSUE TITLE
[1.9.4] PokeCubes are not used up.

### ISSUE THREAD

**Issue by XileForce** [Thutmose/Pokecube#74]
What you expect to happen:
Throw a pokecube and 1 is removed from my inventory.

What happens:
I throw a pokecube and it captures a pokemon and does not get removed from my inventory.

Steps to reproduce:
Take a pokecube(doesnt matter what kind, I tried greatballs too) throw it at a pokemon. regardless of whether or not it is successful, the cube does not get removed from your inventory. Basically its infinite ammo cheat code.

PokeCube Core: 3.3.2
PokeCube Mobs: 2.1.3
PokeCube Revival: 3.3.2
ThutCore: 3.1.3
Forge: 1969

**Comment by Thutmose** [comment]
that was fixed in Pokecube Core 3.3.3

**Comment by XileForce** [comment]
my bad I should have looked!
