### ISSUE TITLE
Pokecube Eggs not hatching

### ISSUE THREAD

**Issue by doctorkreger** [Thutmose/Pokecube#75]
#### Issue Description:
Since the upgrade to 3.3.2 I have not had any of my eggs hatch.  I have amassed several dozen in a pen for observation, and they have been down for well over an hour now.

#### What happens:
Eggs appear to not be hatching.

#### What you expected to happen:
Eggs to hatch in a way similar to previous releases.

#### Steps to reproduce:

1.Place egg
2.Wait

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:3.3.6
- Pokecube Revival (if applicable):3.3.6
- Pokecube Mobs (if applicable):2.1.2
- Minecraft: 1.9.4
- Forge:1.9.4-x.1976

**Comment by Thutmose** [comment]
Could it be that there were too many mobs nearby? eggs will not hatch in that situation

**Comment by doctorkreger** [comment]
I will test this in the morning. Thanks for the info.

**Comment by doctorkreger** [comment]
This worked, cleaned up the sea of eggs.
