### ISSUE TITLE
(Suggestion) Config changes to better allow for increased intermod pvp as well as warning systems for hunger and drowning

### ISSUE THREAD

**Issue by banjomarx** [Thutmose/Pokecube#77]
It would be immensely helpful to have the following in order to allow for better intermod pvp (in particular vs quantum)

A config option to allow a certain amount of pokemon damage versus players to be treated as magic damage (such as with the vanilla instant damage potion)

A config option to allow wild pokemon and owned pokemon to have different damage caps vs players

A config option to allow wild pokemon and owned pokemon to have a different damage SCALING vs players (such as owned pokemon do 35% damage to players)

In addition It would be incredibly helpful to have a warning system that gives notifications when your pokemon is drowning and/or starving

**Comment by Thutmose** [comment]
For the magic thing, would a certain fraction be converted to magic? or would a flat amount be?

Say the following situation:
A pokemob uses an attack that should do 100 damage.
Cap to player is set to 10, and scaling set to 20%.
Scaling would scale the damage to 20 damage, then cap caps it to 10, which is then applied to the player as a pokemob damage source (not set to bypass armour).

Should I have a fraction of that 10 set to bypass? or should I have a second cap/scaling for a section to bypass?

**Comment by banjomarx** [comment]
ya i guess it would make most sense to have a fraction of the 10, in otherwords have the % come into play after the capping

**Comment by banjomarx** [comment]
another possibility i guess would be to have a separate cap for the magic dmg

**Comment by Thutmose** [comment]
ok, I will have the fraction come in after the capping, I do need to see where I should do the magic damage though, A seperate cap would probably be good, not really sure how I want to split the damage though

**Comment by Thutmose** [comment]
I have fixed the drowning now (they should swim like vanilla mobs do now) and added in message for starving, I also added in the requested configs, I will close this issue now, make a new one if you have any more suggestions, or re-open this one if you need the added configs tweaked any,
