### ISSUE TITLE
[1.9.4] Pokemon Spawning At Lvl 50 only a few blocks from spawn

### ISSUE THREAD

**Issue by XileForce** [Thutmose/Pokecube#82]
Can confirm that this occurs on both server, and in singleplayer across multiple maps. Basically the pokemobs spawning are lvl 50 even like 100 blocks from spawn. This is using both the default spawn function as well as the linear one. Occasionaly they also spawn at lvl 0 even thousands of blocks from spawn which is odd.

PokeCube Core: 3.3.8
PokeCube Mobs: 2.1.3
PokeCube Revival: 3.3.7
ThutCore: 3.1.5
Forge: 1976

**Comment by Thutmose** [comment]
can you include the pokecube.cfg?

**Comment by XileForce** [comment]
sure here it is http://pastebin.com/rJBhJMhU

**Comment by XileForce** [comment]
Config issue closed.

**Comment by XileForce** [comment]
hmm even with fresh configs it still seems to occur on latest versions. It seems like theres mobs spawning normally then suddenly a cluster of lvl 50s then a few level 1-5s and then some more lvl 50s only 100 or so blocks from spawn. I'm stumped.
