### ISSUE TITLE
[1.9.4] (Suggestion) have Pokémon on guard use strongest attack.

### ISSUE THREAD

**Issue by XileForce** [Thutmose/Pokecube#83]
Currently Pokémon on guard seem to use whatever their first move is. If you enable auto move selection in the config file it will auto use whatever the strongest move is. I was wondering if it would be possible to apply this logic to any Pokémon on guard even when the config option for auto move selection is disabled.

**Comment by Thutmose** [comment]
They should already do that...

**Comment by XileForce** [comment]
Hmm... I'll test it again. Maybe banjo messed up when we tried it before.
