### ISSUE TITLE
EntityHasPokemobs server crash

### ISSUE THREAD

**Issue by schindlershadow** [Thutmose/Pokecube#84]
Server keeps crashing when some players join:
http://pastebin.com/GPy866pZ

PokeCube Core: 3.4.4
PokeCube Mobs: 2.1.4
PokeCube Revival: 3.4.3
ThutCore: 3.1.6
Forge: 1976

**Comment by Thutmose** [comment]
This should have been fixed in revival 3.4.4, please let me know if it was not.
