### ISSUE TITLE
Trainers without Pokemon still want to battle

### ISSUE THREAD

**Issue by doctorkreger** [Thutmose/Pokecube#89]
#### Issue Description:
They will still show console messages of "____ wants to battle."  Emerald rewarded after trainer realizes lack of monsters.  Can be a way to obtain many emeralds from one trainer.

#### What you expected to happen:
Cool down on aggression from trainers, ineligibility for another emerald.

#### Steps to reproduce:

1. Battle trainer
2.Defeat his monsters
3.Remain in area.
...

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:3.4.6
- Pokecube Revival (if applicable):3.4.7
- Pokecube Mobs (if applicable):2.1.4
- Minecraft: 1.9.4
- Forge:1.9.4-x.1976

**Comment by Thutmose** [comment]
this will be fixed asap, I probably forgot to apply the cooldown properly.

**Comment by Thutmose** [comment]
seems this issue only occurs if you attack them with your own pokemobs, which I hadn't tested well.  It will be fixed in next release.

**Comment by Thutmose** [comment]
Should be fixed in Revival 3.4.8/4.1.8
