### ISSUE TITLE
Occasionally cannot summon pokemon.

### ISSUE THREAD

**Issue by doctorkreger** [Thutmose/Pokecube#90]
#### Issue Description:
A player on my server often find himself in a situation where he will throw a pokecube, his pokemon summons, then immediately disappears.   Having someone else attack him with a pokemob, or summoning one near him, seems to temporarily fix the problem.

#### What you expected to happen:
Pokemon to remain active.

#### Steps to reproduce:

1. Have the player throw pokecube
2.Watch the auto return

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:3.4.6
- Pokecube Revival (if applicable):3.4.7
- Pokecube Mobs (if applicable):2.1.4
- Minecraft: 1.9.4
- Forge:1.9.4-x.1976

**Comment by Thutmose** [comment]
when it disappears, does it recall to pokecube? or does it just not show up in world?

**Comment by doctorkreger** [comment]
It immediately recalls to cube.

**Comment by Thutmose** [comment]
Hmm, can you get it to replicate for any other player? it is any of his pokemobs or just one?

**Comment by doctorkreger** [comment]
Any mobs. It does happen for other players, but only about once each, whereas the main plAyer sees it often. This playershould most unique quality is use of tinkers slime shot and boots, and having the most captured mobs.

**Comment by XileForce** [comment]
Just curious but does he have auto recall turned on in the config files? We had this enabled and the same issue. Since disabling it, the issue appears resolved.

**Comment by doctorkreger** [comment]
I will have him check!

**Comment by doctorkreger** [comment]
Seems to have resolved the problem.
