### ISSUE TITLE
Server Won't Boot, Pokecube Core not initialized

### ISSUE THREAD

**Issue by doctorkreger** [Thutmose/Pokecube#91]
#### Issue Description:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  AppleCore (AppleCore-mc1.9.4-1.3.4.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  EnderCorePlugin (EnderCore-1.9.4-0.4.0.26-alpha.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 7/1/16 8:14 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: Could not initialize class pokecube.core.PokecubeCore
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:179)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:555)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:91)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:321)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:118)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:429)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class pokecube.core.PokecubeCore
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:474)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:524)
	... 5 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.9.4
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3141446848 bytes (2995 MB) / 4116185088 bytes (3925 MB) up to 4116185088 bytes (3925 MB)
	JVM Flags: 2 total; -Xmx4096M -Xms4096M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.28 Powered by Forge 12.17.0.1976 61 mods loaded, 61 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9.4.3.jar) 
	UC	Forge{12.17.0.1976} [Minecraft Forge] (forge-1.9.4.3.jar) 
	UC	actuallyadditions{1.9.4-r45} [Actually Additions] (ActuallyAdditions-1.9.4-r45.jar) 
	UC	alt{1.05} [Additional Loot Tables] (AdditionalLootTables_1.9.4-1.05.jar) 
	UC	adobeblocks{6.0.0.13} [Adobe Blocks 2] (AdobeBlocks-6.0.0.13.jar) 
	UC	adobeblocksvc{3.2-fork} [Adobe Blocks Version Checker] (AdobeBlocks-6.0.0.13.jar) 
	UC	JEI{3.6.7.216} [Just Enough Items] (jei_1.9.4-3.6.7.216.jar) 
	UC	AppleCore{1.3.4} [AppleCore] (AppleCore-mc1.9.4-1.3.4.jar) 
	UC	basemetals{2.3.2} [Base Metals] (BaseMetals_1.9.4-2.3.2.6.jar) 
	UC	Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0 (1).jar) 
	UC	BiomesOPlenty{4.1.0.2033} [Biomes O' Plenty] (BiomesOPlenty-1.9.4-4.1.0.2033-universal.jar) 
	UC	BloodMagic{1.9.4-2.0.2-48} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.0.2-48.jar) 
	UC	Botania{r1.8-312} [Botania] (Botania-unofficial.r1.8-312.jar) 
	UC	Chameleon{1.9-2.1.4} [Chameleon] (Chameleon-1.9-2.1.4.jar) 
	UC	claycraft{2.0} [Claycraft] (Claycraftmod v2.0 - MC1.9.4 Forge.jar) 
	UC	nt{1.0} [Climbing Claw] (ClimbingClawV1.0[1.9.4].jar) 
	UC	cookingforblockheads{3.1.26} [Cooking for Blockheads] (CookingForBlockheads-mc1.9.4-3.1.26.jar) 
	UC	MineTweaker3{3.0.9} [MineTweaker 3] (CraftTweaker-1.9-3.0.9.jar) 
	UC	endercore{1.9.4-0.4.0.26-alpha} [EnderCore] (EnderCore-1.9.4-0.4.0.26-alpha.jar) 
	UC	EnderIO{1.9.4-3.0.0.46_alpha} [Ender IO] (EnderIO-1.9.4-3.0.0.46_alpha.jar) 
	UC	IronChest{6.0.146.788} [Iron Chest] (ironchest-1.9.4-6.0.146.788.jar) 
	UC	moreanvils{6.0.1.10} [More Anvils] (MoreAnvils-6.0.1.10.jar) 
	UC	xreliquary{1.9.4-1.3.2.390} [Reliquary] (Reliquary-1.9.4-1.3.2.390.jar) 
	UC	fluidity{6.0.0.6} [Fluidity] (Fluidity-6.0.0.6.jar) 
	UC	forestry{5.0.23.170} [Forestry] (forestry_1.9.4-5.0.23.170.jar) 
	UC	substratum{1.5.0.1} [Substratum] (Substratum-1.9.4-1.5.0.1 (1).jar) 
	UC	foundry{2.0.0.0-beta5} [Foundry] (Foundry-1.9.4-2.0.0.0-beta5.jar) 
	UC	fyrestone{0.6.4.1} [Fyrestone] (fyrestone-0.6.4.1.jar) 
	UC	grapplemod{1.9.4-v7} [Grappling hook mod] (grapplemod-1.9.4-v7.jar) 
	UC	hempfarmer{1.9.4-1976-1.61} [HempFarmer] (hempfarmer-1.9.4-1976-1.61.jar) 
	UC	hopperducts{1.4.7} [Hopper Ducts] (hopperducts-mc1.9.4-1.4.7 (1).jar) 
	UC	inventorysorter{0.9.1+41} [Simple Inventory sorting] (inventorysorter-1.9.4-0.9.1+41.jar) 
	UC	mantle{1.9.4-0.10.2.jenkins149} [Mantle] (Mantle-1.9.4-0.10.2.jar) 
	UC	modernmetals{0.11.0} [Modern Metals] (ModernMetals-0.11.0.jar) 
	UC	moreanvilsvc{3.2} [More Anvils Version Checker] (MoreAnvils-6.0.1.10.jar) 
	UC	yurtmod{5.01} [Nomadic Tents] (NomadicTents[1.9.4]-5.01.jar) 
	UC	fodc{1.8.2} [Ore Dictionary Converter] (OreDictionaryConverter-1.8.2.jar) 
	UC	orespawn{1.0.3} [Ore Spawn] (OreSpawn_1.9.4-1.0.3.jar) 
	UC	harvestcraft{1.9.4-pre} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4c.jar) 
	UC	thutcore{3.1.7} [ThutCore] (thutcore-1.9.4-3.1.7.jar) 
	UE	NBTEditpqb{1.8.9-1.0} [In-game NBTEdit - Pokecube Edition] (Pokecube Core-3.4.8.jar) 
	UE	pokecube{3.4.8} [Pokécube Core] (Pokecube Core-3.4.8.jar) 
	UE	pokecube_ml{0.1.0} [Pokecube Model Loader] (Pokecube Core-3.4.8.jar) 
	UE	pokecube_mobs{2.1.4} [Pokécube Mobs] (Pokecube Mobs-2.1.4.jar) 
	UE	pokecube_adventures{3.4.8} [Pokécube Revival] (Pokecube Revival-3.4.8.jar) 
	UC	pokecube_compat{1.0} [Pokecube Compat] (Pokecube Revival-3.4.8.jar) 
	UC	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.9.4-1.7.4.jar) 
	UC	Roguelike{1.5.3} [Roguelike Dungeons] (RoguelikeDungeons-1.9.4-1.5.3.jar) 
	UC	roots{0.007} [Roots] (roots-0.007.jar) 
	UC	AS_Ruins{16.1} [Ruins Spawning System] (Ruins-1.9.4.jar) 
	UC	SaltMod{1.8.c} [Salty Mod] (SaltyMod-1.9.4-1.8.c_beta-3.jar) 
	UC	simplycaterpillar{6.0.1.19} [Simply Caterpillar] (SimplyCaterpillar-Forge-6.0.1.19.jar) 
	UC	slabcraftmod{5.0} [Slabcraft] (Slabcraftmod v5.0 - MC1.9.4 Forge.jar) 
	UC	staircraftmod{5.0} [Staircraft] (Staircraftmod v5.0 - MC1.9.4 Forge.jar) 
	UC	storagenetwork{1.12.0} [Storage Network] (StorageNetwork-1.9.4-1.12.0.jar) 
	UC	tconstruct{1.9.4-2.3.3.jenkins263} [Tinkers' Construct] (TConstruct-1.9.4-2.3.3.jar) 
	UC	thuttech{3.0.3} [Thut's Tech] (thuttech-3.0.3.jar) 
	UC	torcharrowsmod{1.9.4-2} [TorchArrowsMod] (torcharrows-1.9.4-2.jar) 
	UC	AS_UpdateCheck{1.1.7} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.9.4.jar) 
	UC	wallcraftmod{5.0} [Wallcraft] (Wallcraftmod v5.0 - MC1.9.4 Forge.jar) 
	Loaded coremods (and transformers): 
AppleCore (AppleCore-mc1.9.4-1.3.4.jar)
  squeek.applecore.asm.TransformerModuleHandler
NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
EnderCorePlugin (EnderCore-1.9.4-0.4.0.26-alpha.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)

	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

#### What happens:
Server crashes during start up with the above log after updating to Core 3.4.8

#### What you expected to happen:
A regular boot.

#### Steps to reproduce:

Boot with Core 3.4.8
____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:3.4.8
- Pokecube Revival (if applicable):3.4.8
- Pokecube Mobs (if applicable):2.1.4
- Minecraft: 1.9.4
- Forge:1.9.4-x.1976

**Comment by Thutmose** [comment]
Hmm, rever to 3.4.7 for now, I will see if I can find what went wrong...

**Comment by Thutmose** [comment]
Found the issue, something was wrong with my compiler.  

It will be fixed for 3.4.9, which will be uploaded shortly.
