### ISSUE TITLE
Pokemon fly or fall when riding them

### ISSUE THREAD

**Issue by schindlershadow** [Thutmose/Pokecube#92]
#### Issue Description:
Modpack: Infinix

Sometimes when riding a pokemon they keep rising or falling even when the respective keys are not being pressed.

PokeCube Core: 3.4.5
PokeCube Mobs: 2.1.4
PokeCube Revival: 3.4.5
ThutCore: 3.1.6
Forge: 1976

**Comment by Thutmose** [comment]
hmm, I will look into this, it is only supposed to toggle up/down when they key presses tell it to.

**Comment by schindlershadow** [comment]
I did more testing.

Pokemon randomly move around, but if you mount them when they are about to move they continue to move in that direction without stopping while you're riding them. Not sure if this is the only condition, more testing is needed.

Also sometimes if you order a pokemon to attack something while riding it, it will start falling slowly and you can't really stop it.

**Comment by Thutmose** [comment]
ahh, it is probably something in their AI interfering then, I will look into that.

**Comment by Thutmose** [comment]
I think this should now have been fixed in 3.6.0/4.3.0, Re-open this issue if it occurs again.
