### ISSUE TITLE
Revives do not work on pokemon when durability  is > 0

### ISSUE THREAD

**Issue by schindlershadow** [Thutmose/Pokecube#93]
#### Issue Description:
Modpack: Infinix

Revives do not work on pokemon when the pokeball is not at 0 durability. the revive does get consumed but the pokemon does not get healed

PokeCube Core: 3.4.5
PokeCube Mobs: 2.1.4
PokeCube Revival: 3.4.5
ThutCore: 3.1.6
Forge: 1976

**Comment by Thutmose** [comment]
Will have this fixed for next version, It won't list the recipe as working unless the cube is at 0 health.

**Comment by Thutmose** [comment]
Fixed in pokecube core 3.4.10/4.1.10
