### ISSUE TITLE
Pokemon not getting renamed when evolved

### ISSUE THREAD

**Issue by schindlershadow** [Thutmose/Pokecube#94]
#### Issue Description:
If a pokemon has no nickname, it does not get its new name when it evolves.

PokeCube Core: 3.4.5
PokeCube Mobs: 2.1.4
PokeCube Revival: 3.4.5
ThutCore: 3.1.6
Forge: 1976

**Comment by Thutmose** [comment]
odd, that seems to be working properly in my development environment, have you tried it with any newly caught pokemobs? it could be a leftover bug from when they were all getting named <name>r by the pokedex.

**Comment by schindlershadow** [comment]
yes my newly caught nidorino evolved by moonstone to nidoking and was still named nidorino. Maybe only item evolving pokemon are affected?

**Comment by Thutmose** [comment]
hmm possibly, I will test that.

**Comment by schindlershadow** [comment]
Just happened again http://i.imgur.com/ZqSr2Od.png

**Comment by XileForce** [comment]
Another player also mentioned that their marshtomp was still named mudkip.

**Comment by Thutmose** [comment]
This one hasn't happened recently, I will close it, but make a new one related to it, where sometimes pokemob nicknames change wrongly.
