### ISSUE TITLE
[1.10.2] Client Crash

### ISSUE THREAD

**Issue by XileForce** [Thutmose/Pokecube#96]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (RandomThings-MC1.10-3.7.4.jar)
  LoadingPlugin (Quark-beta-35.jar)
  LoadingPlugin (ChunkAnimator-MC1.9.4-1.2.jar)
  FMLPlugin (InventoryTweaks-1.61-beta-57.jar)
  IC2core (industrialcraft-2-2.6.5-ex110.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 7/2/16 5:35 PM
Description: Ticking player

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at pokecube.core.client.gui.GuiDisplayPokecubeInfo.getPokemobsToDisplay(GuiDisplayPokecubeInfo.java:218)
	at pokecube.core.events.handlers.EventsHandlerClient.clientTick(EventsHandlerClient.java:248)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_12_EventsHandlerClient_clientTick_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:68)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:159)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:365)
	at net.minecraft.entity.player.EntityPlayer.func_184808_cD(EntityPlayer.java:382)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:292)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:212)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at pokecube.core.client.gui.GuiDisplayPokecubeInfo.getPokemobsToDisplay(GuiDisplayPokecubeInfo.java:218)
	at pokecube.core.events.handlers.EventsHandlerClient.clientTick(EventsHandlerClient.java:248)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_12_EventsHandlerClient_clientTick_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:68)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:159)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:365)
	at net.minecraft.entity.player.EntityPlayer.func_184808_cD(EntityPlayer.java:382)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:292)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 1850
	Entity Name: Xileforce
	Entity's Exact location: -198.30, 67.79, 205.23
	Entity's Block location: World: (-199,67,205), Chunk: (at 9,4,13 in -13,12; contains blocks -208,0,192 to -193,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:212)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@296757e9
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_92, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3341587464 bytes (3186 MB) / 5368709120 bytes (5120 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms5120m -Xmx5120m -XX:+UseG1GC -XX:MaxGCPauseMillis=4
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.32 Powered by Forge 12.18.0.2006 97 mods loaded, 97 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAA	FML{8.0.99.99} [Forge Mod Loader] (modpack.jar) 
	UCHIJAAAAAA	Forge{12.18.0.2006} [Minecraft Forge] (modpack.jar) 
	UCHIJAAAAAA	actuallyadditions{1.10.2-r47} [Actually Additions] (ActuallyAdditions-1.10.2-r47.jar) 
	UCHIJAAAAAA	Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar) 
	UCHIJAAAAAA	baublesstuff{2.0.10} [Baubles Stuff] (baublesstuff-2.0.10.jar) 
	UCHIJAAAAAA	bdlib{1.12.0.2} [BD Lib] (bdlib-1.12.0.2-mc1.9.4.jar) 
	UCHIJAAAAAA	BiomesOPlenty{4.1.0.2033} [Biomes O' Plenty] (BiomesOPlenty-1.9.4-4.1.0.2033-universal.jar) 
	UCHIJAAAAAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10-alpha-1.0.0.jar) 
	UCHIJAAAAAA	JEI{3.7.3.223} [Just Enough Items] (jei_1.10.2-3.7.3.223.jar) 
	UCHIJAAAAAA	BloodMagic{1.9.4-2.0.2-48} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.0.2-48.jar) 
	UCHIJAAAAAA	BloodArsenal{1.9.4-2.0.0-10} [Blood Arsenal] (BloodArsenal-1.9.4-2.0.0-10.jar) 
	UCHIJAAAAAA	bookshelf{1.3.0.280} [Bookshelf] (Bookshelf-1.10-1.3.0.280.jar) 
	UCHIJAAAAAA	bookshelfapi{3.1.0} [Bookshelf] (Bookshelf-API-1.9.4-3.1.0.jar) 
	UCHIJAAAAAA	Botania{r1.8-312} [Botania] (Botania-unofficial.r1.8-312.jar) 
	UCHIJAAAAAA	Chameleon{1.9-2.1.4} [Chameleon] (Chameleon-1.9-2.1.4.jar) 
	UCHIJAAAAAA	chisel{@VERSION@} [Chisel] (Chisel-MC1.9.4-0.0.5.28.jar) 
	UCHIJAAAAAA	chiselsandbits{11.3} [Chisels & Bits] (chiselsandbits-11.3.jar) 
	UCHIJAAAAAA	ChunkAnimator{1.2} [Chunk Animator] (ChunkAnimator-MC1.9.4-1.2.jar) 
	UCHIJAAAAAA	ComputerCraft{1.80pr0} [ComputerCraft] (ComputerCraft1.80pr0.jar) 
	UCHIJAAAAAA	gg5cookiemod{0.7} [Cookie Obsession Mod] (CookieObsession-0.7.jar) 
	UCHIJAAAAAA	cyclopscore{0.6.3} [Cyclops Core] (CyclopsCore-1.9.4-0.6.3-350.jar) 
	UCHIJAAAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJAAAAAA	DarkUtils{1.1.2.52} [Dark Utilities] (DarkUtilities-1.9.4-1.1.2.55.jar) 
	UCHIJAAAAAA	ElecCore{1.5.292} [ElecCore] (ElecCore-1.9.4-1.5.292.jar) 
	UCHIJAAAAAA	deepresonance{1.2.0beta35} [DeepResonance] (deepresonance-1.9.4-1.2.0beta35.jar) 
	UCHIJAAAAAA	defaultoptions{6.1.3} [Default Options] (DefaultOptions-mc1.10-6.1.3.jar) 
	UCHIJAAAAAA	ea{v2.4.1a-mc1.10.2} [Ebon Arts] (EbonArts-v2.4.1a-mc1.10.2.jar) 
	UCHIJAAAAAA	endercore{1.10-0.4.0.33-alpha} [EnderCore] (EnderCore-1.10-0.4.0.33-alpha.jar) 
	UCHIJAAAAAA	EnderIO{1.10-3.0.0.55_alpha} [Ender IO] (EnderIO-1.10-3.0.0.55_alpha.jar) 
	UCHIJAAAAAA	enderrift{1.1.0} [Ender-Rift] (EnderRift-1.9.4-1.1.0.jar) 
	UCHIJAAAAAA	EnderZoo{1.10-1.2.3.43} [Ender Zoo] (EnderZoo-1.10-1.2.3.43.jar) 
	UCHIJAAAAAA	ValkyrieLib{1.10-0.10.0} [Valkyrie Lib] (valkyrielib-1.10-0.10.0.jar) 
	UCHIJAAAAAA	EnvironmentalTech{1.10-0.10.0b} [Environmental Tech] (environmentaltech-1.10-0.10.0b.jar) 
	UCHIJAAAAAA	ExtraBitManipulation{1.9-2.1.2} [Extra Bit Manipulation] (ExtraBitManipulation-1.9.4-2.1.0.jar) 
	UCHIJAAAAAA	IronChest{6.0.146.788} [Iron Chest] (ironchest-1.9.4-6.0.146.788.jar) 
	UCHIJAAAAAA	randomthings{3.7.4} [Random Things] (RandomThings-MC1.10-3.7.4.jar) 
	UCHIJAAAAAA	jeresources{0.4.6.39} [Just Enough Resources] (JustEnoughResources-1.9.4-0.4.6.39.jar) 
	UCHIJAAAAAA	xreliquary{1.10-1.3.2.416} [Reliquary] (Reliquary-1.10-1.3.2.416.jar) 
	UCHIJAAAAAA	fluidity{6.0.0.6} [Fluidity] (Fluidity-6.0.0.6.jar) 
	UCHIJAAAAAA	fluxducts{1.0.4} [Flux Ducts] (fluxducts-mc1.9.4-1.0.4.jar) 
	UCHIJAAAAAA	forestry{5.1.8.189} [Forestry] (forestry_1.10.2-5.1.8.189.jar) 
	UCHIJAAAAAA	IC2{2.6.5-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.5-ex110.jar) 
	UCHIJAAAAAA	advgenerators{0.9.20.2} [Advanced Generators] (generators-0.9.20.2-mc1.9.4.jar) 
	UCHIJAAAAAA	gg5lootmod{0.82} [Loot Mod] (gg5lootmod-1.10-0.82.jar) 
	UCHIJAAAAAA	gravestone{1.5.0} [Gravestone] (Gravestone Mod 1.5.0.jar) 
	UCHIJAAAAAA	gg5gravsuit{0.3} [GameGunner5's GravSuits] (GravSuit-1.10-0.4.jar) 
	UCHIJAAAAAA	HelpFixer{1.3.14} [HelpFixer] (HelpFixer-1.9.4-1.3.14.jar) 
	UCHIJAAAAAA	InfernalMobs{1.7.1} [Infernal Mobs] (InfernalMobs-1.10.jar) 
	UCHIJAAAAAA	integrateddynamics{0.3.10} [Integrated Dynamics] (IntegratedDynamics-1.9.4-0.3.10-247.jar) 
	UCHIJAAAAAA	inventorytweaks{1.61-beta-57-c028bbc} [Inventory Tweaks] (InventoryTweaks-1.61-beta-57.jar) 
	UCHIJAAAAAA	japta{1.9.0} [JAPTA] (JAPTA-1.9.4-1.9.0.jar) 
	UCHIJAAAAAA	journeymap{1.9.4-5.2.1} [JourneyMap] (journeymap-1.9.4-5.2.1-fairplay.jar) 
	UCHIJAAAAAA	LunatriusCore{1.1.2.35} [LunatriusCore] (LunatriusCore-1.9.4-1.1.2.35-universal.jar) 
	UCHIJAAAAAA	mantle{1.10-0.10.3.jenkins156} [Mantle] (Mantle-1.10-0.10.3.jar) 
	UCHIJAAAAAA	Morphtool{GRADLE:VERSION-GRADLE:BUILD} [Morph-o-Tool] (Morph-o-Tool-1.0-4.jar) 
	UCHIJAAAAAA	Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat 1.3-10.jar) 
	UCHIJAAAAAA	nethermetals{1.1.0} [Nether Metals] (NetherMetals_1.9-1.1.0.jar) 
	UCHIJAAAAAA	recipehandler{0.4} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.4(1.9).jar) 
	UCHIJAAAAAA	OpenComputers{1.6.0.2-beta.4} [OpenComputers] (OpenComputers-MC1.10-1.6.0.2-beta.4.jar) 
	UCHIJAAAAAA	openglasses{1.3} [OC Glasses] (OpenGlasses-1.3.jar) 
	UCHIJAAAAAA	openradio{0.7.3} [OpenRadio] (OpenRadio-0.7.3-MC1.9.4.jar) 
	UCHIJAAAAAA	fodc{1.8.2} [Ore Dictionary Converter] (OreDictionaryConverter-1.8.2.jar) 
	UCHIJAAAAAA	harvestcraft{1.9.4-pre} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4c.jar) 
	UCHIJAAAAAA	thutcore{3.1.8} [ThutCore] (thutcore-1.9.4-3.1.8.jar) 
	UCHIJAAAAAA	NBTEditpqb{1.8.9-1.0} [In-game NBTEdit - Pokecube Edition] (Pokecube Core-4.1.9.jar) 
	UCHIJAAAAAA	pokecube{4.1.9} [Pokécube Core] (Pokecube Core-4.1.9.jar) 
	UCHIJAAAAAA	pokecube_ml{0.1.0} [Pokecube Model Loader] (Pokecube Core-4.1.9.jar) 
	UCHIJAAAAAA	pokecube_mobs{2.1.4} [Pokécube Mobs] (Pokecube Mobs-2.1.4.jar) 
	UCHIJAAAAAA	pokecube_adventures{4.1.8} [Pokécube Revival] (Pokecube Revival-4.1.8.jar) 
	UCHIJAAAAAA	pokecube_compat{1.0} [Pokecube Compat] (Pokecube Revival-4.1.8.jar) 
	UCHIJAAAAAA	progressiveautomation{1.6.46} [Progressive Automation] (ProgressiveAutomation-1.9.4-1.6.46.jar) 
	UCHIJAAAAAA	quantumflux{2.0.7} [QuantumFlux] (quantumflux-1.9.4-2.0.7.jar) 
	UCHIJAAAAAA	Quark{beta-35} [Quark] (Quark-beta-35.jar) 
	UCHIJAAAAAA	quickhotbar{1.04} [Quick Hotbar] (quickhotbar_194_1.04.jar) 
	UCHIJAAAAAA	reborncore{2.5.4.47} [RebornCore] (RebornCore-1.9.4-2.5.4.47-universal.jar) 
	UCHIJAAAAAA	reborncore-mcmultipart{2.5.4.47} [reborncore-MCMultiPart] (RebornCore-1.9.4-2.5.4.47-universal.jar) 
	UCHIJAAAAAA	StorageDrawers{1.9.4-3.1.10} [Storage Drawers] (StorageDrawers-1.9.4-3.1.10.jar) 
	UCHIJAAAAAA	refinedstorage{0.8.3} [Refined Storage] (refinedstorage-0.8.3.jar) 
	UCHIJAAAAAA	rftools{4.67} [RFTools] (rftools-1.10-4.67.jar) 
	UCHIJAAAAAA	Roguelike{1.5.4} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.4.jar) 
	UCHIJAAAAAA	roots{0.007} [Roots] (roots-0.007.jar) 
	UCHIJAAAAAA	solarvillage{1.1.0.13} [Solar Village] (SolarVillage-1.10-1.1.0.14.jar) 
	UCHIJAAAAAA	soulshardstow{1.10-2.5.0-34} [Soul Shards - The Old Ways] (SoulShards-TOW-1.10-2.5.0-34.jar) 
	UCHIJAAAAAA	soundfilters{0.9_for_1.9} [Sound Filters] (SoundFilters-0.9_for_1.9.4.jar) 
	UCHIJAAAAAA	tconstruct{1.10-2.3.3a.jenkins271} [Tinkers' Construct] (TConstruct-1.10-2.3.3a.jar) 
	UCHIJAAAAAA	techreborn{1.3.2.120} [TechReborn] (TechReborn-1.9.4-1.3.2.120-universal.jar) 
	UCHIJAAAAAA	Tesla{1.1.0.24} [TESLA] (Tesla-1.9.4-1.1.0.24.jar) 
	UCHIJAAAAAA	tinker_io{beta 2.3.0c} [Tinker I/O] (tinker_io-1.10-beta 2.3.0c.jar) 
	UCHIJAAAAAA	TinkersAddons{1.0.2} [Tinkers' Addons] (Tinkers' Addons-1.9.4-1.0.2.jar) 
	UCHIJAAAAAA	tis3d{0.9.0.1} [TIS-3D] (TIS-3D-MC1.10-0.9.0.1.jar) 
	UCHIJAAAAAA	WailaHarvestability{1.1.7} [Waila Harvestability] (WailaHarvestability-mc1.10-1.1.7.jar) 
	UCHIJAAAAAA	ICSE{1.1.0.0} [I Can See Everything] (Wawla-1.10-2.3.0.193.jar) 
	UCHIJAAAAAA	wawla{2.3.0.193} [What Are We Looking At] (Wawla-1.10-2.3.0.193.jar) 
	UCHIJAAAAAA	worldedit{6.1.3} [WorldEdit] (worldedit-forge-mc1.9.4-6.1.3-dist.jar) 
	UCHIJAAAAAA	WorldEditCuiFe{1.0.2} [WorldEdit CUI Forge Edition] (WorldEditCuiFe-v1.0.4-mf-1.10-12.18.0.1984.jar) 
	UCHIJAAAAAA	ZDoctorBB{1.1} [Blood Baubles] (ZDoctorBB-1.1.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (RandomThings-MC1.10-3.7.4.jar)
  lumien.randomthings.asm.ClassTransformer
LoadingPlugin (Quark-beta-35.jar)
  vazkii.quark.base.asm.ClassTransformer
LoadingPlugin (ChunkAnimator-MC1.9.4-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.61-beta-57.jar)
  invtweaks.forge.asm.ContainerTransformer
IC2core (industrialcraft-2-2.6.5-ex110.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* actuallyadditionsapi (17) from ActuallyAdditions-1.10.2-r47.jar
		* Baubles|API (1.1.1.0) from Baubles-1.9.4-1.2.1.0.jar
		* BloodMagic|API (@VERSION@) from BloodMagic-1.9.4-2.0.2-48.jar
		* BotaniaAPI (79) from Botania-unofficial.r1.8-312.jar
		* CapabilityCore|base (1.01) from EnderRift-1.9.4-1.1.0.jar
		* CapabilityCore|energy (1.01) from EnderRift-1.9.4-1.1.0.jar
		* CapabilityCore|tweakable (1.01) from EnderRift-1.9.4-1.1.0.jar
		* ChiselAPI (0.0.1) from Chisel-MC1.9.4-0.0.5.28.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.9.4-0.0.5.28.jar
		* ChiselsAndBitsAPI (1.8.1) from chiselsandbits-11.3.jar
		* CoFHAPI (1.8.9R1.2.0B1) from quantumflux-1.9.4-2.0.7.jar
		* CoFHAPI|block (1.8.9R1.2.0B1) from ProgressiveAutomation-1.9.4-1.6.46.jar
		* CoFHAPI|core (1.8.9R1.2.0B1) from valkyrielib-1.10-0.10.0.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from refinedstorage-0.8.3.jar
		* CoFHAPI|inventory (1.8.9R1.2.0B1) from valkyrielib-1.10-0.10.0.jar
		* CoFHAPI|item (1.8.9R1.2.0B1) from valkyrielib-1.10-0.10.0.jar
		* CoFHAPI|tileentity (1.8.9R1.2.0B1) from ProgressiveAutomation-1.9.4-1.6.46.jar
		* commoncapabilities|api (0.0.1) from IntegratedDynamics-1.9.4-0.3.10-247.jar
		* ComputerCraft|API (1.80pr0) from ComputerCraft1.80pr0.jar
		* ComputerCraft|API|FileSystem (1.80pr0) from ComputerCraft1.80pr0.jar
		* ComputerCraft|API|Lua (1.80pr0) from ComputerCraft1.80pr0.jar
		* ComputerCraft|API|Media (1.80pr0) from ComputerCraft1.80pr0.jar
		* ComputerCraft|API|Peripheral (1.80pr0) from ComputerCraft1.80pr0.jar
		* ComputerCraft|API|Permissions (1.80pr0) from ComputerCraft1.80pr0.jar
		* ComputerCraft|API|Redstone (1.80pr0) from ComputerCraft1.80pr0.jar
		* ComputerCraft|API|Turtle (1.80pr0) from ComputerCraft1.80pr0.jar
		* DR-API (1.0.4-Beta) from deepresonance-1.9.4-1.2.0beta35.jar
		* ElecCore|Abilities (#API_VER#) from ElecCore-1.9.4-1.5.292.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.10-3.0.0.55_alpha.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.10-3.0.0.55_alpha.jar
		* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.10-3.0.0.55_alpha.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.10-3.0.0.55_alpha.jar
		* environmentaltech.api (1.10-0.10.0b) from environmentaltech-1.10-0.10.0b.jar
		* ForestryAPI|apiculture (4.8.0) from forestry_1.10.2-5.1.8.189.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.10.2-5.1.8.189.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.10.2-5.1.8.189.jar
		* ForestryAPI|core (5.0.0) from forestry_1.10.2-5.1.8.189.jar
		* ForestryAPI|farming (2.1.0) from forestry_1.10.2-5.1.8.189.jar
		* ForestryAPI|food (1.1.0) from forestry_1.10.2-5.1.8.189.jar
		* ForestryAPI|fuels (2.0.1) from forestry_1.10.2-5.1.8.189.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.10.2-5.1.8.189.jar
		* ForestryAPI|greenhouse (5.0.0) from forestry_1.10.2-5.1.8.189.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.10.2-5.1.8.189.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.10.2-5.1.8.189.jar
		* ForestryAPI|mail (3.0.0) from forestry_1.10.2-5.1.8.189.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.10.2-5.1.8.189.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.10.2-5.1.8.189.jar
		* ForestryAPI|storage (3.0.0) from forestry_1.10.2-5.1.8.189.jar
		* ForestryAPI|world (2.1.0) from forestry_1.10.2-5.1.8.189.jar
		* GraphApi (1.1.1) from EnderRift-1.9.4-1.1.0.jar
		* IC2API (1.0) from industrialcraft-2-2.6.5-ex110.jar
		* integrateddynamics|api (0.1.0) from IntegratedDynamics-1.9.4-0.3.10-247.jar
		* jeresources|API (0.4.6.39) from JustEnoughResources-1.9.4-0.4.6.39.jar
		* journeymap|client-api (1.2) from journeymap-1.9.4-5.2.1-fairplay.jar
		* journeymap|client-api-display (1.2) from journeymap-1.9.4-5.2.1-fairplay.jar
		* journeymap|client-api-event (1.2) from journeymap-1.9.4-5.2.1-fairplay.jar
		* journeymap|client-api-model (1.2) from journeymap-1.9.4-5.2.1-fairplay.jar
		* journeymap|client-api-util (1.2) from journeymap-1.9.4-5.2.1-fairplay.jar
		* JustEnoughItemsAPI (4.0.0) from jei_1.10.2-3.7.3.223.jar
		* McJtyLib (1.10-1.9.3) from mcjtylib-1.10-1.9.3.jar
		* OpenComputersAPI|Component (6.0.0-alpha) from OpenComputers-MC1.10-1.6.0.2-beta.4.jar
		* OpenComputersAPI|Core (6.0.0-alpha) from OpenComputers-MC1.10-1.6.0.2-beta.4.jar
		* OpenComputersAPI|Driver (6.0.0-alpha) from OpenComputers-MC1.10-1.6.0.2-beta.4.jar
		* OpenComputersAPI|Driver|Item (6.0.0-alpha) from OpenComputers-MC1.10-1.6.0.2-beta.4.jar
		* OpenComputersAPI|Event (6.0.0-alpha) from OpenComputers-MC1.10-1.6.0.2-beta.4.jar
		* OpenComputersAPI|FileSystem (6.0.0-alpha) from OpenComputers-MC1.10-1.6.0.2-beta.4.jar
		* OpenComputersAPI|Internal (6.0.0-alpha) from OpenComputers-MC1.10-1.6.0.2-beta.4.jar
		* OpenComputersAPI|Machine (6.0.0-alpha) from OpenComputers-MC1.10-1.6.0.2-beta.4.jar
		* OpenComputersAPI|Manual (6.0.0-alpha) from OpenComputers-MC1.10-1.6.0.2-beta.4.jar
		* OpenComputersAPI|Network (6.0.0-alpha) from OpenComputers-MC1.10-1.6.0.2-beta.4.jar
		* OpenComputersAPI|Prefab (6.0.0-alpha) from OpenComputers-MC1.10-1.6.0.2-beta.4.jar
		* reborncoreAPI (2.5.4.47) from RebornCore-1.9.4-2.5.4.47-universal.jar
		* SoulShardsTOW|API (0.1.5) from SoulShards-TOW-1.10-2.5.0-34.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.9.4-3.1.10.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.9.4-3.1.10.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from refinedstorage-0.8.3.jar
		* StorageDrawersAPI|inventory (1.7.10-1.2.0) from refinedstorage-0.8.3.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.9.4-3.1.10.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.9.4-3.1.10.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from refinedstorage-0.8.3.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.9.4-3.1.10.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from refinedstorage-0.8.3.jar
		* techrebornAPI (1.3.2.120) from TechReborn-1.9.4-1.3.2.120-universal.jar
		* Tesla|API (1.1.0.24) from Tesla-1.9.4-1.1.0.24.jar
		* thut|API (1.0.0) from Pokecube Core-4.1.9.jar
		* tis3dAPI (0.9.0.1) from TIS-3D-MC1.10-0.9.0.1.jar
		* ValkyrieLib.api (1.10-0.10.0) from valkyrielib-1.10-0.10.0.jar
		* WailaAPI (1.3) from Waila-1.7.0-B3_1.9.4.jar
	EnderIO: No known problems detected.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Xileforce'/1850, l='New World', x=-198.30, y=67.79, z=205.23]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

PokeCube Core: 4.1.9
PokeCube Mobs: 2.1.4
PokeCube Revival: 4.1.8
ThutCore: 3.1.8
Forge: 12.18.0.2006

**Comment by Thutmose** [comment]
Uploaded 4.1.10 to curse, should fix this.
