### ISSUE TITLE
Another trainers spawning instead of swimmers on water

### ISSUE THREAD

**Issue by jochuan** [Thutmose/Pokecube#98]
#### Issue Description:
trainer that are not swimmers are spawning in the ocean

#### What happens:

Only swimmers should spawn in the ocean but others trainor like burglars and campers spawn there too
![2016-07-04_18 06 37](https://cloud.githubusercontent.com/assets/11268912/16570175/ff00b42e-4216-11e6-8203-a7feffefb0c2.png)

#### What you expected to happen:

Only swimmers or trainers using surf (if implemented) should spawn there

#### Steps to reproduce:

1.go to the ocean
2.find a trainer

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:3.4.9
- Pokecube Revival (if applicable):3.4.8
- Pokecube Mobs (if applicable):2.1.5
- Minecraft: 1.9.4
- Forge:1976

**Comment by Thutmose** [comment]
hmm, I need to fix that, I thought I had made it so only swimmers could spawn there...

**Comment by Thutmose** [comment]
Fixed in Revival 3.4.11/4.1.11
