### ISSUE TITLE
Pokemons aren't going to the pc after the player death

### ISSUE THREAD

**Issue by jochuan** [Thutmose/Pokecube#99]
#### Issue Description:
the pokemons aren't going to the pc after you die

#### What happens:

after dying they still in the same place as dropped items

#### What you expected to happen:

they should go to the pc after you die

#### Steps to reproduce:

1.have pokemons in the inventory
2.die

____
#### Affected Versions (Do *not* use "latest"):

- Pokecube Core:3.4.9
- Pokecube Revival (if applicable):3.4.8
- Pokecube Mobs (if applicable):2.1.5
- Minecraft: 1.9.4
- Forge:1976

**Comment by Thutmose** [comment]
I will look into this, I wonder if the player drops event isn't firing for some reason...

**Comment by Thutmose** [comment]
Found the issue, I wasn't handling the event properly, will be fixed in next release.

**Comment by Thutmose** [comment]
Fixed in 3.4.12/4.1.12
